import { closeSync, existsSync, mkdirSync, openSync, readFileSync, renameSync, writeFileSync } from "fs";
import { fsyncSync } from "../../fs-durable.ts";
import { dirname, isAbsolute, join } from "path";

export type BridgeCommandKind = "start-run" | "resume-run" | "send-input" | "interrupt" | "approval-response" | "add-dir" | "set-access" | "new-session";
export interface BridgeCommand { commandId: string; runId: string; taskId: string; sessionId: string; providerId: string; kind: BridgeCommandKind; inputHash: string; clientMutationId?: string; cursor: number; terminal: boolean; createdAt: string; errorCode?: string; authorizedRoots?: string[]; authorizedAccess?: "workspace" | "full-access" | "bypass"; }
interface SessionWatermark { sessionId: string; at: string; eventId: string; }
interface BridgeFile { schemaVersion: 1; commands: BridgeCommand[]; sessionWatermarks?: SessionWatermark[]; }
const pathFor = (root: string) => join(root, "session-runner-bridge.json");
const hash = (value: string) => new Bun.CryptoHasher("sha256").update(value).digest("hex");
function read(root: string): BridgeFile { const file = pathFor(root); if (!existsSync(file)) return { schemaVersion: 1, commands: [] }; const raw = JSON.parse(readFileSync(file, "utf8")); if (raw?.schemaVersion !== 1 || !Array.isArray(raw.commands) || Object.keys(raw).some((k) => !["schemaVersion", "commands", "sessionWatermarks"].includes(k))) throw new Error("session runner bridge journal 非法"); for (const c of raw.commands) { if (!c || typeof c !== "object" || !["start-run", "resume-run", "send-input", "interrupt", "approval-response", "add-dir", "set-access", "new-session"].includes(c.kind) || Object.keys(c).some((k) => !["commandId", "runId", "taskId", "sessionId", "providerId", "kind", "inputHash", "clientMutationId", "cursor", "terminal", "createdAt", "errorCode", "authorizedRoots", "authorizedAccess"].includes(k)) || ["commandId", "runId", "taskId", "sessionId", "providerId", "inputHash", "createdAt"].some((k) => typeof c[k] !== "string" || !c[k]) || (c.clientMutationId !== undefined && (typeof c.clientMutationId !== "string" || !c.clientMutationId || c.clientMutationId.length > 128)) || !Number.isSafeInteger(c.cursor) || c.cursor < 0 || typeof c.terminal !== "boolean" || (c.errorCode !== undefined && typeof c.errorCode !== "string") || (c.authorizedRoots !== undefined && (!Array.isArray(c.authorizedRoots) || c.authorizedRoots.some((r: unknown) => typeof r !== "string" || !isAbsolute(r)))) || (c.authorizedAccess !== undefined && !["workspace", "full-access", "bypass"].includes(c.authorizedAccess))) throw new Error("session runner bridge command 非法"); } if (raw.sessionWatermarks !== undefined && (!Array.isArray(raw.sessionWatermarks) || raw.sessionWatermarks.some((w: any) => !w || typeof w.sessionId !== "string" || typeof w.at !== "string" || typeof w.eventId !== "string"))) throw new Error("session runner bridge watermark 非法"); return raw; }
function write(root: string, value: BridgeFile): void { mkdirSync(root, { recursive: true }); const file = pathFor(root), tmp = `${file}.${process.pid}.${crypto.randomUUID()}.tmp`; writeFileSync(tmp, JSON.stringify(value, null, 2) + "\n", { flag: "wx", mode: 0o600 }); const fd = openSync(tmp, "r"); try { fsyncSync(fd); } finally { closeSync(fd); } renameSync(tmp, file); const dfd = openSync(dirname(file), "r"); try { fsyncSync(dfd); } finally { closeSync(dfd); } }
type ReserveInput = Omit<BridgeCommand, "commandId" | "runId" | "cursor" | "terminal" | "createdAt" | "inputHash"> & { serializedInput: string; targetRunId?: string; identity?: { commandId: string; runId: string } };
export class SessionRunnerBridgeStore {
  constructor(readonly dataRoot: string) {}
  private match(store: BridgeFile, input: ReserveInput): BridgeCommand | undefined {
    const inputHash = hash(input.serializedInput), turns = new Set<BridgeCommandKind>(["start-run", "resume-run", "send-input"]), isTurn = turns.has(input.kind);
    return store.commands.find((c) => !c.terminal && c.sessionId === input.sessionId && c.taskId === input.taskId && c.providerId === input.providerId && c.inputHash === inputHash && (!isTurn || (!!input.clientMutationId && c.clientMutationId === input.clientMutationId)) && (c.kind === input.kind || (turns.has(c.kind) && turns.has(input.kind))) && (!input.targetRunId || c.runId === input.targetRunId) && JSON.stringify(c.authorizedRoots ?? []) === JSON.stringify(input.authorizedRoots ?? []) && c.authorizedAccess === input.authorizedAccess);
  }
  /** 同 reserve 的匹配口径，但只看不写：调用方需要先判断「这是不是一次重试」再决定走哪条路。 */
  find(input: ReserveInput): BridgeCommand | undefined { const existing = this.match(read(this.dataRoot), input); return existing ? structuredClone(existing) : undefined; }
  reserve(input: ReserveInput): { command: BridgeCommand; reused: boolean } {
    const store = read(this.dataRoot), inputHash = hash(input.serializedInput), existing = this.match(store, input);
    if (existing) return { command: structuredClone(existing), reused: true };
    const command: BridgeCommand = { commandId: input.identity?.commandId ?? crypto.randomUUID(), runId: input.identity?.runId ?? input.targetRunId ?? crypto.randomUUID(), taskId: input.taskId, sessionId: input.sessionId, providerId: input.providerId, kind: input.kind, inputHash, cursor: 0, terminal: false, createdAt: new Date().toISOString(), ...(input.clientMutationId ? { clientMutationId: input.clientMutationId } : {}), ...(input.authorizedRoots ? { authorizedRoots: [...input.authorizedRoots] } : {}), ...(input.authorizedAccess ? { authorizedAccess: input.authorizedAccess } : {}) };
    store.commands.push(command); write(this.dataRoot, store); return { command: structuredClone(command), reused: false };
  }
  list(sessionId?: string): BridgeCommand[] { return read(this.dataRoot).commands.filter((c) => !sessionId || c.sessionId === sessionId).map((c) => structuredClone(c)); }
  advance(commandId: string, cursor: number, terminal: boolean): void { const store = read(this.dataRoot), c = store.commands.find((x) => x.commandId === commandId); if (!c) throw new Error("bridge command 不存在"); if (cursor < c.cursor) return; if (cursor === c.cursor && (!terminal || c.terminal)) return; c.cursor = cursor; c.terminal ||= terminal; write(this.dataRoot, store); }
  markError(commandId: string, errorCode?: string): void { const store = read(this.dataRoot), c = store.commands.find((x) => x.commandId === commandId); if (!c || c.errorCode === errorCode) return; if (errorCode) c.errorCode = errorCode; else delete c.errorCode; write(this.dataRoot, store); }
  isNewSessionEvent(sessionId: string, at: string, eventId: string): boolean { const old = (read(this.dataRoot).sessionWatermarks ?? []).find((x) => x.sessionId === sessionId); return !old || at > old.at || (at === old.at && eventId > old.eventId); }
  markSessionEvent(sessionId: string, at: string, eventId: string): void { const store = read(this.dataRoot), list = store.sessionWatermarks ?? (store.sessionWatermarks = []), old = list.find((x) => x.sessionId === sessionId); if (old && (old.at > at || (old.at === at && old.eventId >= eventId))) return; if (old) Object.assign(old, { at, eventId }); else list.push({ sessionId, at, eventId }); write(this.dataRoot, store); }
}
