import { chmodSync, mkdirSync, mkdtempSync, realpathSync, rmSync, statSync, writeFileSync } from "fs";
import { join } from "path";
import { readRunnerAttachment } from "../../runner/attachments.ts";
import { AGENT_IMAGE_PROVIDER_LINE_MAX_BYTES, normalizeCodexContentImages } from "../../runner/agent-images.ts";
import type { RunnerCommandRecord, RunnerReasonCode } from "../../runner/journals.ts";
import type { ProviderEventInput, RunnerProvider } from "../../runner/server.ts";
import { readCodexTranscriptAsync } from "../transcript-history-async.ts";
import { buildCodexArgs, CODEX_PROVIDER_CAPABILITIES, CODEX_PROVIDER_ID, parseCodexAccess, parseCodexAddDir, parseCodexNewSession, parseCodexSendInput, parseCodexStartInput, type CodexImage, type CodexOptions } from "./protocol.ts";
import { emitCoreLog } from "../../kernel/observability/contracts.ts";

type Event = ProviderEventInput;
type Turn = { command: RunnerCommandRecord; proc?: Bun.Subprocess; queue: Queue; terminal: boolean; interrupted: boolean; interrupting: boolean; timedOut: boolean; failure?: { reason: RunnerReasonCode; message: string }; temp?: string; started: boolean; outputDone?: Promise<void>; stderrDone?: Promise<void>; stderrTail: string; stderrEmitted: boolean; lastActivityAt: number; watchdog?: ReturnType<typeof setInterval>; snapshots: Map<string, string> };
type Session = { id: string; cwd: string; options: CodexOptions; nativeRef?: string; turn?: Turn; operation?: string };
class ProviderError extends Error { constructor(readonly code: string, message: string) { super(message); } }
const fail = (code: string, message: string) => new ProviderError(code, message);
class Queue { values: Event[] = []; waiters: Array<(v: IteratorResult<Event>) => void> = []; ended = false; push(v: Event) { if (this.ended) return; const w = this.waiters.shift(); w ? w({ value: v, done: false }) : this.values.push(v); } end() { if (this.ended) return; this.ended = true; for (const w of this.waiters.splice(0)) w({ value: undefined as never, done: true }); } async *iterate() { while (true) { if (this.values.length) { yield this.values.shift()!; continue; } if (this.ended) return; const n = await new Promise<IteratorResult<Event>>((r) => this.waiters.push(r)); if (n.done) return; yield n.value; } } }
const plain = (v: unknown): v is Record<string, unknown> => !!v && typeof v === "object" && !Array.isArray(v);
const token = (v: unknown) => Number.isSafeInteger(v) && (v as number) >= 0 ? v as number : 0;
const nativeRefPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const now = () => new Date().toISOString();

export type CodexProviderOptions = { dataRoot?: string; maxInvalidLines?: number; maxStdoutBufferBytes?: number; stderrRingBytes?: number; processExitGraceMs?: number; idleTimeoutMs?: number; interruptGraceMs?: number };
export class CodexRunnerProvider implements RunnerProvider {
  readonly id = CODEX_PROVIDER_ID; readonly version = "1.0.0"; readonly capabilities = CODEX_PROVIDER_CAPABILITIES;
  readonly metrics = { invalidLines: 0, droppedFrames: 0, notices: 0 };
  private sessions = new Map<string, Session>(); private sequences = new Map<string, number>(); private closing = false;
  private options: Required<Omit<CodexProviderOptions, "dataRoot">> & { dataRoot?: string };
  constructor(private command: readonly string[] = ["codex"], private env: Record<string, string | undefined> = process.env, options: CodexProviderOptions = {}) {
    if (!command.length || command.some((x) => !x)) throw new Error("Codex command 非法");
    this.options = { maxInvalidLines: options.maxInvalidLines ?? 3, maxStdoutBufferBytes: options.maxStdoutBufferBytes ?? AGENT_IMAGE_PROVIDER_LINE_MAX_BYTES, stderrRingBytes: options.stderrRingBytes ?? 16 * 1024, processExitGraceMs: options.processExitGraceMs ?? 5_000, idleTimeoutMs: options.idleTimeoutMs ?? 15 * 60_000, interruptGraceMs: options.interruptGraceMs ?? 5_000, dataRoot: options.dataRoot };
  }
  readHistory(input: { nativeRef: string; providerHome?: string }) { return readCodexTranscriptAsync(input.nativeRef, input.providerHome, this.env.HOME); }
  async close() { await this.shutdown(); }
  getMetrics() { return { ...this.metrics, activeSessions: [...this.sessions.values()].filter((s) => !!s.turn).length }; }
  async shutdown() { this.closing = true; const turns = [...this.sessions.values()].map((s) => s.turn).filter(Boolean) as Turn[]; for (const t of turns) { t.terminal = true; t.queue.end(); this.signal(t, "SIGKILL"); } await Promise.allSettled(turns.map((t) => t.proc?.exited)); for (const t of turns) this.cleanup(t); this.sessions.clear(); }
  async abort(command: RunnerCommandRecord) { const s = this.sessions.get(command.sessionId), t = s?.turn; if (!t || t.command.commandId !== command.commandId) return; t.terminal = true; t.queue.end(); this.signal(t, "SIGKILL"); await t.proc?.exited.catch(() => -1); this.cleanup(t); }
  async *execute(command: RunnerCommandRecord, input: string): AsyncIterable<Event> {
    try {
      if (this.closing) throw fail("PROVIDER_UNAVAILABLE", "Codex Provider 正在关闭");
      switch (command.kind) {
        case "start-run": yield* this.start(command, input); return;
        case "resume-run": yield* this.resume(command, input); return;
        case "send-input": yield* this.send(command, input); return;
        case "interrupt": yield* this.interrupt(command); return;
        case "add-dir": yield* this.configure(command, "add-dir", (s) => { s.options.extraDirs = [...new Set([...s.options.extraDirs, parseCodexAddDir(input)])]; }); return;
        case "set-access": yield* this.configure(command, "set-access", (s) => { s.options = { ...s.options, access: parseCodexAccess(input) }; }); return;
        case "new-session": parseCodexNewSession(input); yield* this.configure(command, "new-session", (s) => { s.nativeRef = undefined; }); return;
        case "approval-response": throw fail("PROVIDER_CAPABILITY_UNSUPPORTED", "Codex exec 不提供可验证的审批响应协议");
        default: throw fail("PROVIDER_CAPABILITY_UNSUPPORTED", `Codex Provider 不支持 ${(command as any).kind}`);
      }
    } catch (e) { if (e instanceof ProviderError || typeof (e as any)?.code === "string") throw e; throw fail("PROVIDER_INPUT_INVALID", e instanceof Error ? e.message : "Codex input 非法"); }
    finally { this.sequences.delete(command.commandId); }
  }
  private event(c: RunnerCommandRecord, type: Event["type"], extra: Partial<Event> = {}, durability?: Event["durability"]): Event { const sequence = (this.sequences.get(c.commandId) ?? 0) + 1; this.sequences.set(c.commandId, sequence); const h = new Bun.CryptoHasher("sha256").update(c.commandId).digest("hex").slice(0, 24); return { eventId: `codex:${h}:${sequence}`, type, at: now(), commandId: c.commandId, runId: c.runId, sessionId: c.sessionId, providerId: c.providerId, ...extra, ...(durability ? { durability } : {}) } as Event; }
  private cwd(value: string) { try { const v = realpathSync(value); if (!statSync(v).isDirectory()) throw 0; return v; } catch { throw fail("PROVIDER_CWD_INVALID", "Codex cwd 不存在或不是目录"); } }
  private async *start(c: RunnerCommandRecord, input: string) { const p = parseCodexStartInput(input); const prior = this.sessions.get(c.sessionId); if (prior?.turn || prior?.operation) throw fail("PROVIDER_SESSION_BUSY", "Codex session 正在执行"); const s: Session = { id: c.sessionId, cwd: this.cwd(p.cwd), options: p.options }; this.sessions.set(c.sessionId, s); yield* this.turn(s, c, p.text, p.images); }
  private async *resume(c: RunnerCommandRecord, input: string) { const p = parseCodexSendInput(input); if (!p.cwd || !p.options || !p.nativeRef) throw fail("PROVIDER_INPUT_INVALID", "resume-run 必须显式携带 cwd/options/nativeRef"); const cwd = this.cwd(p.cwd), prior = this.sessions.get(c.sessionId); if (prior?.turn || prior?.operation) throw fail("PROVIDER_SESSION_BUSY", "Codex session 正在执行"); if (prior && (prior.nativeRef !== p.nativeRef || prior.cwd !== cwd || !this.sameOptions(prior.options, p.options))) throw fail("PROVIDER_INPUT_INVALID", "resume-run 与已有 Session 身份冲突"); const s: Session = prior ?? { id: c.sessionId, cwd, options: p.options, nativeRef: p.nativeRef }; this.sessions.set(c.sessionId, s); yield* this.turn(s, c, p.text, p.images); }
  private async *send(c: RunnerCommandRecord, input: string) { const p = parseCodexSendInput(input); let s = this.sessions.get(c.sessionId); if (!s && p.cwd && p.options && p.nativeRef) { s = { id: c.sessionId, cwd: this.cwd(p.cwd), options: p.options, nativeRef: p.nativeRef }; this.sessions.set(c.sessionId, s); } if (!s) throw fail("PROVIDER_SESSION_NOT_FOUND", "Codex session 不存在"); if (p.nativeRef) { const cwd = this.cwd(p.cwd!); if (p.nativeRef !== s.nativeRef || cwd !== s.cwd || !this.sameOptions(p.options!, s.options)) throw fail("PROVIDER_INPUT_INVALID", "恢复字段与 Session 冲突"); } yield* this.turn(s, c, p.text, p.images); }
  private async *configure(c: RunnerCommandRecord, op: string, mutate: (s: Session) => void): AsyncIterable<Event> { const s = this.sessions.get(c.sessionId); if (!s) throw fail("PROVIDER_SESSION_NOT_FOUND", "Codex session 不存在"); if (s.turn || s.operation) throw fail("PROVIDER_SESSION_BUSY", "Codex session 正在执行"); s.operation = op; try { yield this.event(c, "started", s.nativeRef ? { nativeRef: s.nativeRef } : {}); mutate(s); if (op === "new-session") yield this.event(c, "session-updated", { payload: JSON.stringify({ nativeRef: null }) }); yield this.event(c, "completed"); } finally { s.operation = undefined; } }
  private async *interrupt(c: RunnerCommandRecord): AsyncIterable<Event> { const s = this.sessions.get(c.sessionId), t = s?.turn; if (!t || t.command.runId !== c.runId || t.terminal) throw fail("PROVIDER_RUN_NOT_ACTIVE", "目标 run 不在执行"); if (t.interrupting) throw fail("PROVIDER_SESSION_BUSY", "Codex interrupt 已在处理"); t.interrupting = true; yield this.event(c, "started", s!.nativeRef ? { nativeRef: s!.nativeRef } : {}); t.interrupted = true; if (!this.signal(t, "SIGINT")) { t.interrupted = false; t.interrupting = false; throw fail("PROVIDER_UNAVAILABLE", "Codex interrupt 失败"); } const exited = await Promise.race([t.proc!.exited.then(() => true), Bun.sleep(this.options.interruptGraceMs).then(() => false)]); if (!exited) { this.signal(t, "SIGKILL"); await t.proc!.exited.catch(() => -1); } yield this.event(c, "completed"); }
  private materialize(images: CodexImage[]): { dir?: string; files: string[] } { if (!images.length) return { files: [] }; if (!this.options.dataRoot) throw fail("PROVIDER_INPUT_INVALID", "图片需要 Runner dataRoot"); const root = join(this.options.dataRoot, "runner", "tmp"); mkdirSync(root, { recursive: true, mode: 0o700 }); chmodSync(root, 0o700); const dir = mkdtempSync(join(root, "codex-")); chmodSync(dir, 0o700); const files = images.map((im, i) => { const ext = im.mediaType === "image/jpeg" ? "jpg" : im.mediaType.split("/")[1]!.replace(/[^A-Za-z0-9]/g, "") || "img"; const file = join(dir, `${i}.${ext}`); writeFileSync(file, Buffer.from(readRunnerAttachment(this.options.dataRoot!, im.blob), "base64"), { mode: 0o600 }); return file; }); return { dir, files }; }
  private async *turn(s: Session, c: RunnerCommandRecord, prompt: string, images: CodexImage[]): AsyncIterable<Event> {
    if (s.turn || s.operation) throw fail("PROVIDER_SESSION_BUSY", "Codex session 正在执行"); const q = new Queue(), t: Turn = { command: c, queue: q, terminal: false, interrupted: false, interrupting: false, timedOut: false, started: false, stderrTail: "", stderrEmitted: false, lastActivityAt: Date.now(), snapshots: new Map() }; s.turn = t;
    try { const material = this.materialize(images); t.temp = material.dir; const env = { ...this.env }; if (s.options.home.kind === "path") env.CODEX_HOME = s.options.home.path; else delete env.CODEX_HOME; let proc: Bun.Subprocess; try { proc = Bun.spawn(buildCodexArgs(this.command, s.options, prompt, material.files, s.nativeRef), { cwd: s.cwd, env, stdin: "ignore", stdout: "pipe", stderr: "pipe", detached: true }); } catch { throw fail("PROVIDER_UNAVAILABLE", "无法启动 Codex CLI"); } t.proc = proc; this.armWatchdog(t); t.outputDone = this.stdout(s, t); t.stderrDone = this.stderr(t); void proc.exited.then(async (code) => { await Promise.allSettled([t.outputDone, t.stderrDone]); this.exited(s, t, code); }); yield* q.iterate(); }
    finally { clearInterval(t.watchdog); if (t.proc) { const exited = await Promise.race([t.proc.exited.then(() => true), Bun.sleep(this.options.processExitGraceMs).then(() => false)]); if (!exited) { this.signal(t, "SIGKILL"); await t.proc.exited.catch(() => -1); } } if (s.turn === t) s.turn = undefined; this.cleanup(t); }
  }
  private cleanup(t: Turn) { if (t.temp) { try { rmSync(t.temp, { recursive: true, force: true }); } catch {} t.temp = undefined; } }
  private async stdout(s: Session, t: Turn) { const reader = (t.proc!.stdout as ReadableStream<Uint8Array>).getReader(), decoder = new TextDecoder("utf-8", { fatal: true }); let buffer = "", bad = 0; try { while (true) { const n = await reader.read(); if (n.done) break; this.touch(t); buffer += decoder.decode(n.value, { stream: true }); if (Buffer.byteLength(buffer) > this.options.maxStdoutBufferBytes) throw fail("PROVIDER_PROTOCOL_ERROR", "Codex stdout 半行超过上限"); let at; while ((at = buffer.indexOf("\n")) >= 0) { const line = buffer.slice(0, at); buffer = buffer.slice(at + 1); if (!line.trim()) continue; try { this.frame(s, t, JSON.parse(line)); bad = 0; } catch (e) { if (e instanceof SyntaxError) { this.metrics.invalidLines++; if (++bad >= this.options.maxInvalidLines) throw fail("PROVIDER_PROTOCOL_ERROR", "Codex 连续输出非法 JSON"); } else throw e; } } } buffer += decoder.decode(); if (buffer.trim()) { try { this.frame(s, t, JSON.parse(buffer)); } catch (e) { if (e instanceof SyntaxError) throw fail("PROVIDER_PROTOCOL_ERROR", "Codex EOF 留下非法半行"); throw e; } } } catch (e) { t.failure = { reason: t.interrupted ? "user_interrupt" : "provider_protocol_error", message: e instanceof Error ? e.message : "stream parse error" }; this.signal(t, "SIGKILL"); } }
  private async stderr(t: Turn) { try { const reader = (t.proc!.stderr as ReadableStream<Uint8Array>).getReader(), decoder = new TextDecoder(); while (true) { const n = await reader.read(); if (n.done) break; this.touch(t); t.stderrTail = (t.stderrTail + decoder.decode(n.value, { stream: true })).slice(-this.options.stderrRingBytes); } t.stderrTail = (t.stderrTail + decoder.decode()).slice(-this.options.stderrRingBytes); } catch { this.metrics.droppedFrames++; this.logDrop(t, "stderr-read-error"); } }
  private frame(s: Session, t: Turn, raw: unknown) { if (t.terminal || !plain(raw) || typeof raw.type !== "string") { this.metrics.droppedFrames++; this.logDrop(t, "invalid-frame"); return; } const c = t.command;
    if (!t.started) { t.started = true; t.queue.push(this.event(c, "started", s.nativeRef ? { nativeRef: s.nativeRef } : {})); }
    if (raw.type === "turn.started") return;
    if (raw.type === "thread.started") { const id = typeof raw.thread_id === "string" ? raw.thread_id : plain(raw.thread) && typeof raw.thread.id === "string" ? raw.thread.id : ""; if (!nativeRefPattern.test(id) || (s.nativeRef && s.nativeRef !== id)) { t.failure = { reason: "provider_protocol_error", message: !nativeRefPattern.test(id) ? "Codex thread.started nativeRef 非 UUID" : "Codex nativeRef 漂移" }; this.signal(t, "SIGKILL"); return; } s.nativeRef = id; t.queue.push(this.event(c, "session-updated", { nativeRef: id, payload: JSON.stringify({ nativeRef: id }) })); return; }
    if ((raw.type === "item.started" || raw.type === "item.updated" || raw.type === "item.completed") && plain(raw.item)) { this.item(t, raw.type, raw.item); return; }
    if (raw.type === "turn.completed") { const u = plain(raw.usage) ? raw.usage : plain(raw.turn) && plain(raw.turn.usage) ? raw.turn.usage : {}; t.queue.push(this.event(c, "usage", { payload: JSON.stringify({ inputTokens: token(u.input_tokens), cachedInputTokens: token(u.cached_input_tokens ?? u.cache_read_input_tokens), outputTokens: token(u.output_tokens), reasoningOutputTokens: token(u.reasoning_output_tokens), contextTokens: token(u.input_tokens) }) }, "best-effort")); this.flushStderr(t); return t.interrupted ? this.terminal(t, "interrupted", "user_interrupt") : t.timedOut ? this.terminal(t, "failed", "provider_no_progress") : this.terminal(t, "completed"); }
    if (raw.type === "turn.failed") { this.flushStderr(t); t.queue.push(this.event(c, "provider-notice", { payload: JSON.stringify({ category: "api_error", error: raw.error ?? null }) }, "best-effort")); return t.interrupted ? this.terminal(t, "interrupted", "user_interrupt") : this.terminal(t, "failed", "provider_result_error"); }
    if (raw.type === "error") { t.queue.push(this.event(c, "provider-notice", { payload: JSON.stringify({ category: "api_error", message: typeof raw.message === "string" ? raw.message : "Codex error" }) }, "best-effort")); return; }
    this.metrics.droppedFrames++; this.logDrop(t, `unknown-type:${raw.type}`);
  }
  private item(t: Turn, frameType: string, item: Record<string, unknown>): void {
    const c = t.command, kind = String(item.type || ""), id = typeof item.id === "string" ? item.id : "";
    if (kind === "agent_message" && typeof item.text === "string") {
      if (frameType === "item.started") { if (id) t.snapshots.set(id, item.text); return; }
      if (frameType === "item.updated") { const prior = id ? t.snapshots.get(id) : undefined; if (prior !== undefined && item.text.startsWith(prior)) { const suffix = item.text.slice(prior.length); if (suffix) t.queue.push(this.event(c, "delta", { payload: JSON.stringify({ role: "assistant", text: suffix }) }, "best-effort")); } else { this.metrics.droppedFrames++; this.logDrop(t, "non-prefix-agent-snapshot"); } if (id) t.snapshots.set(id, item.text); return; }
      if (id) t.snapshots.delete(id); t.queue.push(this.event(c, "message-completed", { payload: JSON.stringify({ role: "assistant", text: item.text }) })); return;
    }
    if (frameType !== "item.completed") return;
    if (kind === "error") { this.metrics.notices++; t.queue.push(this.event(c, "provider-notice", { payload: JSON.stringify({ category: "provider_warning", message: typeof item.message === "string" ? item.message : "Codex item error" }) }, "best-effort")); return; }
    const roles: Record<string, string> = { reasoning: "thinking", command_execution: "tool", file_change: "tool", mcp_tool_call: "tool", web_search: "tool", todo_list: "plan", plan: "plan", plan_update: "plan" };
    const role = roles[kind]; if (role) {
      const normalized = kind === "mcp_tool_call" ? normalizeCodexContentImages(this.options.dataRoot, c.sessionId, item) : item;
      t.queue.push(this.event(c, "message-completed", { payload: JSON.stringify({ role, type: kind, item: normalized }) })); return;
    }
    this.metrics.droppedFrames++; this.logDrop(t, `unknown-item:${kind}`);
  }
  private flushStderr(t: Turn): void { if (!t.stderrTail || t.stderrEmitted || t.terminal) return; t.stderrEmitted = true; this.metrics.notices++;
    // 锁冲突要排在最前：它的 stderr 里带 "thread/resume failed"，被裸 `resume` 一匹配就成了
    // resume_not_found，而两者的处置完全相反（找不到→新开会话；被占用→先释放持有者）。
    const category = /already has an active writer|thread-store conflict/i.test(t.stderrTail) ? "lock_conflict" : /auth|login|credential|token expired/i.test(t.stderrTail) ? "auth_expired" : /rate.?limit|429/i.test(t.stderrTail) ? "rate_limited" : /thread.*not found|rollout.*not found|resume.*not found/i.test(t.stderrTail) ? "resume_not_found" : "stderr"; t.queue.push(this.event(t.command, "provider-notice", { payload: JSON.stringify({ category, tail: t.stderrTail }) }, "best-effort")); }
  private terminal(t: Turn, type: "completed" | "failed" | "interrupted", reason?: RunnerReasonCode, detail?: Record<string, unknown>) { if (t.terminal) return; if (detail?.message) { this.metrics.notices++; t.queue.push(this.event(t.command, "provider-notice", { payload: JSON.stringify({ category: "api_error", message: detail.message }) }, "best-effort")); } t.terminal = true; t.queue.push(this.event(t.command, type, { ...(reason ? { reason } : {}), ...(typeof detail?.exitCode === "number" ? { exitCode: detail.exitCode } : {}) })); t.queue.end(); }
  private exited(s: Session, t: Turn, code: number) { if (s.turn !== t || t.terminal) return; this.flushStderr(t); if (t.failure) return this.terminal(t, t.interrupted ? "interrupted" : "failed", t.interrupted ? "user_interrupt" : t.failure.reason, { exitCode: code, message: t.failure.message }); this.terminal(t, t.interrupted ? "interrupted" : "failed", t.interrupted ? "user_interrupt" : t.timedOut ? "provider_no_progress" : "provider_exit", { exitCode: code }); }
  private sameOptions(a: CodexOptions, b: CodexOptions): boolean { return JSON.stringify(a) === JSON.stringify(b); }
  private touch(t: Turn): void { t.lastActivityAt = Date.now(); }
  private signal(t: Turn, signal: NodeJS.Signals): boolean { const pid = t.proc?.pid; if (!pid) return false; try { process.kill(-pid, signal); return true; } catch { try { t.proc!.kill(signal); return true; } catch { return false; } } }
  private armWatchdog(t: Turn): void { if (this.options.idleTimeoutMs <= 0) return; const interval = Math.max(10, Math.min(60_000, Math.floor(this.options.idleTimeoutMs / 4))); t.watchdog = setInterval(() => { if (t.terminal || t.timedOut || Date.now() - t.lastActivityAt <= this.options.idleTimeoutMs) return; t.timedOut = true; this.signal(t, "SIGTERM"); setTimeout(() => { if (!t.terminal) this.signal(t, "SIGKILL"); }, this.options.interruptGraceMs); }, interval); }
  private logDrop(t: Turn, reason: string): void { emitCoreLog({ event: "codex-frame-dropped", moduleType: "provider", moduleId: this.id, operation: "decode-frame", runId: t.command.runId, sessionId: t.command.sessionId, eventId: t.command.commandId, errorClass: "PROVIDER_FRAME_DROPPED", msg: `reason=${reason} total=${this.metrics.droppedFrames}` }); }
}
