import { chmodSync, closeSync, constants, cpSync, existsSync, fstatSync, linkSync, lstatSync, mkdirSync, openSync, readFileSync, readdirSync, renameSync, rmSync, statfsSync, statSync, unlinkSync, writeFileSync } from "fs";
import { fsyncSync } from "../src/fs-durable.ts";
import { createHash } from "crypto";
import { dirname, join, relative, resolve } from "path";
import { inventoryMigrationCopy, migrationSourceAggregate } from "./data-migration-inventory.ts";
import { SessionRepository } from "../src/sessions/repository.ts";

export const STAGE6_SESSION_PLAN = { id:"stage6-kernel-sessions-v1",schemaFrom:1,schemaTo:1,kind:"session-store-copy-forward" as const };
/** Kept only so old clean fixtures can exercise the transaction shell; it is not a Phase 6 acceptance plan. */
export const STAGE6_NOOP_PLAN = { id:"stage6-layout-noop-v1",schemaFrom:1,schemaTo:1,kind:"versioned-noop" as const };
type Fault="after-backup"|"after-staging"|"after-target"|"before-commit"|"after-schema"|"after-commit"|"rollback-after-revoke"|"rollback-after-staging"|"rollback-mid-primary-switch"|"rollback-mid-schema"|"rollback-mid-marker";
type Options={apply?:boolean;rollback?:boolean;planId?:string;repairInput?:string;faultAt?:Fault};
type MigrationLease={pid:number;token:string;at:string};
type RepairInput={schemaVersion:1;planId:typeof STAGE6_SESSION_PLAN.id;sourceAggregateSha256:string;classification:"preserve-as-archived-orphan";repairs:{sessionId:string;taskRef:string}[]};
export const MIGRATION_LEASE_STALE_MS=5*60_000;

function fsyncDir(path:string){const fd=openSync(path,"r");try{fsyncSync(fd);}finally{closeSync(fd);}}
function atomic(path:string,value:unknown){mkdirSync(dirname(path),{recursive:true,mode:0o700});chmodSync(dirname(path),0o700);const tmp=`${path}.${process.pid}.${crypto.randomUUID()}.tmp`,raw=JSON.stringify(value,null,2)+"\n";writeFileSync(tmp,raw,{mode:0o600});const fd=openSync(tmp,"r");try{fsyncSync(fd);}finally{closeSync(fd);}renameSync(tmp,path);fsyncDir(dirname(path));}
function dataFiles(root:string){const out:string[]=[];function walk(dir:string){for(const name of readdirSync(dir)){if(name==="secrets"||name==="backups"||name==="migrations")continue;const path=join(dir,name),st=lstatSync(path);if(st.isSymbolicLink())throw new Error("MIGRATION_SYMLINK_REJECTED");if(st.isDirectory())walk(path);else if(st.isFile()&&name!==".ownward-connector-drill-copy")out.push(path);}}walk(root);return out.sort();}
function assertSanitizedCopy(root:string){const marker=join(root,".ownward-connector-drill-copy");if(!existsSync(marker)||lstatSync(marker).isSymbolicLink()||!lstatSync(marker).isFile())throw new Error("MIGRATION_SANITIZED_COPY_REQUIRED");if(existsSync(join(root,"secrets")))throw new Error("MIGRATION_SECRETS_PRESENT");const walk=(dir:string)=>{for(const name of readdirSync(dir)){const path=join(dir,name),st=lstatSync(path);if(st.isSymbolicLink())throw new Error("MIGRATION_SYMLINK_REJECTED");if(st.isDirectory())walk(path);}};walk(root);}
function fingerprint(root:string,paths=dataFiles(root)){const h=createHash("sha256");let bytes=0;for(const path of paths){const raw=readFileSync(path);bytes+=raw.length;h.update(relative(root,path));h.update("\0");h.update(raw);}return{files:paths.length,bytes,sha256:h.digest("hex")};}
function privateCopy(root:string,target:string,paths:string[]){mkdirSync(target,{recursive:true,mode:0o700});chmodSync(target,0o700);const dirs=new Set<string>([target]);for(const path of paths){const rel=relative(root,path),to=join(target,rel);mkdirSync(dirname(to),{recursive:true,mode:0o700});chmodSync(dirname(to),0o700);dirs.add(dirname(to));cpSync(path,to);chmodSync(to,0o600);const fd=openSync(to,"r");try{fsyncSync(fd);}finally{closeSync(fd);}}for(const dir of [...dirs].sort((a,b)=>b.length-a.length))fsyncDir(dir);}
function fail(at:Fault|undefined,want:Fault){if(at===want)throw Object.assign(new Error(`injected ${want}`),{code:"MIGRATION_FAULT_INJECTED"});}
export function canRecoverMigrationLease(lease:MigrationLease,now=Date.now(),alive=(pid:number)=>{try{process.kill(pid,0);return true;}catch(error:any){return error?.code==="EPERM";}}){const at=Date.parse(lease.at);return Number.isInteger(lease.pid)&&lease.pid>0&&typeof lease.token==="string"&&lease.token.length>0&&Number.isFinite(at)&&now-at>=MIGRATION_LEASE_STALE_MS&&!alive(lease.pid);}
export function claimStaleMigrationLease(path:string,recovery:string,expectedToken:string){try{linkSync(path,recovery);}catch{return false;}try{const pinned=JSON.parse(readFileSync(recovery,"utf8")) as MigrationLease;if(pinned.token!==expectedToken)return false;const current=statSync(path),claimed=statSync(recovery);if(current.dev!==claimed.dev||current.ino!==claimed.ino)return false;unlinkSync(path);return true;}catch{return false;}finally{try{rmSync(recovery,{force:true});}catch{}}}
function withLease<T>(root:string,fn:()=>T):T{const dir=join(root,"migrations"),lease=join(dir,".global-lease"),token=crypto.randomUUID(),recovery=`${lease}.recovery.${process.pid}.${token}`;mkdirSync(dir,{recursive:true,mode:0o700});try{const acquire=()=>writeFileSync(lease,JSON.stringify({pid:process.pid,token,at:new Date().toISOString()}),{flag:"wx",mode:0o600});try{acquire();}catch(error:any){if(error?.code!=="EEXIST")throw error;let stale:MigrationLease|null=null;try{stale=JSON.parse(readFileSync(lease,"utf8"));}catch{}if(!stale||!canRecoverMigrationLease(stale)||!claimStaleMigrationLease(lease,recovery,stale.token))throw Object.assign(new Error("MIGRATION_LEASE_BUSY"),{code:"MIGRATION_LEASE_BUSY"});try{acquire();}catch{throw Object.assign(new Error("MIGRATION_LEASE_BUSY"),{code:"MIGRATION_LEASE_BUSY"});}}return fn();}finally{try{const current=JSON.parse(readFileSync(lease,"utf8"));if(current.token===token)rmSync(lease,{force:true});}catch{}try{rmSync(recovery,{force:true});}catch{}}}

function danglingSessionLinks(root:string){const tasks=JSON.parse(readFileSync(join(root,"tasks.json"),"utf8")),store=JSON.parse(readFileSync(join(root,"sessions.json"),"utf8")),ids=new Set((Array.isArray(tasks)?tasks:[]).map((x:any)=>x?.id).filter(Boolean)),sessions=Array.isArray(store?.sessions)?store.sessions:[];return sessions.flatMap((session:any)=>(Array.isArray(session?.taskIds)?session.taskIds:[]).filter((taskRef:any)=>typeof taskRef==="string"&&!ids.has(taskRef)).map((taskRef:string)=>({session,sessionId:session.id,taskRef})));}
function readRepairInput(root:string,pathInput:string|undefined):RepairInput{
  if(existsSync(join(root,"kernel","sessions.json"))&&!existsSync(join(root,"backups",STAGE6_SESSION_PLAN.id)))throw new Error("MIGRATION_PRIMARY_PREEXISTING");
  if(!pathInput)throw new Error("MIGRATION_REPAIR_INPUT_REQUIRED");const path=resolve(pathInput),rootPrefix=resolve(root)+"/";if(path===resolve(root)||path.startsWith(rootPrefix))throw new Error("MIGRATION_REPAIR_INPUT_MUST_BE_EXTERNAL");
  let fd=-1,raw:any;try{fd=openSync(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const st=fstatSync(fd),uid=typeof process.getuid==="function"?process.getuid():st.uid;if(!st.isFile()||st.uid!==uid||st.nlink!==1||(st.mode&0o777)!==0o600)throw new Error("MIGRATION_REPAIR_INPUT_NOT_PRIVATE");raw=JSON.parse(readFileSync(fd,"utf8"));}catch(error:any){if(String(error?.message)==="MIGRATION_REPAIR_INPUT_NOT_PRIVATE"||error?.code==="ELOOP")throw new Error("MIGRATION_REPAIR_INPUT_NOT_PRIVATE");throw new Error("MIGRATION_REPAIR_INPUT_INVALID");}finally{if(fd>=0)closeSync(fd);}
  const exact=JSON.stringify(Object.keys(raw||{}).sort())===JSON.stringify(["classification","planId","repairs","schemaVersion","sourceAggregateSha256"]);if(!exact||raw.schemaVersion!==1||raw.planId!==STAGE6_SESSION_PLAN.id||raw.classification!=="preserve-as-archived-orphan"||!/^[0-9a-f]{64}$/.test(raw.sourceAggregateSha256)||!Array.isArray(raw.repairs)||raw.repairs.some((x:any)=>!x||JSON.stringify(Object.keys(x).sort())!==JSON.stringify(["sessionId","taskRef"])||typeof x.sessionId!=="string"||!x.sessionId||typeof x.taskRef!=="string"||!x.taskRef))throw new Error("MIGRATION_REPAIR_INPUT_INVALID");if(raw.sourceAggregateSha256!==migrationSourceAggregate(root))throw new Error("MIGRATION_REPAIR_SOURCE_MISMATCH");return raw;
}
export function writeStage6RepairInput(rootInput:string,outputInput:string){const root=resolve(rootInput),output=resolve(outputInput);if(existsSync(join(root,"kernel","sessions.json")))throw new Error("MIGRATION_PRIMARY_PREEXISTING");const inventory=inventoryMigrationCopy(root),links=danglingSessionLinks(root);if(inventory.keyRefs.blocking!==links.length||!links.length)throw new Error("MIGRATION_REPAIR_UNKNOWN_DANGLING");const grouped=new Map<string,any[]>();for(const link of links)grouped.set(link.sessionId,[...(grouped.get(link.sessionId)??[]),link]);for(const rows of grouped.values()){const taskIds=rows[0].session.taskIds;if(!Array.isArray(taskIds)||taskIds.length!==rows.length||!rows[0].session.nativeRef)throw new Error("MIGRATION_REPAIR_SHAPE_UNSUPPORTED");}if(existsSync(output))throw new Error("MIGRATION_REPAIR_OUTPUT_EXISTS");const parent=dirname(output);mkdirSync(parent,{recursive:true,mode:0o700});const pst=statSync(parent),uid=typeof process.getuid==="function"?process.getuid():pst.uid,sticky=(pst.mode&0o1000)!==0;if(!pst.isDirectory()||(pst.uid!==uid&&pst.uid!==0)||((pst.mode&0o022)!==0&&!sticky))throw new Error("MIGRATION_REPAIR_OUTPUT_PARENT_UNSAFE");writeFileSync(output,JSON.stringify({schemaVersion:1,planId:STAGE6_SESSION_PLAN.id,sourceAggregateSha256:migrationSourceAggregate(root),classification:"preserve-as-archived-orphan",repairs:links.map(({sessionId,taskRef})=>({sessionId,taskRef}))},null,2)+"\n",{flag:"wx",mode:0o600});return{written:true,repairs:links.length};}
function migratedSessions(root:string,repair:RepairInput){const store=JSON.parse(readFileSync(join(root,"sessions.json"),"utf8")),links=danglingSessionLinks(root),wanted=new Set(repair.repairs.map(x=>`${x.sessionId}\0${x.taskRef}`)),actual=new Set(links.map(x=>`${x.sessionId}\0${x.taskRef}`));if(wanted.size!==repair.repairs.length||wanted.size!==actual.size||[...wanted].some(x=>!actual.has(x)))throw new Error("MIGRATION_REPAIR_SET_MISMATCH");const bySession=new Map<string,string[]>();for(const row of repair.repairs)bySession.set(row.sessionId,[...(bySession.get(row.sessionId)??[]),row.taskRef]);const sessions=store.sessions.map((session:any)=>{const refs=bySession.get(session.id);if(!refs)return session;if(session.taskIds.length!==refs.length||!session.nativeRef)throw new Error("MIGRATION_REPAIR_SHAPE_UNSUPPORTED");return{...session,taskIds:[],archive:{state:"orphaned-task-link",originalTaskRefs:[...refs].sort(),migrationId:STAGE6_SESSION_PLAN.id,reason:"task-record-missing",sourceAggregateSha256:repair.sourceAggregateSha256}};});return{...store,schemaVersion:1,sessions};}
function assertSpace(root:string,beforeBytes:number,targetBytes:number){const fs=statfsSync(root),available=Number(fs.bavail)*Number(fs.bsize),required=Math.ceil((beforeBytes+targetBytes)*1.2);if(!Number.isFinite(available)||available<required)throw new Error("MIGRATION_DISK_SPACE_INSUFFICIENT");return{available,required};}
const digestFile=(path:string)=>createHash("sha256").update(readFileSync(path)).digest("hex");
const semanticPaths=(root:string)=>["schema.json","tasks.json","sessions.json","pinned-sessions.json","actions.json"].map(name=>join(root,name)).filter(existsSync);
const semanticDigest=(root:string)=>fingerprint(root,semanticPaths(root)).sha256;
function postSurface(inventory:ReturnType<typeof inventoryMigrationCopy>){return{cardinality:inventory.cardinality,canonicalSessionStore:inventory.canonicalSessionStore,refAggregateSha256:inventory.keyRefs.aggregateSha256,archived:inventory.keyRefs.archived,blocking:inventory.keyRefs.blocking};}
function readCommit(path:string,plan=STAGE6_SESSION_PLAN){let marker:any;try{marker=JSON.parse(readFileSync(path,"utf8"));}catch{throw new Error("MIGRATION_COMMIT_MARKER_INVALID");}const keys=["planId","post","postInputsSha256","postSchema","preSchema","schemaFrom","schemaTo","sourceAggregateSha256","targetSha256","validated"];if(JSON.stringify(Object.keys(marker||{}).sort())!==JSON.stringify(keys)||marker.planId!==plan.id||marker.schemaFrom!==plan.schemaFrom||marker.schemaTo!==plan.schemaTo||marker.validated!==true||!marker.preSchema||!marker.postSchema||![marker.sourceAggregateSha256,marker.targetSha256,marker.postInputsSha256].every((x:any)=>typeof x==="string"&&/^[0-9a-f]{64}$/.test(x)))throw new Error("MIGRATION_COMMIT_MARKER_INVALID");return marker;}
function readBackupManifest(backup:string,planId:string){let manifest:any;try{manifest=JSON.parse(readFileSync(join(backup,"backup-manifest.json"),"utf8"));}catch{throw new Error("MIGRATION_BACKUP_MANIFEST_INVALID");}if(JSON.stringify(Object.keys(manifest||{}).sort())!==JSON.stringify(["before","planId","sourceAggregateSha256"])||manifest.planId!==planId||!manifest.before||!Number.isSafeInteger(manifest.before.files)||!Number.isSafeInteger(manifest.before.bytes)||!/^[0-9a-f]{64}$/.test(manifest.before.sha256)||!/^[0-9a-f]{64}$/.test(manifest.sourceAggregateSha256))throw new Error("MIGRATION_BACKUP_MANIFEST_INVALID");const files=dataFiles(backup).filter(path=>relative(backup,path)!=="backup-manifest.json"),actual=fingerprint(backup,files);if(JSON.stringify(actual)!==JSON.stringify(manifest.before))throw new Error("MIGRATION_BACKUP_VALIDATION_FAILED");return manifest;}

export function runStage6Migration(rootInput:string,opts:Options={}){const root=resolve(rootInput),plan=opts.planId===STAGE6_NOOP_PLAN.id?STAGE6_NOOP_PLAN:STAGE6_SESSION_PLAN;if(opts.planId&&opts.planId!==plan.id)throw new Error("MIGRATION_PLAN_ID_MISMATCH");assertSanitizedCopy(root);if(!opts.apply&&!opts.rollback){const inventory=inventoryMigrationCopy(root);return{mode:"dry-run",plan,applyEligible:inventory.applyEligible,repairRequired:plan.id===STAGE6_SESSION_PLAN.id&&!inventory.applyEligible,cardinality:inventory.cardinality,keyRefs:inventory.keyRefs};}
  return withLease(root,()=>{const migrationRoot=join(root,"migrations",plan.id),backup=join(root,"backups",plan.id),commit=join(migrationRoot,"commit.json");
    if(opts.rollback){if(!opts.apply)throw new Error("MIGRATION_ROLLBACK_REQUIRES_EXPLICIT_APPLY");if(!existsSync(backup))throw new Error("MIGRATION_BACKUP_MISSING");readBackupManifest(backup,plan.id);const journal=join(migrationRoot,"rollback.json"),hidden=join(migrationRoot,"rollback-primary.json"),target=join(root,"kernel","sessions.json");let prior:any=null;try{prior=JSON.parse(readFileSync(journal,"utf8"));}catch{}const marker=existsSync(commit)?readCommit(commit,plan as typeof STAGE6_SESSION_PLAN):prior?.marker;if(!marker)throw new Error("MIGRATION_COMMIT_MARKER_INVALID");if(existsSync(target)&&digestFile(target)!==marker.targetSha256)throw new Error("MIGRATION_ROLLBACK_TARGET_DRIFT");const currentSchema=JSON.parse(readFileSync(join(root,"schema.json"),"utf8"));if(JSON.stringify(currentSchema)!==JSON.stringify(marker.postSchema)&&JSON.stringify(currentSchema)!==JSON.stringify(marker.preSchema))throw new Error("MIGRATION_ROLLBACK_SCHEMA_DRIFT");atomic(journal,{planId:plan.id,phase:"prepared",marker});if(existsSync(target)&&!existsSync(hidden)){renameSync(target,hidden);fsyncDir(dirname(target));fsyncDir(migrationRoot);}fail(opts.faultAt,"rollback-mid-primary-switch");fail(opts.faultAt,"rollback-after-revoke");atomic(journal,{planId:plan.id,phase:"primary-hidden",marker});atomic(join(root,"schema.json"),marker.preSchema);fail(opts.faultAt,"rollback-mid-schema");fail(opts.faultAt,"rollback-after-staging");atomic(journal,{planId:plan.id,phase:"schema-restored",marker});if(existsSync(commit)){rmSync(commit,{force:true});fsyncDir(migrationRoot);}fail(opts.faultAt,"rollback-mid-marker");rmSync(hidden,{force:true});atomic(journal,{planId:plan.id,phase:"complete",rolledBack:true,marker});return{mode:"rollback",plan,restored:true};}
    let schema=JSON.parse(readFileSync(join(root,"schema.json"),"utf8"));if(schema.version!==plan.schemaFrom)throw new Error("MIGRATION_SCHEMA_FROM_MISMATCH");if(existsSync(commit)){const marker=readCommit(commit,plan as typeof STAGE6_SESSION_PLAN),manifest=readBackupManifest(backup,plan.id),target=join(root,"kernel","sessions.json"),stagedTarget=join(migrationRoot,"staging","kernel","sessions.json");if(marker.sourceAggregateSha256!==manifest.sourceAggregateSha256||JSON.stringify(schema)!==JSON.stringify(marker.postSchema)||semanticDigest(root)!==marker.postInputsSha256)throw new Error("MIGRATION_COMMITTED_STATE_INVALID");if(plan.id===STAGE6_SESSION_PLAN.id&&!existsSync(target)){if(!existsSync(stagedTarget)||digestFile(stagedTarget)!==marker.targetSha256)throw new Error("MIGRATION_COMMITTED_STATE_INVALID");mkdirSync(dirname(target),{recursive:true,mode:0o700});renameSync(stagedTarget,target);fsyncDir(dirname(target));}const inventory=inventoryMigrationCopy(root),targetInvalid=plan.id===STAGE6_SESSION_PLAN.id&&digestFile(target)!==marker.targetSha256;if(targetInvalid||JSON.stringify(postSurface(inventory))!==JSON.stringify(marker.post)||(plan.id===STAGE6_SESSION_PLAN.id&&(!inventory.applyEligible||inventory.canonicalSessionStore!=="kernel")))throw new Error("MIGRATION_COMMITTED_STATE_INVALID");return{mode:"apply",plan,applyEligible:true,cardinality:inventory.cardinality,keyRefs:inventory.keyRefs,idempotent:true,committed:true};}if(Array.isArray(schema.applied)&&schema.applied.includes(plan.id)){const saved=join(backup,"schema.json");if(!existsSync(saved))throw new Error("MIGRATION_SCHEMA_RECOVERY_BACKUP_MISSING");const tmp=join(root,`.schema-recover.${crypto.randomUUID()}`);cpSync(saved,tmp);renameSync(tmp,join(root,"schema.json"));fsyncDir(root);schema=JSON.parse(readFileSync(join(root,"schema.json"),"utf8"));}
    const preSourceAggregate=migrationSourceAggregate(root),beforeInventory=inventoryMigrationCopy(root),repair=plan.id===STAGE6_SESSION_PLAN.id?readRepairInput(root,opts.repairInput):null;if(plan.id===STAGE6_NOOP_PLAN.id&&!beforeInventory.applyEligible)throw new Error("MIGRATION_APPLY_BLOCKED_BY_REFS");const targetValue=repair?migratedSessions(root,repair):null,targetRaw=targetValue?Buffer.from(JSON.stringify(targetValue,null,2)+"\n"):Buffer.alloc(0),source=dataFiles(root).filter(path=>relative(root,path)!=="kernel/sessions.json"),before=fingerprint(root,source),space=assertSpace(root,before.bytes,targetRaw.length);
    if(!existsSync(backup)){const backupStaging=`${backup}.staging.${crypto.randomUUID()}`;privateCopy(root,backupStaging,source);atomic(join(backupStaging,"backup-manifest.json"),{planId:plan.id,before,sourceAggregateSha256:preSourceAggregate});const stagedFiles=dataFiles(backupStaging).filter(path=>relative(backupStaging,path)!=="backup-manifest.json"),staged=fingerprint(backupStaging,stagedFiles);if(staged.sha256!==before.sha256||staged.files!==before.files){rmSync(backupStaging,{recursive:true,force:true});throw new Error("MIGRATION_BACKUP_VALIDATION_FAILED");}mkdirSync(dirname(backup),{recursive:true,mode:0o700});renameSync(backupStaging,backup);fsyncDir(dirname(backup));}else{const manifest=readBackupManifest(backup,plan.id);if(JSON.stringify(manifest.before)!==JSON.stringify(before)||manifest.sourceAggregateSha256!==preSourceAggregate)throw new Error("MIGRATION_BACKUP_SOURCE_DRIFT");}fail(opts.faultAt,"after-backup");
    const staging=join(migrationRoot,"staging");rmSync(staging,{recursive:true,force:true});mkdirSync(staging,{recursive:true,mode:0o700});atomic(join(staging,"plan.json"),{plan,before,space,sourceAggregateSha256:preSourceAggregate});if(targetValue)atomic(join(staging,"kernel","sessions.json"),targetValue);fail(opts.faultAt,"after-staging");if(migrationSourceAggregate(root)!==preSourceAggregate)throw new Error("MIGRATION_WRITE_STOP_PROOF_FAILED");
    let post=beforeInventory;if(targetValue){const validation=join(staging,"validation"),markerFile=join(root,".ownward-connector-drill-copy");rmSync(validation,{recursive:true,force:true});privateCopy(root,validation,[...semanticPaths(root),markerFile]);atomic(join(validation,"kernel","sessions.json"),targetValue);post=inventoryMigrationCopy(validation);if(!post.applyEligible||post.canonicalSessionStore!=="kernel"||post.cardinality.sessions!==beforeInventory.cardinality.sessions||post.cardinality.tasks!==beforeInventory.cardinality.tasks||post.cardinality.pinned!==beforeInventory.cardinality.pinned||post.cardinality.actions!==beforeInventory.cardinality.actions||post.keyRefs.archived.total!==repair!.repairs.length||new SessionRepository(validation).list().length!==post.cardinality.sessions)throw new Error("MIGRATION_POST_VALIDATION_FAILED");rmSync(validation,{recursive:true,force:true});}fail(opts.faultAt,"before-commit");const postSchema={version:plan.schemaTo,applied:[...new Set([...(schema.applied??[]),plan.id])]};atomic(join(root,"schema.json"),postSchema);fail(opts.faultAt,"after-schema");const stagedTarget=join(staging,"kernel","sessions.json"),target=join(root,"kernel","sessions.json"),targetSha256=targetValue?digestFile(stagedTarget):createHash("sha256").update("").digest("hex");atomic(commit,{planId:plan.id,schemaFrom:plan.schemaFrom,schemaTo:plan.schemaTo,preSchema:schema,postSchema,sourceAggregateSha256:preSourceAggregate,targetSha256,postInputsSha256:semanticDigest(root),post:postSurface(post),validated:true});fail(opts.faultAt,"after-commit");if(targetValue){mkdirSync(dirname(target),{recursive:true,mode:0o700});renameSync(stagedTarget,target);fsyncDir(dirname(target));}fail(opts.faultAt,"after-target");const committedInventory=inventoryMigrationCopy(root);if(JSON.stringify(postSurface(committedInventory))!==JSON.stringify(postSurface(post)))throw new Error("MIGRATION_POST_VALIDATION_FAILED");return{mode:"apply",plan,applyEligible:true,cardinality:committedInventory.cardinality,keyRefs:committedInventory.keyRefs,committed:true,idempotent:false};});}

if(import.meta.main){const args=process.argv.slice(2),value=(name:string)=>{const i=args.indexOf(name);return i>=0?args[i+1]:undefined;},source=value("--source"),plan=value("--plan-id"),repairInput=value("--repair-input"),writeRepair=value("--write-repair-input");if(!source){console.error("usage: bun scripts/data-migration-executor.ts --source <sanitized-copy> [--write-repair-input <0600-file> | --apply --plan-id stage6-kernel-sessions-v1 --repair-input <0600-file> | --apply --rollback --plan-id stage6-kernel-sessions-v1]");process.exit(2);}try{const result=writeRepair?writeStage6RepairInput(source,writeRepair):runStage6Migration(source,{apply:args.includes("--apply"),rollback:args.includes("--rollback"),planId:plan,repairInput});console.log(JSON.stringify(result,null,2));}catch(error:any){console.error(JSON.stringify({ok:false,code:String(error?.code||error?.message||"MIGRATION_FAILED")}));process.exit(1);}}
