import { describe, expect, test } from "bun:test";
import { chmodSync, existsSync, linkSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import { canRecoverMigrationLease, claimStaleMigrationLease, MIGRATION_LEASE_STALE_MS, runStage6Migration, STAGE6_NOOP_PLAN, STAGE6_SESSION_PLAN, writeStage6RepairInput } from "./data-migration-executor.ts";
import { inventoryMigrationCopy } from "./data-migration-inventory.ts";
import { SessionRepository } from "../src/sessions/repository.ts";

const roots:string[]=[];
function base(orphan=false){
  const root=mkdtempSync(join(tmpdir(),"ownward-stage6-migration-"));roots.push(root);
  writeFileSync(join(root,".ownward-connector-drill-copy"),"");
  writeFileSync(join(root,"schema.json"),JSON.stringify({version:1,applied:[]}));
  writeFileSync(join(root,"tasks.json"),JSON.stringify([{id:"task"}]));
  const stamp="2026-08-17T00:00:00.000Z",sessions=[{id:"session",providerId:"claude",nativeRef:"ref",previousRefs:[],cwd:"/repo",control:"ownward",taskIds:["task"],recoverable:true,source:"legacy",createdAt:stamp,updatedAt:stamp}];
  if(orphan)sessions.push({id:"orphan",providerId:"claude",nativeRef:"orphan-ref",previousRefs:[],cwd:"/gone",control:"external",taskIds:["missing"],recoverable:true,source:"legacy",createdAt:stamp,updatedAt:stamp});
  writeFileSync(join(root,"sessions.json"),JSON.stringify({schemaVersion:1,sessions}));
  writeFileSync(join(root,"pinned-sessions.json"),JSON.stringify([{kind:"task",ref:"task"}]));writeFileSync(join(root,"actions.json"),"[]");return root;
}
function repair(root:string){const path=join(tmpdir(),`ownward-repair-${crypto.randomUUID()}.json`);roots.push(path);expect(writeStage6RepairInput(root,path)).toEqual({written:true,repairs:1});expect(statSync(path).mode&0o077).toBe(0);return path;}
function clean(){while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true});}

describe("stage6 real Session Store migration",()=>{
  test("dry-run is non-mutating and exact private repair produces a canonical archived Session",()=>{const root=base(true);try{const source=readFileSync(join(root,"sessions.json"),"utf8"),input=repair(root);expect(runStage6Migration(root)).toMatchObject({mode:"dry-run",plan:{id:STAGE6_SESSION_PLAN.id},applyEligible:false,repairRequired:true,keyRefs:{blocking:1}});expect(existsSync(join(root,"backups"))).toBe(false);const applied=runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input});expect(applied).toMatchObject({committed:true,idempotent:false,cardinality:{tasks:1,sessions:2,pinned:1,actions:0},keyRefs:{blocking:0,archived:{total:1,valid:1}}});expect(readFileSync(join(root,"sessions.json"),"utf8")).toBe(source);const archived=new SessionRepository(root).getById("orphan")!;expect(archived).toMatchObject({nativeRef:"orphan-ref",taskIds:[],archive:{state:"orphaned-task-link",originalTaskRefs:["missing"],reason:"task-record-missing"}});expect(new SessionRepository(root).getByTaskId("missing")).toBeNull();expect(inventoryMigrationCopy(root)).toMatchObject({canonicalSessionStore:"kernel",applyEligible:true});expect(runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input})).toMatchObject({committed:true,idempotent:true});}finally{clean();}});

  test("repair input is external, 0600, source-bound and refuses unknown dangling kinds",()=>{for(const mode of["public","inside","drift","unknown"]){const root=base(true);try{let input=repair(root);if(mode==="public")chmodSync(input,0o644);if(mode==="inside"){const inside=join(root,"repair.json");writeFileSync(inside,readFileSync(input),{mode:0o600});input=inside;}if(mode==="drift")writeFileSync(join(root,"actions.json"),"[ ]");if(mode==="unknown")writeFileSync(join(root,"pinned-sessions.json"),JSON.stringify([{kind:"task",ref:"unknown"}]));if(mode==="unknown")expect(()=>writeStage6RepairInput(root,join(tmpdir(),`unknown-${crypto.randomUUID()}`))).toThrow("MIGRATION_REPAIR_UNKNOWN_DANGLING");else expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input})).toThrow(mode==="public"?"MIGRATION_REPAIR_INPUT_NOT_PRIVATE":mode==="inside"?"MIGRATION_REPAIR_INPUT_MUST_BE_EXTERNAL":"MIGRATION_REPAIR_SOURCE_MISMATCH");}finally{clean();}}});

  test("repair input rejects symlink and hard-link substitution using the opened descriptor",()=>{const root=base(true);try{const input=repair(root),symlink=join(tmpdir(),`repair-link-${crypto.randomUUID()}`),hardlink=join(tmpdir(),`repair-hard-${crypto.randomUUID()}`);roots.push(symlink,hardlink);symlinkSync(input,symlink);expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:symlink})).toThrow("MIGRATION_REPAIR_INPUT_NOT_PRIVATE");linkSync(input,hardlink);expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:hardlink})).toThrow("MIGRATION_REPAIR_INPUT_NOT_PRIVATE");}finally{clean();}});

  for(const fault of["after-backup","after-staging","after-target","before-commit","after-schema","after-commit"] as const)test(`fault ${fault} is rerunnable without a half-visible migration`,()=>{const root=base(true);try{const input=repair(root);expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input,faultAt:fault})).toThrow("injected");const hasCommit=existsSync(join(root,"migrations",STAGE6_SESSION_PLAN.id,"commit.json")),published=fault==="after-target";expect(hasCommit).toBe(fault==="after-commit"||published);expect(new SessionRepository(root).getById("orphan")?.archive!==undefined).toBe(published);expect(runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input})).toMatchObject({committed:true});expect(inventoryMigrationCopy(root)).toMatchObject({applyEligible:true,canonicalSessionStore:"kernel"});}finally{clean();}});

  test("rollback atomically hides only the plan target and preserves post-migration business writes",()=>{const root=base(true);try{const input=repair(root),before=readFileSync(join(root,"sessions.json"),"utf8");runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input});const changed=JSON.stringify([{id:"task"},{id:"later"}]);writeFileSync(join(root,"tasks.json"),changed);expect(runStage6Migration(root,{apply:true,rollback:true,planId:STAGE6_SESSION_PLAN.id})).toMatchObject({mode:"rollback",restored:true});expect(existsSync(join(root,"kernel/sessions.json"))).toBe(false);expect(readFileSync(join(root,"sessions.json"),"utf8")).toBe(before);expect(readFileSync(join(root,"tasks.json"),"utf8")).toBe(changed);expect(inventoryMigrationCopy(root)).toMatchObject({canonicalSessionStore:"legacy",cardinality:{tasks:2},keyRefs:{blocking:1}});}finally{clean();}});

  test("commit marker disagreement fails closed",()=>{const root=base(true);try{const input=repair(root);runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input});writeFileSync(join(root,"migrations",STAGE6_SESSION_PLAN.id,"commit.json"),JSON.stringify({planId:STAGE6_SESSION_PLAN.id,schemaFrom:1,schemaTo:99,validated:true}));expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input})).toThrow("MIGRATION_COMMIT_MARKER_INVALID");}finally{clean();}});

  test("idempotent apply validates schema, exact target digest and post surface",()=>{for(const drift of["schema","target","marker"]){const root=base(true);try{const input=repair(root);runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input});if(drift==="schema")writeFileSync(join(root,"schema.json"),JSON.stringify({version:1,applied:[]}));if(drift==="target"){const file=join(root,"kernel/sessions.json"),store=JSON.parse(readFileSync(file,"utf8"));store.sessions[0].cwd="/different-but-valid";writeFileSync(file,JSON.stringify(store));}if(drift==="marker"){const file=join(root,"migrations",STAGE6_SESSION_PLAN.id,"commit.json"),marker=JSON.parse(readFileSync(file,"utf8"));marker.post.cardinality.sessions++;writeFileSync(file,JSON.stringify(marker));}expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input})).toThrow(drift==="marker"?"MIGRATION_COMMITTED_STATE_INVALID":"MIGRATION_COMMITTED_STATE_INVALID");}finally{clean();}}});

  for(const fault of["rollback-mid-primary-switch","rollback-mid-schema","rollback-mid-marker"] as const)test(`rollback fault ${fault} keeps a single visible store and is rerunnable`,()=>{const root=base(true);try{const input=repair(root);runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input});expect(()=>runStage6Migration(root,{apply:true,rollback:true,planId:STAGE6_SESSION_PLAN.id,faultAt:fault})).toThrow("injected");expect(new SessionRepository(root).getById("orphan")?.archive).toBeUndefined();expect(runStage6Migration(root,{apply:true,rollback:true,planId:STAGE6_SESSION_PLAN.id})).toMatchObject({restored:true});expect(existsSync(join(root,"kernel/sessions.json"))).toBe(false);}finally{clean();}});

  test("rollback refuses a later schema owner instead of overwriting its applied state",()=>{const root=base(true);try{const input=repair(root);runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input});const schema={version:1,applied:[STAGE6_SESSION_PLAN.id,"later-migration"]};writeFileSync(join(root,"schema.json"),JSON.stringify(schema));expect(()=>runStage6Migration(root,{apply:true,rollback:true,planId:STAGE6_SESSION_PLAN.id})).toThrow("MIGRATION_ROLLBACK_SCHEMA_DRIFT");expect(JSON.parse(readFileSync(join(root,"schema.json"),"utf8"))).toEqual(schema);expect(existsSync(join(root,"kernel/sessions.json"))).toBe(true);}finally{clean();}});

  test("retry refuses semantic source drift after a staged fault",()=>{const root=base(true);try{const input=repair(root);expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input,faultAt:"after-staging"})).toThrow("injected");writeFileSync(join(root,"actions.json"),"[ ]");expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_SESSION_PLAN.id,repairInput:input})).toThrow("MIGRATION_REPAIR_SOURCE_MISMATCH");}finally{clean();}});
});

describe("stage6 transaction shell",()=>{
  test("no-op remains a fixture plan but blocks dangling refs",()=>{const root=base();try{expect(runStage6Migration(root,{planId:STAGE6_NOOP_PLAN.id})).toMatchObject({plan:{id:STAGE6_NOOP_PLAN.id},applyEligible:true});runStage6Migration(root,{apply:true,planId:STAGE6_NOOP_PLAN.id});expect(runStage6Migration(root,{apply:true,planId:STAGE6_NOOP_PLAN.id})).toMatchObject({idempotent:true});}finally{clean();}const orphan=base(true);try{expect(()=>runStage6Migration(orphan,{apply:true,planId:STAGE6_NOOP_PLAN.id})).toThrow("MIGRATION_APPLY_BLOCKED_BY_REFS");}finally{clean();}});
  test("only a stale lease from a dead owner is recoverable",()=>{const now=Date.now(),lease={pid:999999,token:"old",at:new Date(now-MIGRATION_LEASE_STALE_MS).toISOString()};expect(canRecoverMigrationLease(lease,now,()=>false)).toBe(true);expect(canRecoverMigrationLease(lease,now,()=>true)).toBe(false);});
  test("stale lease claim cannot delete a successor",()=>{const root=base(),dir=join(root,"migrations"),lease=join(dir,".global-lease"),first=`${lease}.first`,second=`${lease}.second`;try{mkdirSync(dir,{recursive:true});writeFileSync(lease,JSON.stringify({pid:999999,token:"old",at:"2000-01-01T00:00:00.000Z"}));expect(claimStaleMigrationLease(lease,first,"old")).toBe(true);writeFileSync(lease,JSON.stringify({pid:process.pid,token:"successor",at:new Date().toISOString()}));expect(claimStaleMigrationLease(lease,second,"old")).toBe(false);expect(JSON.parse(readFileSync(lease,"utf8")).token).toBe("successor");}finally{clean();}});
  test("marker, secrets and symlinks are rejected before apply",()=>{for(const kind of["marker","secrets","symlink"]){const root=base();try{if(kind==="marker")rmSync(join(root,".ownward-connector-drill-copy"));if(kind==="secrets"){mkdirSync(join(root,"secrets"));writeFileSync(join(root,"secrets/token"),"secret");}if(kind==="symlink")symlinkSync(join(root,"tasks.json"),join(root,"linked.json"));expect(()=>runStage6Migration(root,{apply:true,planId:STAGE6_NOOP_PLAN.id})).toThrow();}finally{clean();}}});
});
