#!/bin/bash
# Crash-recoverable transaction for the immutable Runner + daemon release pair.
set -euo pipefail
[ "$(id -u)" -ne 0 ]||{ echo "❌ 禁止以 root 发布" >&2;exit 64; }
cd "$(dirname "$0")/..";SOURCE_ROOT="$(pwd)";DATA_ROOT="${OWNWARD_DATA_ROOT:-$SOURCE_ROOT/data}";BUN="${OWNWARD_BUN:-$(command -v bun || true)}";DOMAIN="gui/$(id -u)";AGENT_DIR="$HOME/Library/LaunchAgents";RELEASES="$DATA_ROOT/releases";MARKER="$RELEASES/transaction.json";LOCK="$RELEASES/.install.lock";DEPLOY_LOCK_OWNED=0;DEPLOY_LOCK_TOKEN="${OWNWARD_DEPLOYMENT_LOCK_TOKEN:-}"
[ -n "$BUN" ]&&[ -x "$BUN" ]||{ echo "❌ 找不到 bun" >&2;exit 69; };mkdir -p "$RELEASES" "$AGENT_DIR";chmod 700 "$RELEASES"
durable_write(){ local path="$1" mode="${2:-384}";"$BUN" "$SOURCE_ROOT/src/release/durable-write.ts" write "$path" "$mode"; }
durable_remove(){ "$BUN" "$SOURCE_ROOT/src/release/durable-write.ts" remove "$1"; }
proc_start(){ ps -o lstart= -p "$1" 2>/dev/null|sed 's/^ *//'; }
release_deployment_lock(){ [ "$DEPLOY_LOCK_OWNED" = 0 ]||"$BUN" "$SOURCE_ROOT/src/release/deployment-lock.ts" release "$DATA_ROOT" "$DEPLOY_LOCK_TOKEN" 2>/dev/null||true; }
if [ -n "$DEPLOY_LOCK_TOKEN" ];then "$BUN" "$SOURCE_ROOT/src/release/deployment-lock.ts" assert "$DATA_ROOT" "$DEPLOY_LOCK_TOKEN" >/dev/null;else DEPLOY_LOCK_TOKEN="$("$BUN" "$SOURCE_ROOT/src/release/deployment-lock.ts" acquire "$DATA_ROOT" "$$")";DEPLOY_LOCK_OWNED=1;fi
trap release_deployment_lock EXIT
if ! mkdir -m 700 "$LOCK" 2>/dev/null;then LPID="$(sed -n 's/^pid=//p' "$LOCK/owner" 2>/dev/null||true)";LSTART="$(sed -n 's/^start=//p' "$LOCK/owner" 2>/dev/null||true)";if [[ "$LPID" =~ ^[1-9][0-9]*$ ]]&&kill -0 "$LPID" 2>/dev/null&&[ "$(proc_start "$LPID")" = "$LSTART" ];then echo "❌ 已有 release transaction pid=$LPID" >&2;exit 75;fi;STALE="$RELEASES/.install.stale.$$";mv "$LOCK" "$STALE"||exit 75;chmod -R u+rwX,go-rwx "$STALE" 2>/dev/null||true;rm -rf "$STALE";mkdir -m 700 "$LOCK"||exit 75;fi
printf 'pid=%s\nstart=%s\n' "$$" "$(proc_start $$)"|durable_write "$LOCK/owner" 384;chmod 700 "$LOCK"
initial_cleanup(){ rm -f "$LOCK/owner";rmdir "$LOCK" 2>/dev/null||true;release_deployment_lock; }
trap initial_cleanup EXIT
[ "$(stat -f %Lp "$LOCK")" = 700 ]||{ echo "❌ release lock permissions invalid" >&2;exit 65; }
[ -z "${OWNWARD_LOCK_TEST_EXIT:-}" ]||exit "$OWNWARD_LOCK_TEST_EXIT"
RUNNER_PLIST="$AGENT_DIR/ai.ownward.runner.plist";DAEMON_PLIST="$AGENT_DIR/ai.ownward.daemon.plist";COMMITTED=0
json(){ "$BUN" -e 'const x=JSON.parse(await Bun.file(process.argv[1]).text());let v=x;for(const k of process.argv[2].split("."))v=v?.[k];if(v!==undefined&&v!==null)console.log(v)' "$1" "$2"; }
plist_json(){ plutil -convert json -o - "$1" 2>/dev/null; }
plist_env(){ local file="$1" key="$2";[ -f "$file" ]||return 0;plist_json "$file"|"$BUN" -e 'const x=JSON.parse(await Bun.stdin.text());console.log(x.EnvironmentVariables?.[process.argv[1]]??"")' "$key"; }
bootstrap_plist(){ local label="$1" file="$2";launchctl bootout "$DOMAIN/$label" 2>/dev/null||true;if [ -f "$file" ];then cp "$file" "$AGENT_DIR/$label.plist";chmod 600 "$AGENT_DIR/$label.plist";for _ in 1 2 3 4 5;do launchctl bootstrap "$DOMAIN" "$AGENT_DIR/$label.plist" 2>/dev/null&&return 0;sleep 2;done;return 1;else rm -f "$AGENT_DIR/$label.plist";fi; }
runner_probe(){ local plist="$1" expected data root;expected="$(plist_env "$plist" OWNWARD_RUNNER_BUILD_IDENTITY)";data="$(plist_env "$plist" OWNWARD_DATA_ROOT)";root="$(plist_json "$plist"|"$BUN" -e 'const x=JSON.parse(await Bun.stdin.text());console.log(x.WorkingDirectory??"")')";[ -n "$data" ]||data="$DATA_ROOT";if [ -n "$expected" ];then STATUS="$(cd "$root"&&OWNWARD_DATA_ROOT="$data" "$BUN" src/runner/health.ts)";"$BUN" -e 'const{parseRunnerHealth}=await import(process.argv[1]);parseRunnerHealth(JSON.parse(process.argv[2]),{expectedBuild:process.argv[3]})' "$SOURCE_ROOT/src/runner/health-contract.ts" "$STATUS" "$expected";else (cd "$root"&&OWNWARD_DATA_ROOT="$data" "$BUN" src/runner/health.ts >/dev/null);fi; }
snapshot_port(){ local plist="$1" config root;config="$(plist_env "$plist" OWNWARD_CONFIG_ROOT)";root="$(plist_json "$plist"|"$BUN" -e 'const x=JSON.parse(await Bun.stdin.text());console.log(x.WorkingDirectory??"")')";[ -n "$root" ]||return 1;if [ -n "$config" ];then "$BUN" "$root/src/release/config-snapshot.ts" validate "$config" >/dev/null||return 1;else config="$root";fi;"$BUN" -e 'let x={};try{x=JSON.parse(await Bun.file(process.argv[1]+"/config.json").text())}catch{}const p=Number(x.dashboard?.port??4517);if(!Number.isSafeInteger(p)||p<1||p>65535)process.exit(65);console.log(p)' "$config"; }
daemon_probe(){ local plist="$1" expected port endpoint;expected="$(plist_env "$plist" OWNWARD_BUILD_IDENTITY)";port="$(snapshot_port "$plist")"||return 1;endpoint=api/system/runtime-health;[ -n "$expected" ]||endpoint=api/state;for _ in $(seq 1 30);do BODY="$(curl -fsS --max-time 2 "http://127.0.0.1:$port/$endpoint" 2>/dev/null||true)";if [ -n "$BODY" ];then if [ -z "$expected" ];then return 0;else "$BUN" -e 'const x=JSON.parse(process.argv[1]);if(x.ok!==true||x.buildIdentity!==process.argv[2])process.exit(1)' "$BODY" "$expected"&&return 0;fi;fi;sleep 1;done;return 1; }
restore_marker(){ local backup ready=false;backup="$(json "$MARKER" backupDir)";case "$backup" in "$RELEASES"/tx-*) ;; *) echo "invalid transaction backup path" >&2;return 1;;esac;echo "restoring interrupted release transaction from $backup" >&2;launchctl bootout "$DOMAIN/ai.ownward.daemon" 2>/dev/null||true;bootstrap_plist ai.ownward.runner "$backup/runner.plist"||return 1;if [ -f "$backup/runner.plist" ];then for _ in $(seq 1 30);do if runner_probe "$backup/runner.plist";then ready=true;break;fi;sleep 1;done;[ "$ready" = true ]||return 1;fi;bootstrap_plist ai.ownward.daemon "$backup/daemon.plist"||return 1;[ ! -f "$backup/daemon.plist" ]||daemon_probe "$backup/daemon.plist"||return 1;return 0; }
plist_config_digest(){ local file="$1" config;config="$(plist_env "$file" OWNWARD_CONFIG_ROOT)";[ -n "$config" ]||return 1;"$BUN" "$SOURCE_ROOT/src/release/config-snapshot.ts" validate "$config"|"$BUN" -e 'const x=JSON.parse(await Bun.stdin.text());console.log(x.id)'; }
pair_is_target(){ local target="$1" target_config="$2";[ "$(plist_env "$RUNNER_PLIST" OWNWARD_RUNNER_BUILD_IDENTITY)" = "$target" ]&&[ "$(plist_env "$DAEMON_PLIST" OWNWARD_BUILD_IDENTITY)" = "$target" ]&&[ "$(plist_config_digest "$RUNNER_PLIST")" = "$target_config" ]&&[ "$(plist_config_digest "$DAEMON_PLIST")" = "$target_config" ]&&runner_probe "$RUNNER_PLIST"&&daemon_probe "$DAEMON_PLIST"; }
recover_marker(){ local backup target target_config previous previous_config phase state_current state_current_config pair=false decision;backup="$(json "$MARKER" backupDir)";target="$(json "$MARKER" target)";target_config="$(json "$MARKER" targetConfig)";previous="$(json "$MARKER" previous)";previous_config="$(json "$MARKER" previousConfig)";phase="$(json "$MARKER" phase)";state_current="$(test -f "$RELEASES/state.json"&&json "$RELEASES/state.json" current||true)";state_current_config="$(test -f "$RELEASES/state.json"&&json "$RELEASES/state.json" currentConfigDigest||true)";pair_is_target "$target" "$target_config"&&pair=true;decision="$("$BUN" -e 'const{decideInterruptedRelease}=await import(process.argv[1]);console.log(decideInterruptedRelease({phase:process.argv[2],stateCurrent:process.argv[3],stateCurrentConfig:process.argv[4],target:process.argv[5],targetConfig:process.argv[6],pairIsTarget:process.argv[7]==="true"}))' "$SOURCE_ROOT/src/release/recovery-policy.ts" "$phase" "$state_current" "$state_current_config" "$target" "$target_config" "$pair")";if [ "$decision" = finalize-target ];then echo "finalizing interrupted committed release $target/$target_config" >&2;else restore_marker||return 1;if [ -f "$RELEASES/state.json" ];then "$BUN" -e 'const p=process.argv[1],previous=process.argv[2],previousConfig=process.argv[3],target=process.argv[4],targetConfig=process.argv[5],x=JSON.parse(await Bun.file(p).text());x.current=previous;x.currentConfigDigest=previousConfig;x.lastGood=previous;x.rollbackCandidate=target;x.rollbackCandidateConfigDigest=targetConfig;x.rejected=target;console.log(JSON.stringify(x))' "$RELEASES/state.json" "$previous" "$previous_config" "$target" "$target_config"|durable_write "$RELEASES/state.json" 384;fi;fi;rm -rf "$backup";durable_remove "$MARKER"; }
[ ! -L "$MARKER" ]||{ echo "❌ release transaction marker must not be a symlink" >&2;exit 65; };if [ -f "$MARKER" ];then recover_marker||{ echo "❌ interrupted release recovery failed; marker/backups preserved" >&2;exit 70;};fi
if [ -n "${OWNWARD_TARGET_RELEASE_ID:-}" ];then BUILD_ID="$OWNWARD_TARGET_RELEASE_ID";RELEASE_ROOT="$RELEASES/$BUILD_ID";"$BUN" "$RELEASE_ROOT/src/release/build.ts" validate "$RELEASE_ROOT" "$BUILD_ID" >/dev/null;MODE=rollback;else git diff --quiet --ignore-submodules --&&git diff --cached --quiet --ignore-submodules --||{ echo "❌ tracked worktree/index 不干净，拒绝构建不可复现 release" >&2;exit 65;};MANIFEST="$("$BUN" src/release/build.ts prepare "$SOURCE_ROOT" "$RELEASES")";BUILD_ID="$("$BUN" -e 'console.log(JSON.parse(process.argv[1]).buildIdentity)' "$MANIFEST")";RELEASE_ROOT="$RELEASES/$BUILD_ID";MODE=deploy;fi
"$BUN" "$RELEASE_ROOT/src/release/build.ts" validate "$RELEASE_ROOT" "$BUILD_ID" >/dev/null
[ -z "${OWNWARD_EXPECTED_BUILD:-}" ]||[ "$BUILD_ID" = "$OWNWARD_EXPECTED_BUILD" ]||{ echo "❌ release build differs from evolve attempt" >&2;exit 76; }
PRIVATE_ROOT="$RELEASES/private";SOURCE_CONFIG_DIGEST="$($BUN "$RELEASE_ROOT/src/release/config-snapshot.ts" digest "$SOURCE_ROOT")";[ -z "${OWNWARD_EXPECTED_SOURCE_CONFIG_DIGEST:-}" ]||[ "$SOURCE_CONFIG_DIGEST" = "$OWNWARD_EXPECTED_SOURCE_CONFIG_DIGEST" ]||{ echo "❌ source config digest changed before snapshot" >&2;exit 76; };if [ "$MODE" = deploy ];then CONFIG_DIGEST="$SOURCE_CONFIG_DIGEST";else CONFIG_DIGEST="${OWNWARD_TARGET_CONFIG_DIGEST:-$SOURCE_CONFIG_DIGEST}";fi;PRIVATE_RELEASE="$PRIVATE_ROOT/$BUILD_ID/$CONFIG_DIGEST";[ ! -L "$PRIVATE_ROOT" ]&&[ ! -L "$PRIVATE_RELEASE" ]||{ echo "❌ private release path must not be a symlink" >&2;exit 65; };CONFIG_ROOT="$PRIVATE_RELEASE/config";if [ "$MODE" = deploy ];then mkdir -p "$PRIVATE_RELEASE";chmod 700 "$PRIVATE_ROOT" "$PRIVATE_ROOT/$BUILD_ID" "$PRIVATE_RELEASE";SNAPSHOT_JSON="$("$BUN" "$RELEASE_ROOT/src/release/config-snapshot.ts" prepare "$SOURCE_ROOT" "$CONFIG_ROOT")";PREPARED_CONFIG_DIGEST="$(printf '%s' "$SNAPSHOT_JSON"|"$BUN" -e 'const x=JSON.parse(await Bun.stdin.text());console.log(x.id)')";[ "$PREPARED_CONFIG_DIGEST" = "$CONFIG_DIGEST" ]||{ echo "❌ prepared config digest mismatch" >&2;exit 76; };else SNAPSHOT="$($BUN "$RELEASE_ROOT/src/release/config-snapshot.ts" locate "$PRIVATE_ROOT/$BUILD_ID" "${OWNWARD_TARGET_CONFIG_DIGEST:-}")";CONFIG_ROOT="$(printf '%s' "$SNAPSHOT"|$BUN -e 'const x=JSON.parse(await Bun.stdin.text());console.log(x.root)')";CONFIG_DIGEST="$(printf '%s' "$SNAPSHOT"|$BUN -e 'const x=JSON.parse(await Bun.stdin.text());console.log(x.id)')";fi
TXID="$(date +%s)-$$-$RANDOM";BACKUP="$RELEASES/tx-$TXID";mkdir "$BACKUP";chmod 700 "$BACKUP";[ ! -f "$RUNNER_PLIST" ]||cp "$RUNNER_PLIST" "$BACKUP/runner.plist";[ ! -f "$DAEMON_PLIST" ]||cp "$DAEMON_PLIST" "$BACKUP/daemon.plist"
PREVIOUS="$(test -f "$RELEASES/state.json"&&json "$RELEASES/state.json" current||true)";PREVIOUS_CONFIG="$(test -f "$RELEASES/state.json"&&json "$RELEASES/state.json" currentConfigDigest||true)";printf '{"formatVersion":1,"transactionId":"%s","pid":%s,"target":"%s","targetConfig":"%s","previous":"%s","previousConfig":"%s","mode":"%s","phase":"prepared","backupDir":"%s"}\n' "$TXID" "$$" "$BUILD_ID" "$CONFIG_DIGEST" "$PREVIOUS" "$PREVIOUS_CONFIG" "$MODE" "$BACKUP"|durable_write "$MARKER" 384
phase(){ "$BUN" -e 'const f=process.argv[1],x=JSON.parse(await Bun.file(f).text());x.phase=process.argv[2];console.log(JSON.stringify(x))' "$MARKER" "$1"|durable_write "$MARKER" 384; }
on_exit(){ rc=$?;trap - EXIT;if [ "$rc" -ne 0 ]&&[ "$COMMITTED" = 0 ];then if restore_marker;then rm -rf "$BACKUP";durable_remove "$MARKER";else echo "❌ paired recovery failed; marker/backups preserved at $BACKUP" >&2;rc=70;fi;fi;rm -f "$LOCK/owner";rmdir "$LOCK" 2>/dev/null||true;release_deployment_lock;exit "$rc"; };trap on_exit EXIT
export OWNWARD_RELEASE_ROOT="$RELEASE_ROOT" OWNWARD_DATA_ROOT="$DATA_ROOT" OWNWARD_SOURCE_ROOT="$SOURCE_ROOT" OWNWARD_CONFIG_ROOT="$CONFIG_ROOT" OWNWARD_BUILD_IDENTITY="$BUILD_ID" OWNWARD_BUN="$BUN"
bash "$SOURCE_ROOT/launchd/install-runner.sh";phase runner-installed
bash "$SOURCE_ROOT/launchd/install.sh";phase daemon-observed
# canary 也只盯 claude/codex：codebuddy 是第三方网关（登录态易过期），不许它把发布事务打回滚
CONFIGURED_CANARY="$(cd "$RELEASE_ROOT"&&OWNWARD_PROVIDER_CANARY="${OWNWARD_PROVIDER_CANARY:-}" "$BUN" -e 'import{cfg}from"./src/util.ts";const on=process.env.OWNWARD_PROVIDER_CANARY!=="0"&&(process.env.OWNWARD_PROVIDER_CANARY==="1"||cfg.release?.providerCanary===true);console.log(on?Object.entries(cfg.providers??{}).filter(([,v])=>v?.enabled!==false).map(([k])=>k==="claude-code"?"claude":k).filter(k=>k==="claude"||k==="codex").join(" "):"")')"
CANARY="";for provider in $CONFIGURED_CANARY;do if command -v "$provider" >/dev/null 2>&1;then CANARY="${CANARY:+$CANARY }$provider";else echo "⚠ provider canary skipped: $provider CLI not installed";fi;done
if [ -n "$CANARY" ];then "$BUN" "$RELEASE_ROOT/src/release/provider-canary.ts" "$RELEASE_ROOT" $CANARY;fi;phase canary-passed
STATE="$RELEASES/state.json";PREVIOUS_CONFIG_DIGEST="$(test -f "$STATE"&&json "$STATE" currentConfigDigest||true)";if [ "$MODE" = rollback ];then REJECTED="$PREVIOUS";ROLLBACK_CANDIDATE="";ROLLBACK_CONFIG_DIGEST="";else REJECTED="";ROLLBACK_CANDIDATE="$PREVIOUS";ROLLBACK_CONFIG_DIGEST="$PREVIOUS_CONFIG_DIGEST";fi;printf '{"formatVersion":1,"current":"%s","currentConfigDigest":"%s","lastGood":"%s","rollbackCandidate":"%s","rollbackCandidateConfigDigest":"%s","rejected":"%s","committedAt":"%s","evolveAttemptId":"%s"}\n' "$BUILD_ID" "$CONFIG_DIGEST" "$BUILD_ID" "$ROLLBACK_CANDIDATE" "$ROLLBACK_CONFIG_DIGEST" "$REJECTED" "$(date -u +%FT%TZ)" "${OWNWARD_EVOLVE_ATTEMPT_ID:-}"|durable_write "$STATE" 384;phase state-committed
COMMITTED=1;durable_remove "$MARKER";rm -rf "$BACKUP";rm -f "$LOCK/owner";rmdir "$LOCK";release_deployment_lock;trap - EXIT;echo "✅ release committed: $BUILD_ID"
