import { describe, expect, test } from "bun:test";
import type { ConnectorCheckpoint, ConnectorContext, ConnectorEvent } from "../kernel/connectors/contracts.ts";
import { collectGithub, runGithubPoll } from "./github.ts";
import { accessTokenFromGrant, collectGmailAccount, runGmailPoll } from "./gmail.ts";
import { collectStockAt, restoreStockState, runStockTick } from "./stock.ts";
import { ConnectorRuntime } from "../kernel/connectors/runtime.ts";
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";

const VALID_ID=/^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,255}$/;

function fixture(id: string, config: Record<string, unknown> = {}) {
  const published: Array<{ events: readonly ConnectorEvent[]; checkpoint?: ConnectorCheckpoint }> = []; let checkpoint: ConnectorCheckpoint | null = null;
  const ctx: ConnectorContext = { id, generation: "fixture-generation", config, signal: new AbortController().signal, checkpoint: async () => checkpoint, publish: async (events, next) => { published.push({ events, checkpoint: next }); checkpoint = next ?? checkpoint; return { accepted: events.length, duplicates: 0 }; }, secret: async () => undefined, reportHealth: async()=>{}, log: () => {} };
  return { ctx, published };
}

describe("first-party ConnectorContext adapters", () => {
  test("GitHub emits only changed thread revisions and unread snapshots", async () => {
    const f = fixture("github"); const threads = [{ id: "42", reason: "review_requested", updated_at: "2026-08-16T01:02:03Z", repository: { full_name: "o/r" }, subject: { title: "PR", type: "PullRequest", url: "https://api.github.com/repos/o/r/pulls/7" } }];
    await collectGithub(f.ctx, async () => ({ code: 0, stdout: JSON.stringify(threads), stderr: "" })); await collectGithub(f.ctx, async () => ({ code: 0, stdout: JSON.stringify(threads), stderr: "" }));
    expect(f.published[0]!.events[0]).toMatchObject({ id: "42:2026-08-16T01:02:03Z:1", namespace: "github.inbox", type: "review_requested", occurredAt: "2026-08-16T01:02:03Z", payload: { subjectType: "PullRequest", type: "PullRequest", updatedAt: "2026-08-16T01:02:03Z", updated_at: "2026-08-16T01:02:03Z", observation: 1 } }); expect(f.published[0]!.checkpoint?.cursor).toBe("2026-08-16T01:02:03Z");expect(f.published[0]!.events.at(-1)?.id).toMatch(/^snapshot:/);expect(f.published[1]!.events).toHaveLength(0);expect(f.published[1]!.checkpoint?.metadata).toMatchObject({observation:1,count:0});
  });
  test("GitHub fetch cap withholds partial snapshots and reports degraded health",async()=>{const f=fixture("github"),rows=Array.from({length:1001},(_,i)=>({id:String(i),reason:"subscribed",updated_at:"2026-08-16T01:00:00Z",repository:{full_name:"o/r"},subject:{title:String(i),type:"Issue"}})),health:any[]=[],logs:string[]=[];(f.ctx as any).reportHealth=async(v:any)=>health.push(v);(f.ctx as any).log=(_op:string,msg:string)=>logs.push(msg);let args:string[]=[];await collectGithub(f.ctx,async(a)=>{args=a;return{code:0,stdout:JSON.stringify([rows.slice(0,600),rows.slice(600)]),stderr:""};});expect(args).toEqual(["gh","api","notifications","--method","GET","--paginate","--slurp","-f","per_page=100"]);expect(f.published[0]!.events.filter(e=>e.type!=="snapshot")).toHaveLength(1000);expect(f.published[0]!.events.some(e=>e.type==="snapshot")).toBeFalse();expect(health).toEqual([expect.objectContaining({ok:false,code:"GITHUB_NOTIFICATIONS_TRUNCATED",detail:expect.objectContaining({total:1001,snapshotPublished:false})})]);expect(logs[0]).toContain("truncated at 1000");expect(JSON.parse(String(f.published[0]!.checkpoint?.metadata?.threadRevisions))).toHaveProperty("999");expect(JSON.parse(String(f.published[0]!.checkpoint?.metadata?.threadRevisions))).not.toHaveProperty("1000");});

  test("GitHub real gh fixture observes a GET instead of -f's implicit POST",async()=>{const dir=mkdtempSync(join(tmpdir(),"ownward-gh-argv-")),capture=join(dir,"argv"),oldPath=process.env.PATH;try{const gh=join(dir,"gh");writeFileSync(gh,`#!/bin/sh\nprintf '%s\\n' "$@" > '${capture}'\ncase " $* " in *" --method GET "*) printf '[]';; *) printf 'wrong method' >&2; exit 64;; esac\n`);chmodSync(gh,0o755);process.env.PATH=`${dir}:${oldPath||""}`;const f=fixture("github");await collectGithub(f.ctx);expect(readFileSync(capture,"utf8").trim().split("\n")).toEqual(["api","notifications","--method","GET","--paginate","--slurp","-f","per_page=100"]);expect(f.published[0]!.events[0]?.type).toBe("snapshot");}finally{process.env.PATH=oldPath;rmSync(dir,{recursive:true,force:true});}});

  test("GitHub snapshot identity stays unique when a historical unread set returns",async()=>{const f=fixture("github"),empty:any[]=[],b=[{id:"B",reason:"review_requested",updated_at:"2026-08-16T01:00:00Z",repository:{full_name:"o/r"},subject:{title:"B",type:"PullRequest",url:"https://api.github.com/repos/o/r/pulls/2"}}];const runWith=(rows:any[])=>collectGithub(f.ctx,async()=>({code:0,stdout:JSON.stringify(rows),stderr:""}));await runWith(empty);await runWith(empty);await runWith(b);await runWith(empty);const snapshots=f.published.flatMap(x=>x.events).filter(x=>x.type==="snapshot");expect(f.published[1]!.events).toHaveLength(0);expect(new Set(snapshots.map(x=>x.id)).size).toBe(3);expect(snapshots.map(x=>x.payload.observation)).toEqual([1,2,3]);expect((snapshots[2]!.payload.unreadThreadIds as string[])).toEqual([]);});
  test("GitHub re-emits a resolved thread with the same updated_at in a new observation",async()=>{const f=fixture("github"),thread={id:"42",reason:"review_requested",updated_at:"2026-08-16T01:02:03Z",repository:{full_name:"o/r"},subject:{title:"PR",type:"PullRequest"}},poll=(rows:any[])=>collectGithub(f.ctx,async()=>({code:0,stdout:JSON.stringify(rows),stderr:""}));await poll([thread]);await poll([]);await poll([thread]);const reviews=f.published.flatMap(x=>x.events).filter(x=>x.type==="review_requested");expect(reviews.map(x=>x.id)).toEqual(["42:2026-08-16T01:02:03Z:1","42:2026-08-16T01:02:03Z:3"]);expect(reviews.map(x=>x.payload.observation)).toEqual([1,3]);});

  test("GitHub snapshot identity cannot collide with accepted history after corrupt checkpoint recovery",async()=>{const data=mkdtempSync(join(tmpdir(),"ownward-github-identity-")),manifest:any={id:"github",name:"GitHub",version:"1.0.0",kernelApiVersion:1,entry:"builtin",capabilities:["events","checkpoint"],eventNamespaces:["github.inbox"]},empty:any[]=[],b=[{id:"B",reason:"review_requested",updated_at:"2026-08-16T01:00:00Z",repository:{full_name:"o/r"},subject:{title:"B",type:"PullRequest"}}];try{let ctx!:ConnectorContext;const make=()=>new ConnectorRuntime({dataRoot:data,config:{connectors:{github:{enabled:true}}},builtins:[{manifest,load:async()=>({start(c:ConnectorContext){ctx=c;}})}]});let runtime=make();await runtime.start();await collectGithub(ctx,async()=>({code:0,stdout:JSON.stringify(empty),stderr:""}));await runtime.stop();mkdirSync(join(data,"connectors","github"),{recursive:true});writeFileSync(join(data,"connectors","github","checkpoint.json"),"{");runtime=make();await runtime.start();const runWith=(rows:any[])=>collectGithub(ctx,async()=>({code:0,stdout:JSON.stringify(rows),stderr:""}));await runWith(empty);await runWith(b);await runWith(empty);expect(runtime.statuses()[0]!.accepted).toBe(4);expect(runtime.statuses()[0]!.duplicates).toBe(0);await runtime.stop();}finally{rmSync(data,{recursive:true,force:true});}});
  test("GitHub repeated poll under backpressure keeps one stable pending snapshot",async()=>{const data=mkdtempSync(join(tmpdir(),"ownward-github-pending-")),manifest:any={id:"github",name:"GitHub",version:"1.0.0",kernelApiVersion:1,entry:"builtin",capabilities:["events","checkpoint"],eventNamespaces:["github.inbox"]};writeFileSync(join(data,"queue.jsonl"),JSON.stringify({source:"other",ts:new Date().toISOString(),payload:{}})+"\n");try{let ctx!:ConnectorContext;const runtime=new ConnectorRuntime({dataRoot:data,maxPendingEvents:1,config:{connectors:{github:{enabled:true}}},builtins:[{manifest,load:async()=>({start(c:ConnectorContext){ctx=c;}})}]});await runtime.start();const poll=()=>collectGithub(ctx,async()=>({code:0,stdout:"[]",stderr:""}));await poll();await poll();const dir=join(data,"connectors","github","pending"),files=readdirSync(dir).filter(f=>f.endsWith(".json"));expect(files).toHaveLength(1);expect(runtime.statuses()[0]).toMatchObject({accepted:0,duplicates:0});await runtime.stop();}finally{rmSync(data,{recursive:true,force:true});}});
  test("GitHub deferred A-B-A keeps only the final snapshot while preserving review events",async()=>{const data=mkdtempSync(join(tmpdir(),"ownward-github-singleton-")),manifest:any={id:"github",name:"GitHub",version:"1.0.0",kernelApiVersion:1,entry:"builtin",capabilities:["events","checkpoint"],eventNamespaces:["github.inbox"],singletonEventTypes:["snapshot"]},filler=JSON.stringify({source:"other",ts:new Date().toISOString(),payload:{}})+"\n",b=[{id:"B",reason:"review_requested",updated_at:"2026-08-16T01:00:00Z",repository:{full_name:"o/r"},subject:{title:"B",type:"PullRequest"}}];writeFileSync(join(data,"queue.jsonl"),filler+filler);try{let ctx!:ConnectorContext;const projected:any[]=[];const runtime=new ConnectorRuntime({dataRoot:data,maxPendingEvents:2,drainBaseMs:5,drainMaxMs:20,onEvents:events=>{projected.push(...events);},config:{connectors:{github:{enabled:true}}},builtins:[{manifest,load:async()=>({start(c:ConnectorContext){ctx=c;}})}]});await runtime.start();const poll=(rows:any[])=>collectGithub(ctx,async()=>({code:0,stdout:JSON.stringify(rows),stderr:""}));await poll([]);await poll(b);await poll([]);const dir=join(data,"connectors","github","pending"),pending=readdirSync(dir).filter(name=>name.endsWith(".json")).flatMap(name=>JSON.parse(readFileSync(join(dir,name),"utf8")).events);expect(pending.filter((event:any)=>event.type==="snapshot")).toHaveLength(1);expect(pending.find((event:any)=>event.type==="snapshot").payload.unreadThreadIds).toEqual([]);expect(pending.some((event:any)=>event.type==="review_requested")).toBeTrue();rmSync(join(data,"queue.jsonl"));const deadline=Date.now()+1_000;while(Date.now()<deadline&&readdirSync(dir).some(name=>name.endsWith(".json")))await Bun.sleep(10);expect(projected.at(-1)?.key).toBe("github.inbox.snapshot");expect(projected.at(-1)?.payload.unreadThreadIds).toEqual([]);await runtime.stop();}finally{rmSync(data,{recursive:true,force:true});}});


  test("Gmail publishes account-scoped stable message ids without changing workbench APIs", async () => {
    const f = fixture("gmail"), api = async (path: string) => path.startsWith("/messages?") ? { messages: [{ id: "m1" }] } : { threadId: "t1", snippet: "hello", payload: { headers: [{ name: "From", value: "a@example.com" }, { name: "Subject", value: "Hi" }, { name: "Date", value: "Sun, 16 Aug 2026 10:00:00 +0800" }] } };
    await collectGmailAccount(f.ctx, { email: "me@example.com", file: "/unused" }, api as any);
    const event=f.published[0]!.events[0]!;expect(event.id).toMatch(VALID_ID);expect(event).toMatchObject({ namespace: "gmail.inbox", type: "message", payload: { id:"m1",messageId: "m1", threadId: "t1", account: "me@example.com" } }); expect(f.published[0]!.checkpoint?.metadata).toMatchObject({ account: "me@example.com", count: 1 });
  });

  test("Gmail skips metadata requests for message ids persisted in its checkpoint", async () => {
    const f = fixture("gmail"); let metadataRequests = 0;
    const api = async (path: string) => {
      if (path.startsWith("/messages?")) return { messages: [{ id: "m1" }] };
      metadataRequests++; return { threadId: "t1", snippet: "hello", payload: { headers: [] } };
    };
    await collectGmailAccount(f.ctx, { email: "me@example.com", file: "/unused" }, api as any);
    await collectGmailAccount(f.ctx, { email: "me@example.com", file: "/unused" }, api as any);
    expect(metadataRequests).toBe(1);
    expect(f.published[1]).toMatchObject({ events: [], checkpoint: { metadata: { count: 0 } } });
    expect(JSON.parse(String(f.published[1]!.checkpoint?.metadata?.knownMessageIds))).toEqual({ "me@example.com": ["m1"] });
  });

  test("Gmail grant token is reused across a poll and concurrent refresh is coalesced",async()=>{const original=globalThis.fetch;let refreshes=0;globalThis.fetch=(async()=>{refreshes++;return new Response(JSON.stringify({access_token:"fresh",expires_in:3600}),{status:200});})as any;try{const creds:any={client_id:"client-cache-test",client_secret:"secret",refresh_token:"refresh-cache-test"};expect(await Promise.all([accessTokenFromGrant(creds),accessTokenFromGrant({...creds})])).toEqual(["fresh","fresh"]);expect(await accessTokenFromGrant({...creds})).toBe("fresh");expect(refreshes).toBe(1);}finally{globalThis.fetch=original;}});

  test("Gmail and GitHub poll guards skip overlapping intervals and release after failure",async()=>{for(const guard of[runGmailPoll,runGithubPoll]){const state={running:false};let release!:()=>void,runs=0;const first=guard(state,()=>new Promise<void>(resolve=>{runs++;release=resolve;}));while(!release)await Bun.sleep(1);expect(await guard(state,async()=>{runs++;})).toBe(false);release();expect(await first).toBe(true);await expect(guard(state,async()=>{runs++;throw new Error("failed");})).rejects.toThrow("failed");expect(state.running).toBe(false);expect(runs).toBe(2);}});

  test("Stock publishes one stable scheduled snapshot per symbol", async () => {
    const f = fixture("stock", { watchlist: ["TSLA.US", "AAPL.US"] }), now = new Date("2026-08-17T02:00:00.000Z");
    await collectStockAt(f.ctx, now, async (args) => ({ code: 0, stdout: `report:${args.at(-1)}`, stderr: "" }));
    expect(f.published[0]!.events).toHaveLength(2); expect(f.published[0]!.events.map((event) => event.id)).toEqual([expect.stringContaining(":TSLA.US"), expect.stringContaining(":AAPL.US")]); expect(f.published[0]!.events.every((event) => VALID_ID.test(event.id)&&!event.id.includes(" ")&&event.namespace === "stock.inbox" && event.type === "snapshot")).toBe(true); expect(f.published[0]!.checkpoint?.cursor).toBe("2026-08-17T10:00");
  });

  test("Stock failed scheduled collection remains retryable until publish succeeds",async()=>{const f=fixture("stock",{watchlist:["TSLA.US"],checkTimes:["10:00"]}),state={lastFired:""},now=new Date("2026-08-17T02:00:00.000Z");let attempts=0;expect(await runStockTick(f.ctx,state,now,async()=>{attempts++;throw new Error("temporary");})).toBe(false);expect(state.lastFired).toBe("");expect(await runStockTick(f.ctx,state,now,async()=>{attempts++;return{code:0,stdout:"ok",stderr:""};})).toBe(true);expect(attempts).toBe(2);expect(state.lastFired).toBe("2026-08-17T10:00");expect(await runStockTick(f.ctx,state,now,async()=>{throw new Error("must not run");})).toBe(false);});
  test("Stock catches up a scheduled minute missed by the 30-second ticker",async()=>{const f=fixture("stock",{watchlist:["TSLA.US"],checkTimes:["10:00"]}),state={lastFired:""};expect(await runStockTick(f.ctx,state,new Date("2026-08-17T02:01:00.000Z"),async()=>({code:0,stdout:"ok",stderr:""}))).toBe(true);expect(f.published[0]!.events[0]).toMatchObject({id:expect.stringContaining("2026-08-17T10:00"),payload:{scheduledAt:"2026-08-17T10:00"}});expect(state.lastFired).toBe("2026-08-17T10:00");});

  test("Stock skips overlapping ticks and releases its running guard",async()=>{const f=fixture("stock",{watchlist:["TSLA.US"],checkTimes:["10:00"]}),state={lastFired:"",running:false},now=new Date("2026-08-17T02:00:00.000Z");let release!:()=>void;const first=runStockTick(f.ctx,state,now,()=>new Promise(resolve=>{release=()=>resolve({code:0,stdout:"ok",stderr:""});}));while(!release)await Bun.sleep(1);expect(await runStockTick(f.ctx,state,now,async()=>({code:0,stdout:"duplicate",stderr:""}))).toBe(false);release();expect(await first).toBe(true);expect(state.running).toBe(false);});
  test("live GitHub context rotates generation after checkpoint quarantine",async()=>{const data=mkdtempSync(join(tmpdir(),"ownward-github-live-generation-")),manifest:any={id:"github",name:"GitHub",version:"1.0.0",kernelApiVersion:1,entry:"builtin",capabilities:["events","checkpoint"],eventNamespaces:["github.inbox"]};try{let ctx!:ConnectorContext;const runtime=new ConnectorRuntime({dataRoot:data,config:{connectors:{github:{enabled:true}}},builtins:[{manifest,load:async()=>({start(c:ConnectorContext){ctx=c;}})}]});await runtime.start();const poll=()=>collectGithub(ctx,async()=>({code:0,stdout:"[]",stderr:""}));await poll();const g1=ctx.generation,first=readFileSync(join(data,"queue.jsonl"),"utf8").trim();writeFileSync(join(data,"connectors","github","checkpoint.json"),"{");expect(await ctx.checkpoint()).toBeNull();const g2=ctx.generation;expect(g2).not.toBe(g1);await poll();const ids=readFileSync(join(data,"queue.jsonl"),"utf8").trim().split("\n").map(line=>JSON.parse(line).id);expect(ids).toHaveLength(2);expect(new Set(ids).size).toBe(2);expect(first).toContain(g1);expect(ids[1]).toContain(g2);expect(runtime.statuses()[0]).toMatchObject({accepted:2,duplicates:0,state:"ready"});await runtime.stop();}finally{rmSync(data,{recursive:true,force:true});}});
  test("Stock restores last fired schedule from connector checkpoint",async()=>{const f=fixture("stock");await f.ctx.publish([],{version:1,cursor:"2026-08-17T10:00",updatedAt:"2026-08-17T02:00:00Z"});expect(await restoreStockState(f.ctx)).toEqual({lastFired:"2026-08-17T10:00",running:false});});
});
