import {afterEach,expect,test} from "bun:test";
import {mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from "fs";
import {tmpdir} from "os";
import {join} from "path";
import {commitTaskPatchesAt,durableLaunchReceipt,runnerTaskPatch} from "./dispatch.ts";
import {RunnerCommandJournal} from "./runner/journals.ts";
import {RunRepository} from "./runs/repository.ts";
import {SessionRepository} from "./sessions/repository.ts";

const roots:string[]=[];
afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));

test("durable accept is recoverable after post-submit sync disconnect",async()=>{const root=mkdtempSync(join(tmpdir(),"ownward-launch-")),cwd=join(root,"repo");roots.push(root);mkdirSync(cwd);const session=new SessionRepository(root).reserve({taskId:"task",providerId:"claude",cwd});new RunnerCommandJournal(root).accept({commandId:"accepted-command",kind:"start-run",runId:"accepted-run",sessionId:session.id,providerId:"claude",input:"{}"});new RunRepository(root).append({schemaVersion:1,eventId:"accepted-event",type:"command-accepted",at:"2026-08-17T00:00:00.000Z",commandId:"accepted-command",runId:"accepted-run",taskId:"task",sessionId:session.id,providerId:"claude"});expect(await durableLaunchReceipt(root,"task")).toEqual({commandId:"accepted-command",runId:"accepted-run"});expect(await durableLaunchReceipt(root,"other")).toBeNull();});
test("latest follow-up Run maps completed failed interrupted and unknown without stale ids",()=>{for(const [status,expected] of[["completed",{status:"exited",exitCode:0,uncertain:false}],["failed",{status:"exited",exitCode:7,uncertain:false}],["interrupted",{status:"exited",exitCode:130,uncertain:false}],["unknown_outcome",{status:"exited",uncertain:true,endedAt:"2026-08-17T00:00:00.000Z"}]] as const){expect(runnerTaskPatch({status,commandId:`new-${status}`,runId:`run-${status}`,endedAt:"2026-08-17T00:00:00.000Z",terminal:{providerExitCode:7}} as any)).toMatchObject({...expected,commandId:`new-${status}`,runId:`run-${status}`});}});
test("terminal patch CAS cannot overwrite a newer accepted Run",()=>{const root=mkdtempSync(join(tmpdir(),"ownward-patch-cas-"));roots.push(root);writeFileSync(join(root,"tasks.json"),JSON.stringify([{id:"task",project:"p",projectDir:"/tmp",cwd:"/tmp",task:"x",mode:"claude-bg",engine:true,startedAt:"now",status:"running",commandId:"run-B-command",runId:"run-B"}]));commitTaskPatchesAt(root,new Map([["task",{status:"exited",commandId:"run-A-command",runId:"run-A",exitCode:1}]]),new Map([["task",{commandId:"run-A-command",runId:"run-A"}]]));expect(JSON.parse(readFileSync(join(root,"tasks.json"),"utf8"))[0]).toMatchObject({status:"running",commandId:"run-B-command",runId:"run-B"});commitTaskPatchesAt(root,new Map([["task",{status:"exited",commandId:"run-B-command",runId:"run-B",exitCode:0}]]),new Map([["task",{commandId:"run-B-command",runId:"run-B"}]]));expect(JSON.parse(readFileSync(join(root,"tasks.json"),"utf8"))[0]).toMatchObject({status:"exited",commandId:"run-B-command",runId:"run-B",exitCode:0});});
