import { chmodSync, existsSync, lstatSync, mkdtempSync, rmSync } from "fs";
import { timingSafeEqual } from "crypto";
import { join } from "path";
import { tmpdir } from "os";
import { fileURLToPath } from "url";
import { clampFrameMax, encodeHostFrame, HostFrameDecoder, type HostEnvelope } from "./host-protocol.ts";
import type { VerticalManifest } from "./contracts.ts";
import type { ScopedStorage } from "./contracts.ts";

type Pending = { resolve: (v: Record<string, any>) => void; reject: (e: Error) => void; timer: ReturnType<typeof setTimeout> };
const BASE_OUTGOING_BYTES = 2 * 1024 * 1024;
export class ExtensionHostClient {
  private socket?: Bun.Socket<ExtensionHostClient>; private proc?: Bun.Subprocess; private decoder: HostFrameDecoder; private pending = new Map<string, Pending>(); private readonly outgoing: Uint8Array[] = []; private outgoingOffset = 0; private queuedBytes = 0; private runtimeDir = ""; private socketPath = ""; private readonly capability = Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString("hex"); private stopped = false; private terminatingUnexpected = false; private stderrTail = "";
  private storageLease=crypto.randomUUID();
  private actions:import("./contracts.ts").ScopedActions|undefined;
  private actionsLease=crypto.randomUUID();
  private llm:import("./contracts.ts").ScopedLlm|undefined;
  private llmLease=crypto.randomUUID();
  private readonly frameMax: number;
  private readonly maxOutgoingBytes: number;
  constructor(readonly root: string, readonly manifest: VerticalManifest, private storage: ScopedStorage | undefined, private readonly onExit: (code: number | null) => void, private readonly logger: (operation: string, message: string) => void, options: { frameMaxBytes?: number } = {}) { this.frameMax = clampFrameMax(options.frameMaxBytes); this.maxOutgoingBytes = Math.max(BASE_OUTGOING_BYTES, this.frameMax + 1024 * 1024); this.decoder = new HostFrameDecoder(this.frameMax); }
  setStorage(storage:ScopedStorage|undefined){this.storage=storage;this.storageLease=crypto.randomUUID();}
  setActions(actions:import("./contracts.ts").ScopedActions|undefined){this.actions=actions;this.actionsLease=crypto.randomUUID();}
  setLlm(llm:import("./contracts.ts").ScopedLlm|undefined){this.llm=llm;this.llmLease=crypto.randomUUID();}
  async launch(readinessTimeoutMs:number):Promise<void>{
    this.runtimeDir = mkdtempSync(join(tmpdir(), `ownward-extension-${this.manifest.id}-`)); chmodSync(this.runtimeDir, 0o700); this.socketPath = join(this.runtimeDir, "host.sock"); const hostEntry = fileURLToPath(new URL("./host-entry.ts", import.meta.url)), entry = join(this.root, this.manifest.entry);
    this.proc = Bun.spawn([process.execPath, hostEntry], { detached: true, stdin: "ignore", stdout: "ignore", stderr: "pipe", env: { PATH: process.env.PATH || "/usr/bin:/bin", LANG: process.env.LANG || "C.UTF-8", OWNWARD_EXTENSION_SOCKET: this.socketPath, OWNWARD_EXTENSION_CAPABILITY: this.capability, OWNWARD_EXTENSION_ROOT: this.root, OWNWARD_EXTENSION_ENTRY: entry, OWNWARD_EXTENSION_FRAME_MAX: String(this.frameMax) } }); void this.captureStderr(this.proc.stderr as ReadableStream<Uint8Array>);
    void this.proc.exited.then((code) => { this.disconnect(Object.assign(new Error("Extension Host exited"), { code: "EXTENSION_HOST_EXITED" })); if (!this.stopped) this.onExit(code); });
    const end = Date.now() + readinessTimeoutMs;
    // Windows：Bun 把 `unix:` 映射成命名管道，socket 路径上不会出现任何文件实体，
    // 所以 POSIX 的「stat 到 socket 且 uid/mode 正确」这道就绪门在这里永远不会亮
    // （process.getuid 本身也是 undefined）。改成等 host-entry 落下的 .ready 标记。
    // 不能退化成「连不上就重试」：连接失败会触发 connectError → unexpectedDisconnect，
    // 那条路会把刚起来的 Host 一起杀掉，重试反而必然失败。
    // 归属校验的等价物在 Windows 上是管道名（mkdtemp 随机私有目录）+ 每帧的 capability token。
    if (process.platform === "win32") {
      while (!existsSync(this.socketPath + ".ready")) {
        if (this.proc.exitCode !== null) throw Object.assign(new Error("Extension Host 启动失败"), { code: "EXTENSION_HOST_EXITED" });
        if (Date.now() >= end) { this.kill(); throw Object.assign(new Error("Extension Host readiness 超时"), { code: "EXTENSION_HOST_START_TIMEOUT" }); }
        await Bun.sleep(5);
      }
      await this.connect();
      return;
    }
    let ready=false; while (!ready) { if (Date.now() >= end) { this.kill(); throw Object.assign(new Error("Extension Host readiness 超时"), { code: "EXTENSION_HOST_START_TIMEOUT" }); } if (this.proc.exitCode !== null) throw Object.assign(new Error("Extension Host 启动失败"), { code: "EXTENSION_HOST_EXITED" }); if(existsSync(this.socketPath)){try{const st=lstatSync(this.socketPath);ready=st.isSocket()&&st.uid===process.getuid()&&(st.mode&0o077)===0;}catch{}} if(!ready)await Bun.sleep(5); }
    await this.connect();
  }
  async migrate(config:Record<string,unknown>,migrationId:string,timeoutMs:number){return this.request("migrate",{id:this.manifest.id,config:structuredClone(config),grants:{storage:!!this.storage,leaseId:this.storageLease,actions:!!this.actions,actionsLeaseId:this.actionsLease,llm:!!this.llm,llmLeaseId:this.llmLease},migrationId},timeoutMs);}
  async describe(timeoutMs:number){return this.request("describe",{},timeoutMs);}
  async activate(config:Record<string,unknown>,timeoutMs:number){return this.request("activate", { id: this.manifest.id, config: structuredClone(config), grants: { storage: !!this.storage,leaseId:this.storageLease,actions:!!this.actions,actionsLeaseId:this.actionsLease,llm:!!this.llm,llmLeaseId:this.llmLease } }, timeoutMs);}
  async start(config:Record<string,unknown>,readinessTimeoutMs:number,activateTimeoutMs:number){await this.launch(readinessTimeoutMs);return this.activate(config,activateTimeoutMs);}
  private async connect() { const self = this, disconnected=()=>Object.assign(new Error("Extension Host disconnected"),{code:"EXTENSION_HOST_DISCONNECTED"}); await Bun.connect<ExtensionHostClient>({ unix: this.socketPath, data: this, socket: { binaryType: "buffer", open(socket) { self.socket = socket; }, data(socket, bytes) { if (self.socket !== socket) return; let frames: HostEnvelope[]; try { frames = self.decoder.push(bytes); } catch { self.unexpectedDisconnect(Object.assign(new Error("Extension Host protocol invalid"),{code:"EXTENSION_HOST_PROTOCOL_INVALID"})); return; } for (const frame of frames) void self.receive(frame); }, drain(socket) { if (self.socket === socket) self.flush(); }, close(socket) { if (self.socket === socket) self.unexpectedDisconnect(disconnected()); }, end(socket) { if (self.socket === socket) self.unexpectedDisconnect(disconnected()); }, error(socket) { if (self.socket === socket) self.unexpectedDisconnect(disconnected()); }, connectError() { self.unexpectedDisconnect(disconnected()); } } }); }
  async request(method: string, body: Record<string, unknown>, timeoutMs = 2_000, killOnTimeout = true): Promise<Record<string, any>> { if (!this.socket) throw Object.assign(new Error("Extension Host unavailable"), { code: "EXTENSION_HOST_UNAVAILABLE" }); const id = `kernel-${crypto.randomUUID()}`; return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(id); reject(Object.assign(new Error("Extension Host timeout"), { code: "EXTENSION_HOST_TIMEOUT" })); if(killOnTimeout)this.kill(); }, timeoutMs); this.pending.set(id, { resolve, reject, timer }); try { this.send({ version: 1, type: "request", id, capability: this.capability, method, body }); } catch (error) { clearTimeout(timer); this.pending.delete(id); reject(error); } }); }
  private async receive(env:HostEnvelope){const a=Buffer.from(env.capability),b=Buffer.from(this.capability);if(a.length!==b.length||!timingSafeEqual(a,b)){this.kill();return}if(env.type==="response"){const p=this.pending.get(env.id);if(!p)return;clearTimeout(p.timer);this.pending.delete(env.id);env.ok?p.resolve(env.body):p.reject(Object.assign(new Error("Extension Host rejected request"),{code:env.errorCode||"EXTENSION_HOST_ERROR"}));return}try{let body:Record<string,unknown>={};const keys=Object.keys(env.body).sort(),key=env.body.key;if(env.method.startsWith("storage.")&&env.body.leaseId!==this.storageLease)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});if(["storage.read","storage.remove"].includes(env.method)&&JSON.stringify(keys)!==JSON.stringify(["key","leaseId"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});if(env.method==="storage.write"&&JSON.stringify(keys)!==JSON.stringify(["key","leaseId","value"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});if(env.method==="log"&&JSON.stringify(keys)!==JSON.stringify(["message","operation"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});if(env.method.startsWith("storage.")&&(typeof key!=="string"||!/^[A-Za-z0-9._/-]{1,200}$/.test(key)))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});if(env.method==="storage.read"){if(!this.storage)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});body={value:this.storage.readJson(key as string)}}else if(env.method==="storage.write"){if(!this.storage)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});if(JSON.stringify(env.body.value).length>256*1024)throw Object.assign(new Error(),{code:"EXTENSION_STORAGE_VALUE_TOO_LARGE"});this.storage.writeJson(key as string,env.body.value)}else if(env.method==="storage.remove"){if(!this.storage)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});this.storage.remove(key as string)}else if(env.method==="llm.complete"){if(env.body.leaseId!==this.llmLease)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});if(!this.llm)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});if(JSON.stringify(keys)!==JSON.stringify(["input","leaseId"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});const inp=env.body.input as any;if(!inp||typeof inp!=="object"||Array.isArray(inp)||typeof inp.prompt!=="string"||Object.keys(inp).some((k)=>!["prompt","json","schema","filePath","timeoutMs","engine","model"].includes(k)))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});body={value:await this.llm.complete(inp)};}
      else if(env.method==="llm.engines"){if(env.body.leaseId!==this.llmLease)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});if(!this.llm)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});if(JSON.stringify(keys)!==JSON.stringify(["leaseId"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});body={value:await this.llm.engines()};}
      else if(env.method.startsWith("actions.")){if(env.body.leaseId!==this.actionsLease)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});if(!this.actions)throw Object.assign(new Error(),{code:"EXTENSION_CAPABILITY_REVOKED"});
      if(env.method==="actions.list"){if(JSON.stringify(keys)!==JSON.stringify(["leaseId"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});body={actions:await this.actions.list()};}
      else if(env.method==="actions.open"){if(JSON.stringify(keys)!==JSON.stringify(["action","leaseId"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});const a=env.body.action as any;if(!a||typeof a!=="object"||Array.isArray(a)||Object.keys(a).some((k)=>!["id","kind","title","reason","ref"].includes(k)))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});body={ok:await this.actions.open(a)};}
      else if(env.method==="actions.resolve"){if(JSON.stringify(keys)!==JSON.stringify(["id","leaseId","resolution"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});if(typeof env.body.id!=="string"||typeof env.body.resolution!=="string")throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});body={ok:await this.actions.resolve(env.body.id,env.body.resolution)};}
      else if(env.method==="actions.dismiss"){if(JSON.stringify(keys)!==JSON.stringify(["id","leaseId"]))throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});if(typeof env.body.id!=="string")throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});body={ok:await this.actions.dismiss(env.body.id)};}
      else throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_METHOD_DENIED"});}
      else if(env.method==="log"){if(typeof env.body.operation!=="string"||typeof env.body.message!=="string")throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_REQUEST_INVALID"});this.logger(env.body.operation.slice(0,80),env.body.message.slice(0,500))}else throw Object.assign(new Error(),{code:"EXTENSION_KERNEL_METHOD_DENIED"});this.send({version:1,type:"response",id:env.id,capability:this.capability,method:env.method,ok:true,body})}catch(e:any){this.send({version:1,type:"response",id:env.id,capability:this.capability,method:env.method,ok:false,errorCode:String(e?.code||"EXTENSION_KERNEL_ERROR"),body:{}})}}
  private send(env: HostEnvelope) { const frame = encodeHostFrame(env, this.frameMax); if (this.queuedBytes + frame.byteLength > this.maxOutgoingBytes) { const error = Object.assign(new Error("Extension Host outgoing queue overflow"), { code: "EXTENSION_HOST_BACKPRESSURE" }), socket = this.socket; this.disconnect(error); socket?.close(); throw error; } this.outgoing.push(frame); this.queuedBytes += frame.byteLength; this.flush(); }
  private flush() { const socket = this.socket; if (!socket) return; while (this.outgoing.length) { const frame = this.outgoing[0]!, written = socket.write(frame, this.outgoingOffset, frame.byteLength - this.outgoingOffset); if (written < 0) { this.disconnect(Object.assign(new Error("Extension Host write failed"), { code: "EXTENSION_HOST_WRITE_FAILED" })); socket.close(); return; } if (written === 0) return; this.outgoingOffset += written; this.queuedBytes -= written; if (this.outgoingOffset < frame.byteLength) return; this.outgoing.shift(); this.outgoingOffset = 0; } }
  diagnostics(){return this.stderrTail?{stderrTail:this.stderrTail}:{};}
  private async captureStderr(stream:ReadableStream<Uint8Array>){try{const reader=stream.getReader(),decoder=new TextDecoder();while(true){const next=await reader.read();if(next.done)break;this.stderrTail=redactHostStderr(this.stderrTail+decoder.decode(next.value,{stream:true}),this.capability,this.root).slice(-16*1024);}this.stderrTail=redactHostStderr(this.stderrTail+decoder.decode(),this.capability,this.root).slice(-16*1024);}catch{}}
  async stop(timeoutMs = 1_000) { this.stopped = true; try { await this.request("stop", {}, timeoutMs); } catch {} this.kill(); }
  kill() { this.stopped = true; const proc=this.proc,pid = proc?.pid; if (pid) { try { process.kill(-pid, "SIGTERM"); } catch {} try{proc.kill("SIGTERM");}catch{} setTimeout(() => { try { process.kill(-pid, "SIGKILL"); } catch {} try{proc.kill("SIGKILL");}catch{} }, 250); } this.socket?.close(); this.socket = undefined; if (this.runtimeDir) rmSync(this.runtimeDir, { recursive: true, force: true }); }
  private unexpectedDisconnect(error:Error){if(this.stopped||this.terminatingUnexpected){this.disconnect(error);return;}this.terminatingUnexpected=true;const socket=this.socket,proc=this.proc,pid=proc?.pid;this.disconnect(error);socket?.close();if(pid){try{process.kill(-pid,"SIGTERM")}catch{}try{proc?.kill("SIGTERM")}catch{}setTimeout(()=>{try{process.kill(-pid,"SIGKILL")}catch{}try{proc?.kill("SIGKILL")}catch{}},250);}}
  private disconnect(error: Error) { this.socket = undefined; this.outgoing.length = 0; this.outgoingOffset = 0; this.queuedBytes = 0; for (const p of this.pending.values()) { clearTimeout(p.timer); p.reject(error); } this.pending.clear(); }
}
function redactHostStderr(value:string,capability:string,root:string):string{return value.replaceAll(capability,"[REDACTED_CAPABILITY]").replaceAll(root,"[REDACTED_EXTENSION_ROOT]").replace(/\b(token|secret|password|authorization)\s*[:=]\s*\S+/gi,"$1=[REDACTED]").slice(-16*1024);}
