import{expect,test}from"bun:test";
import{existsSync,mkdtempSync,readFileSync,rmSync,symlinkSync,writeFileSync}from"fs";
import{tmpdir}from"os";
import{join}from"path";
import{durableWrite}from"./durable-write.ts";
import{decideInterruptedRelease}from"./recovery-policy.ts";

test("SIGKILL after state pointer switch converges to observed target build+config pair",()=>{const base={phase:"canary-passed",stateCurrent:"same-build",stateCurrentConfig:"new-config",target:"same-build",targetConfig:"new-config"};expect(decideInterruptedRelease({...base,pairIsTarget:true})).toBe("finalize-target");expect(decideInterruptedRelease({...base,stateCurrentConfig:"old-config",pairIsTarget:true})).toBe("restore-previous");expect(decideInterruptedRelease({...base,pairIsTarget:false})).toBe("restore-previous")});
test("SIGKILL at earlier phase restores an unproven pair",()=>{expect(decideInterruptedRelease({phase:"runner-installed",stateCurrent:"old",target:"new",pairIsTarget:false})).toBe("restore-previous")});
test("durable state and marker survive externally injected SIGKILL and re-entry converges to actual pair",async()=>{for(const fault of["after-state","early"]){const dir=mkdtempSync(join(tmpdir(),"release-kill-")),state=join(dir,"state.json"),marker=join(dir,"marker.json"),actualFile=join(dir,"actual.json"),durable=JSON.stringify(join(import.meta.dir,"durable-write.ts"));try{durableWrite(actualFile,JSON.stringify({pair:"old"}));const child=Bun.spawn([process.execPath,"-e",`import{durableWrite}from ${durable};durableWrite(${JSON.stringify(marker)},JSON.stringify({phase:${JSON.stringify(fault==="after-state"?"canary-passed":"runner-installed")},target:"new",previous:"old"}));durableWrite(${JSON.stringify(state)},JSON.stringify({current:${JSON.stringify(fault==="after-state"?"new":"old")}}));Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0)`]);for(let i=0;i<200&&!existsSync(state);i++)await Bun.sleep(2);expect(existsSync(marker)).toBeTrue();expect(existsSync(state)).toBeTrue();child.kill("SIGKILL");expect(await child.exited).not.toBe(0);const m=JSON.parse(readFileSync(marker,"utf8")),s=JSON.parse(readFileSync(state,"utf8")),actual=JSON.parse(readFileSync(actualFile,"utf8")).pair,decision=decideInterruptedRelease({phase:m.phase,stateCurrent:s.current,target:m.target,pairIsTarget:actual===m.target});if(decision==="restore-previous")s.current=m.previous;durableWrite(state,JSON.stringify(s));expect(JSON.parse(readFileSync(state,"utf8")).current).toBe(actual)}finally{rmSync(dir,{recursive:true,force:true})}}});
test("durable writes refuse symlink targets and ancestor directories",()=>{const dir=mkdtempSync(join(tmpdir(),"durable-link-")),outside=join(dir,"outside"),link=join(dir,"link");try{writeFileSync(outside,"old");symlinkSync(outside,link);expect(()=>durableWrite(link,"new")).toThrow("symlink");rmSync(link);symlinkSync(dir,link);expect(()=>durableWrite(join(link,"state.json"),"new")).toThrow("symlink");expect(readFileSync(outside,"utf8")).toBe("old")}finally{rmSync(dir,{recursive:true,force:true})}});
