"use strict";
/* Settings + Skill Control Plane：写操作始终先生成确定性 diff/plan，再由浏览器会话批准。 */
const Settings={category:"general",schema:null,effective:null,settingsError:"",draft:new Map(),validation:null,validateTimer:null,operation:null,operationTimer:null,pollFailures:0,pollStarted:0,skills:null,registry:null,skillsError:"",skillMode:"catalog",query:"",filter:"all",selected:"",analysis:null,analysisProgress:null,progressTimer:null,selectedActions:new Set(),plan:null,transaction:null,transactions:[],busy:"",dialogReturn:null};
const SETTING_CATEGORIES=[["general","通用","称呼、时区与 Vault"],["system","系统与运行","运行健康、组件与计划"],["engines","AI 引擎","Provider、模型与权限"],["skills","Skills","跨引擎发现、整理与纳管"],["sources","事件源","飞书、GitHub、Gmail 与股票"],["automation","自动化","心跳、日报与分流"],["notifications","通知","macOS 与飞书提醒"],["extensions","扩展","已安装 Vertical 的启停"],["advanced","高级","网络、命令与诊断"]];
const CATEGORY_ROOTS={general:["owner","timezone","quietHours","vault"],engines:["chat","llm","providers","dispatch","engine","architecture"],sources:["connectors"],automation:["heartbeat","digest","triage"],notifications:["notify"],extensions:["verticals"],advanced:["dashboard","strategy"]};
const LABELS={verticals:"扩展",owner:"Owner",timezone:"时区",quietHours:"静默时段",vault:"知识库",chat:"对话",llm:"后台 AI",providers:"Provider",dispatch:"任务派发",engine:"会话引擎",architecture:"架构权限",connectors:"事件源",heartbeat:"心跳",digest:"日报",triage:"事件分流",notify:"通知",dashboard:"Dashboard",strategy:"策略",enabled:"启用",port:"端口",listen:"监听范围",root:"目录",name:"称呼",intervalMin:"间隔（分钟）",model:"模型",effort:"思考深度",allowFullAccess:"允许完整访问",allowedRoots:"授权目录"};
const TERMINAL_SETTINGS=new Set(["committed","restored","manual-repair"]),TERMINAL_SKILLS=new Set(["committed","rolled-back","manual-repair"]);
const controlPlaneFrozen=()=>Settings.operation?.phase==="manual-repair"||Settings.transaction?.phase==="manual-repair"||Settings.transactions.some(tx=>tx.phase==="manual-repair");
async function requestJSON(url,options={}){const response=await fetch(url,options),text=await response.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={message:text}}if(!response.ok){const error=new Error(body?.error?.message||body?.message||`${url} → ${response.status}`);error.status=response.status;error.code=body?.error?.code||body?.error;error.body=body;throw error}return{status:response.status,body}}
const postJSON=(url,body)=>requestJSON(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body||{})});
const pointerParts=p=>p.slice(1).split("/").map(x=>x.replaceAll("~1","/").replaceAll("~0","~"));
const valueAt=(root,p)=>pointerParts(p).reduce((value,key)=>value?.[key],root);const labelFor=p=>pointerParts(p).map(k=>LABELS[k]||k).join(" · ");
const jsonValue=v=>typeof v==="string"?v:JSON.stringify(v),randomKey=()=>`${Date.now()}-${crypto.randomUUID()}`;

TABS.settings={init(root){root.innerHTML=`<aside class="settings-sidebar"><div class="page-head compact"><div><div class="eyebrow">CONTROL PLANE</div><h1>设置</h1><p>配置与多引擎 Skill 的统一控制面</p></div></div><nav class="settings-categories" aria-label="设置分类">${SETTING_CATEGORIES.map(([id,label,desc])=>`<button type="button" data-settings-category="${id}" aria-current="false"><strong>${label}</strong><span>${desc}</span><i id="settings-count-${id}"></i></button>`).join("")}</nav></aside><div class="settings-main"><div class="settings-toolbar"><div><h2 id="settings-title">通用</h2><p id="settings-subtitle"></p></div><button class="button ghost sm" id="settings-refresh" type="button">刷新</button></div><div class="settings-scroll" id="settings-content" aria-live="polite"></div><footer class="settings-apply" id="settings-footer"><span id="settings-footer-state"></span><div><button class="button ghost sm" id="settings-discard" type="button" hidden>全部放弃</button> <button class="button primary" id="settings-review" type="button" disabled>审阅并应用</button></div></footer></div><dialog class="control-dialog" id="settings-dialog" aria-labelledby="control-dialog-title"><div id="settings-dialog-body"></div></dialog>`;$$('[data-settings-category]',root).forEach(b=>b.addEventListener("click",async()=>{Settings.category=b.dataset.settingsCategory;if(Settings.category==="skills"&&!Settings.skills)await loadSkills(false);renderSettings()}));$("#settings-refresh",root).addEventListener("click",()=>Settings.category==="skills"?loadSkills(true):loadSettings(false));$("#settings-discard",root).addEventListener("click",()=>{Settings.draft.clear();Settings.validation=null;renderSettings()});$("#settings-review",root).addEventListener("click",reviewSettings);$("#settings-dialog",root).addEventListener("close",()=>Settings.dialogReturn?.focus?.());window.addEventListener("beforeunload",e=>{if(Settings.draft.size){e.preventDefault();e.returnValue=""}});loadSettings(true)},show(){renderSettings()}};

async function loadSettings(initial){const content=$("#settings-content");if(!content)return;if(initial)content.innerHTML=stateBox("正在读取设置…","loading");Settings.settingsError="";const operationId=new URLSearchParams(location.search).get("settingsOperation"),operationUrl=operationId?`/api/settings/operations/${encodeURIComponent(operationId)}`:"/api/settings/operations/current";const[schema,effective,current]=await Promise.allSettled([requestJSON("/api/settings/schema"),requestJSON("/api/settings/effective"),requestJSON(operationUrl)]);if(schema.status==="fulfilled")Settings.schema=schema.value.body;if(effective.status==="fulfilled")Settings.effective=effective.value.body;if(current.status==="fulfilled"&&current.value.body.operation){Settings.operation=current.value.body.operation;if(!TERMINAL_SETTINGS.has(Settings.operation.phase))pollSettingsOperation()}if(!Settings.schema||!Settings.effective)Settings.settingsError="设置服务暂时不可用；运行状态仍可在「系统」查看。";if(Settings.draft.size)scheduleValidation();renderSettings()}
function renderSettings(){const root=$("#settings-root");if(!root||!$("#settings-content"))return;const meta=SETTING_CATEGORIES.find(([id])=>id===Settings.category)||SETTING_CATEGORIES[0];$("#settings-title").textContent=meta[1];$("#settings-subtitle").textContent=meta[2];$$('[data-settings-category]',root).forEach(b=>{const on=b.dataset.settingsCategory===Settings.category;b.dataset.on=on;b.setAttribute("aria-current",on?"page":"false")});if(Settings.category==="system")window.renderSystemInSettings?.($("#settings-content"));else if(Settings.category==="skills")renderSkills($("#settings-content"));else if(Settings.settingsError)$("#settings-content").innerHTML=stateBox(Settings.settingsError,"error");else{renderConfig($("#settings-content"),Settings.category);if(Settings.category==="automation")window.renderRoutinesEditor?.($("#settings-content"))}renderFooter()}
function schemaFields(){const out=[];const walk=(nodes,pointer="")=>Object.entries(nodes||{}).forEach(([key,node])=>{const path=`${pointer}/${key.replaceAll("~","~0").replaceAll("/","~1")}`;node.type==="object"?walk(node.children,path):out.push({pointer:path,...node})});walk(Settings.schema?.nodes);return out}
const categoryFields=category=>schemaFields().filter(field=>field.metadata?.editable&&(CATEGORY_ROOTS[category]||[]).includes(pointerParts(field.pointer)[0]));
function shownValue(field){const patch=Settings.draft.get(field.pointer);if(patch?.op==="set")return patch.value;if(patch?.op==="remove")return field.default;return valueAt(Settings.effective?.effective||{},field.pointer)}
function fieldId(pointer){return`setting-${btoa(unescape(encodeURIComponent(pointer))).replaceAll("=","")}`}
// 已知可枚举字段 → 下拉选项（schema 未带 enum，按 pointer 末段/正则硬编码）。免手写框、减少输错。
const SELECT_OPTIONS={listen:[["local","仅本机 (127.0.0.1)"],["all","局域网可访问 (0.0.0.0)"]],engine:[["claude","Claude Code"],["codex","Codex"],["codebuddy","CodeBuddy"],["codechat","CodeChat"]],provider:[["","跟随系统默认"],["claude","Claude Code"],["codex","Codex"],["codebuddy","CodeBuddy"]],permission:[["","跟随引擎默认"],["safe","safe（需要审批）"],["bypass","bypass（完整权限）"]],identity:[["user","用户身份"],["bot","机器人身份"]]};
const TZ_LIST=["Asia/Shanghai","Asia/Hong_Kong","Asia/Tokyo","Asia/Singapore","America/New_York","America/Los_Angeles","Europe/London","UTC"];
function dispatchDefaultProvider(){const patch=Settings.draft.get("/dispatch/defaults/provider");return String(patch?.op==="set"?patch.value:patch?.op==="remove"?"":valueAt(Settings.effective?.effective||{},"/dispatch/defaults/provider")||"")}
function dispatchDefaultModel(){const patch=Settings.draft.get("/dispatch/defaults/model");return String(patch?.op==="set"?patch.value:patch?.op==="remove"?"":valueAt(Settings.effective?.effective||{},"/dispatch/defaults/model")||"")}
function dispatchDefaultEffort(){const patch=Settings.draft.get("/dispatch/defaults/effort");return String(patch?.op==="set"?patch.value:patch?.op==="remove"?"":valueAt(Settings.effective?.effective||{},"/dispatch/defaults/effort")||"")}
function selectOptionsFor(pointer){if(pointer==="/dispatch/defaults/model"){const provider=dispatchDefaultProvider(),models=WORK_PROVIDER_CAPABILITIES[provider]?.models||[];return[["","跟随引擎默认"],...models.map(value=>[value,value])]}if(pointer==="/dispatch/defaults/effort"){const provider=dispatchDefaultProvider(),efforts=workProviderEfforts(provider,dispatchDefaultModel());return[["","跟随引擎默认"],...efforts.map(value=>[value,WORK_EFFORT_LABELS[value]||value])]}const seg=pointer.split("/").pop();return SELECT_OPTIONS[seg]||null;}
function fieldControl(field){const value=shownValue(field),pointer=esc(field.pointer),id=fieldId(field.pointer);if(field.type==="boolean")return`<label class="setting-switch"><input id="${id}" data-setting-pointer="${pointer}" type="checkbox" ${value?"checked":""}><span>${value?"已开启":"已关闭"}</span></label>`;if(field.type==="array")return`<textarea id="${id}" data-setting-pointer="${pointer}" data-setting-type="array" rows="2" spellcheck="false">${esc(JSON.stringify(value??[]))}</textarea>`;const opts=selectOptionsFor(field.pointer);if(opts&&field.type!=="number"){const cur=String(value??"");const known=opts.some(([v])=>String(v)===cur),unsupportedDispatch=/^\/dispatch\/defaults\/(?:model|effort)$/.test(field.pointer)&&!known;return`<select id="${id}" data-setting-pointer="${pointer}" data-setting-type="${field.type}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===cur?"selected":""}>${esc(l)}</option>`).join("")}${known?"":`<option value="${esc(cur)}" selected ${unsupportedDispatch?"disabled":""}>${esc(unsupportedDispatch?`${cur||"（未设置）"}（所选引擎或模型不支持）`:cur||"（未设置）")}</option>`}</select>`;}if(/\/timezone$/.test(field.pointer)){return`<input id="${id}" list="tz-datalist" data-setting-pointer="${pointer}" data-setting-type="${field.type}" type="text" value="${esc(value??"")}"><datalist id="tz-datalist">${TZ_LIST.map(z=>`<option value="${z}">`).join("")}</datalist>`;}const inputType=field.type==="number"?"number":/\/(?:time|start|end)$/.test(field.pointer)?"time":"text";return`<input id="${id}" data-setting-pointer="${pointer}" data-setting-type="${field.type}" type="${inputType}" value="${esc(value??"")}" ${field.metadata?.sensitive?'autocomplete="off"':""}>`}
// 分组：按配置子对象聚合，做成层级（飞书/GitHub… 各自成组）。>2 段用前两段当组，否则用第一段。
const GROUP_NAMES={lark:"飞书",github:"GitHub",gmail:"邮件（Gmail）",stock:"股票",owner:"身份",vault:"知识库",quietHours:"静默时段",providers:"Provider",dispatch:"任务派发",defaults:"派发默认值",architecture:"架构权限",heartbeat:"心跳",digest:"日报",triage:"事件分流",timezone:"时区",notify:"通知",dashboard:"Dashboard",strategy:"策略",chat:"对话",llm:"后台 AI",engine:"会话引擎"};
// 叶子字段的短标签：分组后不再重复「事件源·lark·」前缀，只显示末段人话名。
const LEAF_LABELS={skillAnalysisModel:"Skill 整理模型",enabled:"启用",pollMin:"轮询间隔（分钟）",intervalMin:"间隔（分钟）",groupPolicy:"群消息策略",maxBatch:"单次上限",time:"时间",port:"端口",listen:"监听范围",root:"目录",dir:"默认项目目录",provider:"默认引擎",permission:"默认权限",name:"称呼",model:"默认模型",effort:"默认思考深度",identity:"身份",start:"开始",end:"结束",allowFullAccess:"允许完整访问",allowedRoots:"授权目录",timezone:"时区",engine:"引擎",aheadMin:"提前量（分钟）",window:"取材窗口",checkTimes:"检查时点",watchlist:"自选标的"};
function groupKeyOf(pointer){const parts=pointerParts(pointer);return parts.length>2?parts.slice(0,2).join("/"):parts[0];}
function groupLabelOf(key){const seg=key.split("/").pop();return GROUP_NAMES[seg]||LABELS[seg]||seg;}
function leafLabelOf(pointer){const seg=pointerParts(pointer).pop();return LEAF_LABELS[seg]||LABELS[seg]||seg;}
function settingFieldHtml(field,issues,short){const dirty=Settings.draft.has(field.pointer),overridden=Settings.effective?.provenance?.[field.pointer]==="override",issue=issues.get(field.pointer);return`<article class="settings-field editable" data-dirty="${dirty}" data-risk="${field.metadata?.risk||"low"}"><div><label for="${fieldId(field.pointer)}"><h4>${esc(short?leafLabelOf(field.pointer):labelFor(field.pointer))}</h4></label><span class="settings-path mono">${esc(field.pointer)}</span><div class="setting-badges">${overridden?"<span>本机覆盖</span>":"<span>沿用默认</span>"}${dirty?"<strong>待应用</strong>":""}${field.metadata?.risk!=="low"?"<em>高风险</em>":""}</div></div><div class="settings-editor">${fieldControl(field)}<div class="setting-actions">${overridden?`<button type="button" class="button ghost sm" data-setting-remove="${esc(field.pointer)}">沿用默认值</button>`:""}${dirty?`<button type="button" class="button ghost sm" data-setting-undo="${esc(field.pointer)}">撤销</button>`:""}</div>${issue?`<p class="setting-error" role="alert">${esc(issue)}</p>`:""}</div></article>`}
// 真层级：一个配置子对象 = 一个父分组。它的「启用」字段升为分组头上的总开关，其余字段作为子项缩进嵌在下面。
function settingGroupHtml(key,fields,issues){const enableField=fields.find(f=>pointerParts(f.pointer).pop()==="enabled");const rest=fields.filter(f=>f!==enableField);if(!enableField&&fields.length===1)return settingFieldHtml(fields[0],issues,false);const on=enableField?!!shownValue(enableField):true;return`<section class="settings-group" data-enabled="${on}"><header class="settings-group-head"><div class="settings-group-title">${esc(groupLabelOf(key))}</div>${enableField?`<div class="settings-group-switch">${fieldControl(enableField)}</div>`:""}</header>${rest.length?`<div class="settings-group-body">${rest.map(f=>settingFieldHtml(f,issues,true)).join("")}</div>`:""}</section>`}
function renderConfig(content,category){if(!Settings.schema||!Settings.effective){content.innerHTML=stateBox("正在读取设置…","loading");return}const fields=categoryFields(category),issues=new Map((Settings.validation?.issues||[]).map(x=>[x.path,x.message]));const groups=new Map();for(const f of fields){const k=groupKeyOf(f.pointer);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(f)}const body=fields.length?[...groups.entries()].map(([k,fs])=>settingGroupHtml(k,fs,issues)).join(""):`<div class="settings-callout"><strong>本分类暂无可编辑字段</strong><span>内部配置只在系统诊断中展示。</span></div>`;content.innerHTML=(Settings.operation?operationBanner(Settings.operation,"settings"):"")+body;$$('[data-setting-pointer]',content).forEach(input=>input.addEventListener("change",settingChanged));$$('[data-setting-remove]',content).forEach(b=>b.addEventListener("click",()=>{Settings.draft.set(b.dataset.settingRemove,{op:"remove",path:b.dataset.settingRemove});scheduleValidation();renderSettings()}));$$('[data-setting-undo]',content).forEach(b=>b.addEventListener("click",()=>{Settings.draft.delete(b.dataset.settingUndo);scheduleValidation();renderSettings()}))}
function settingChanged(e){const input=e.currentTarget,path=input.dataset.settingPointer,type=input.dataset.settingType||(input.type==="checkbox"?"boolean":"string");let value;try{value=type==="boolean"?input.checked:type==="number"?Number(input.value):type==="array"?JSON.parse(input.value):input.value}catch{Settings.validation={valid:false,issues:[{path,message:"请输入合法 JSON 数组"}]};renderSettings();return}Settings.draft.set(path,{op:"set",path,value});if(path==="/dispatch/defaults/provider"){const capability=WORK_PROVIDER_CAPABILITIES[value],model=capability?.defaultModel||"";Settings.draft.set("/dispatch/defaults/model",{op:"set",path:"/dispatch/defaults/model",value:model});Settings.draft.set("/dispatch/defaults/effort",{op:"set",path:"/dispatch/defaults/effort",value:model?workProviderDefaultEffort(value,model):""})}else if(path==="/dispatch/defaults/model"){const provider=dispatchDefaultProvider(),efforts=workProviderEfforts(provider,value),currentEffort=dispatchDefaultEffort();Settings.draft.set("/dispatch/defaults/effort",{op:"set",path:"/dispatch/defaults/effort",value:efforts.includes(currentEffort)?currentEffort:(value?workProviderDefaultEffort(provider,value):"")})}scheduleValidation();renderSettings()}
function scheduleValidation(){clearTimeout(Settings.validateTimer);Settings.validation=Settings.draft.size?{state:"validating",issues:[]}:null;if(Settings.draft.size)Settings.validateTimer=setTimeout(validateDraft,300)}
async function validateDraft(){try{Settings.validation=(await postJSON("/api/settings/validate",{sourceDigest:Settings.effective.sourceDigest,patches:[...Settings.draft.values()]})).body}catch(error){Settings.validation={valid:false,stale:error.status===409,issues:error.body?.issues||[{path:"",message:error.message}]}}renderSettings()}
function renderFooter(){const footer=$("#settings-footer"),state=$("#settings-footer-state"),review=$("#settings-review"),discard=$("#settings-discard");if(!footer)return;footer.hidden=Settings.category==="skills"||Settings.category==="system";if(footer.hidden)return;const draftCount=Settings.draft.size,v=Settings.validation,n=v?.valid?v.normalizedPatches?.length??draftCount:draftCount,frozen=controlPlaneFrozen();discard.hidden=!draftCount;review.disabled=!n||v?.state==="validating"||v?.valid!==true||frozen||Settings.operation&&!TERMINAL_SETTINGS.has(Settings.operation.phase);state.innerHTML=frozen?"<strong>控制面已冻结</strong> · 需要先完成人工恢复":!draftCount||v?.valid&&!n?"<strong>配置已同步</strong> · 没有有效修改":v?.state==="validating"?`<strong>正在校验 ${draftCount} 项修改…</strong>`:v?.stale?"<strong>配置已被外部修改</strong> · 草稿仍保留，请刷新后重新检查":v?.valid?`<strong>${n} 项待应用</strong> · 将事务化重启 Ownward`:`<strong>${v?.issues?.length||1} 项需要处理</strong>`}
function openDialog(html,returnEl){Settings.dialogReturn=returnEl||document.activeElement;const dialog=$("#settings-dialog"),body=$("#settings-dialog-body");body.innerHTML=html;dialog.showModal();$$('[data-dialog-close]',body).forEach(b=>b.addEventListener("click",()=>dialog.close()));return body}
function reviewSettings(e){if(!Settings.validation?.valid)return;const diff=Settings.validation.redactedDiff||[],confirmations=Settings.validation.risk?.confirmations||[];const body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">HUMAN APPROVAL</div><h2 id="control-dialog-title">审阅 ${diff.length} 项配置变更</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="approval-effects">${diff.map(item=>`<article><strong>${esc(labelFor(item.path))}</strong><code>${esc(jsonValue(item.before))}</code><span>→</span><code>${esc(jsonValue(item.after))}</code><small>${esc(item.path)} · ${item.risk}</small></article>`).join("")}</div>${confirmations.length?`<div class="approval-confirmations">${confirmations.map(item=>`<label><input type="checkbox" data-confirmation="${esc(item)}"> 我理解并确认：${esc(item)}</label>`).join("")}</div>`:""}<div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="settings-approve-apply">批准并重启 Ownward</button></div>`,e?.currentTarget);$("#settings-approve-apply",body).addEventListener("click",()=>applySettings(confirmations,body))}
async function applySettings(confirmations,body){const button=$("#settings-approve-apply",body),checked=$$('[data-confirmation]:checked',body).map(x=>x.dataset.confirmation);if(confirmations.some(item=>!checked.includes(item))){toast("请逐项确认高风险影响");return}button.disabled=true;button.textContent="正在创建审批…";const payload={sourceDigest:Settings.effective.sourceDigest,patches:[...Settings.draft.values()],confirmations:checked};try{const approval=(await postJSON("/api/settings/approve",payload)).body;button.textContent="正在启动事务…";const result=(await postJSON("/api/settings/apply",{...payload,approvalId:approval.approvalId,idempotencyKey:randomKey()})).body;Settings.operation=result.operation;$("#settings-dialog").close();history.replaceState(null,"",`${location.pathname}?tab=settings&settingsOperation=${encodeURIComponent(Settings.operation.id)}`);pollSettingsOperation();renderSettings()}catch(error){button.disabled=false;button.textContent="批准并重启 Ownward";toast(`${error.code||"应用失败"}：${error.message}`)}}
function operationBanner(operation,domain){const terminal=domain==="settings"?TERMINAL_SETTINGS:TERMINAL_SKILLS,bad=["manual-repair","restored","rolled-back"].includes(operation.phase);return`<div class="operation-banner" data-state="${bad?"error":terminal.has(operation.phase)?"done":"running"}" role="${bad?"alert":"status"}"><strong>${domain==="settings"?"设置事务":"Skill 事务"} · ${esc(operation.phase)}</strong><span>${operation.error?.message?esc(operation.error.message):operation.errorCode?esc(operation.errorCode):terminal.has(operation.phase)?"事务已结束":"正在执行或恢复，请稍候"}</span><code>${esc(operation.id)}</code></div>`}
function pollSettingsOperation(){clearTimeout(Settings.operationTimer);if(!Settings.operation||TERMINAL_SETTINGS.has(Settings.operation.phase))return;if(!Settings.pollStarted)Settings.pollStarted=Date.now();Settings.operationTimer=setTimeout(async()=>{const path=`/api/settings/operations/${Settings.operation.id}`;try{Settings.operation=(await requestJSON(path)).body.operation;Settings.pollFailures=0}catch{Settings.pollFailures++;const candidate=Settings.operation.origins?.candidate;if(Settings.pollFailures>=5&&candidate&&candidate!==location.origin){location.assign(`${candidate}/?tab=settings&settingsOperation=${encodeURIComponent(Settings.operation.id)}`);return}if(Date.now()-Settings.pollStarted>180000){Settings.operation={...Settings.operation,error:{message:"无法连接旧或候选地址。请检查端口、代理与 TLS 后重新打开 Settings。"}};renderSettings();return}}if(Settings.operation?.phase==="committed"){Settings.draft.clear();Settings.validation=null;Settings.pollStarted=0;await loadSettings(false)}renderSettings();pollSettingsOperation()},1200)}

async function loadSkills(scan){Settings.skillsError="";Settings.busy=scan?"scanning":Settings.busy;if(scan)renderSettings()
  // 操作记录和恢复入口不能挂在扫描成功上：扫描失败（daemon 重启中、某个根读不了、预算耗尽）
  // 恰恰是用户最需要回滚的时候，这时候把恢复入口一起藏掉是最坏的时机。两边各自独立取。
  const history=Promise.all([requestJSON("/api/skills/transactions").catch(()=>({body:[]})),requestJSON("/api/skills/registry").catch(()=>({body:{skills:[]}}))])
  try{Settings.skills=(await(scan?postJSON("/api/skills/scan",{}):requestJSON("/api/skills"))).body}catch(error){Settings.skillsError=error.code==="SKILL_SCAN_REQUIRED"||error.status===404?"尚未扫描 Skill":`Skill inventory 暂时不可用：${error.message}`}
  const[tx,registry]=await history
  Settings.transactions=Array.isArray(tx.body)?tx.body:tx.body.transactions||[]
  Settings.registry=registry.body
  Settings.busy=""
  renderSettings()}
function skillCatalog(){let catalog;if(Array.isArray(Settings.skills?.catalog))catalog=Settings.skills?.catalog.map(item=>({...item}));else{const groups=new Map();for(const item of Settings.skills?.observations||[]){const group=groups.get(item.name)||{logicalId:item.name,name:item.name,description:item.description,observationIds:[],engines:[],scopes:[],findings:[]};group.observationIds.push(item.id);if(!group.engines.includes(item.engine))group.engines.push(item.engine);if(!group.scopes.includes(item.scope))group.scopes.push(item.scope);for(const finding of item.findings||[])if(!group.findings.includes(finding))group.findings.push(finding);groups.set(item.name,group)}catalog=[...groups.values()]}for(const managed of Settings.registry?.skills||[]){const existing=catalog.find(item=>item.name===managed.name&&item.digest===managed.digest);if(existing){existing.managedSkillId=managed.id;continue}catalog.push({logicalId:`managed:${managed.id}`,managedSkillId:managed.id,name:managed.name,description:managed.description,digest:managed.digest,ownership:"managed",observationIds:[],engines:[...new Set(managed.deployments.map(item=>item.engine))],scopes:[...new Set(managed.deployments.map(item=>item.scope))],findings:["broken"]})}return catalog.sort((a,b)=>a.name.localeCompare(b.name))}
function renderSkills(content){const items=skillCatalog(),summary=Settings.skills?.summary||{},partial=Settings.skills?.completeness==="partial",adapters=Settings.skills?.adapters||[],frozen=controlPlaneFrozen();$("#settings-count-skills").textContent=(summary.duplicates||0)+(summary.conflicts||0)||"";content.innerHTML=`${Settings.transaction?operationBanner(Settings.transaction,"skills"):""}${Settings.busy==="planning"?stateBox("正在生成 Skill 操作方案…","loading"):""}${Settings.skillsError?stateBox(Settings.skillsError,"error"):""}<div class="skill-control-tabs" role="tablist"><button role="tab" aria-selected="${Settings.skillMode==="catalog"}" data-skill-mode="catalog" data-on="${Settings.skillMode==="catalog"}">目录</button><button role="tab" aria-selected="${Settings.skillMode==="agent"}" data-skill-mode="agent" data-on="${Settings.skillMode==="agent"}">整理建议</button><button role="tab" aria-selected="${Settings.skillMode==="history"}" data-skill-mode="history" data-on="${Settings.skillMode==="history"}">操作记录</button></div>${frozen?`<div class="settings-callout warning" role="alert"><strong>控制面已冻结</strong><span>manual-repair 未完成前禁止设置与 Skill 写操作。</span></div>`:""}${partial?`<div class="settings-callout warning"><strong>扫描结果不完整，所有写操作已禁用</strong><span>${esc((Settings.skills?.warnings||[]).join("；"))}</span></div>`:""}${adapters.some(a=>a.capability!=="read-write")?`<div class="settings-callout warning"><strong>部分引擎已降级为只读</strong><span>${adapters.map(a=>`${a.engine}: ${a.capability}${a.reason?`（${a.reason}）`:""}`).join(" · ")}</span></div>`:""}${Settings.skillMode==="catalog"?skillCatalogHtml(items):Settings.skillMode==="agent"?skillAgentHtml():skillHistoryHtml()}`;$$('[data-skill-mode]',content).forEach(b=>b.addEventListener("click",()=>{Settings.skillMode=b.dataset.skillMode;renderSettings()}));bindSkillControls(content)}
function skillCatalogHtml(items){if(Settings.skillsError&&!Settings.skills)return`<div class="settings-callout"><strong>${esc(Settings.skillsError)}</strong><button class="button secondary" id="skills-scan">开始只读扫描</button></div>`;const shown=items.filter(item=>!Settings.query||`${item.name} ${item.description||""} ${(item.engines||[]).join(" ")}`.toLowerCase().includes(Settings.query.toLowerCase())).filter(item=>Settings.filter==="all"||(item.findings||[]).includes(Settings.filter));const selected=shown.find(x=>x.logicalId===Settings.selected)||shown[0];if(selected)Settings.selected=selected.logicalId;return`<div class="skills-summary"><div><strong>${items.length}</strong><span>统一 Skills</span></div><div><strong>${Settings.skills?.summary?.duplicates||0}</strong><span>重复</span></div><div><strong>${Settings.skills?.summary?.conflicts||0}</strong><span>冲突</span></div><div><strong>${Settings.skills?.summary?.protected||0}</strong><span>受保护</span></div></div><div class="skills-tools"><input type="search" id="skills-search" placeholder="搜索名称或引擎" value="${esc(Settings.query)}"><select id="skills-filter"><option value="all">全部状态</option><option value="duplicate">重复</option><option value="conflict">冲突</option><option value="protected">受保护</option><option value="broken">失效</option></select><button class="button secondary sm" id="skills-scan">${Settings.busy==="scanning"?"扫描中…":"重新扫描"}</button></div><div class="skills-browser"><div class="skills-list">${shown.length?shown.map(item=>`<button class="skill-row" data-skill-id="${esc(item.logicalId)}" aria-pressed="${item.logicalId===Settings.selected}"><span class="skill-row-main"><strong>${esc(item.name)}</strong><small>${esc((item.engines||[]).join(" · ")||"未部署")}</small></span><span class="skill-state" data-state="${esc((item.findings||["ok"])[0]||"ok")}">${esc((item.findings||[]).join(" / ")||"正常")}</span></button>`).join(""):stateBox("没有符合筛选条件的 Skill")}</div><aside class="skill-detail">${selected?skillDetailHtml(selected):stateBox("选择一个 Skill 查看详情")}</aside></div>`}
function engineRoots(engine){return(Settings.skills?.roots||[]).filter(root=>root.engine===engine&&root.scope==="user"&&!root.protected&&["read-write","explicit-only"].includes(root.mutationCapability))}
function targetRootId(engine,deploymentPath){const roots=engineRoots(engine);if(deploymentPath){const matched=roots.find(root=>deploymentPath===`${root.path}/${deploymentPath.split("/").pop()}`);if(matched)return matched.id}return roots.length===1&&roots[0].mutationCapability==="read-write"?roots[0].id:""}
function migrateButtons(record,obs,writable){if(!record||!writable||!record.sources.some(source=>source.path===(obs.displayPath||obs.entryPath)))return"";return["claude","codex","codebuddy"].filter(engine=>engine!==obs.engine&&engineRoots(engine).length).map(engine=>`<button class="button danger sm" data-migrate-source="${esc(obs.id)}" data-skill-id="${esc(record.id)}" data-engine="${engine}" data-root-id="${esc(targetRootId(engine))}">迁移到 ${engine} 并移除此部署…</button>`).join("")}
function skillDetailHtml(item){const observations=(Settings.skills?.observations||[]).filter(x=>item.observationIds.includes(x.id)),writable=!controlPlaneFrozen()&&Settings.skills?.completeness==="complete",record=Settings.registry?.skills?.find(skill=>skill.name===item.name&&(!item.digest||skill.digest===item.digest)),engines=["claude","codex","codebuddy"],isBundle=observations.some(obs=>obs.nestedSkills>0),isConflict=observations.some(obs=>(obs.findings||[]).includes("conflict")),healthyDiscovered=observations.filter(obs=>obs.ownership==="discovered"&&!['bounded','unreadable','malformed','broken','empty'].includes(obs.state)),canAdopt=writable&&!record&&!isBundle&&observations.length===item.observationIds.length&&observations.length>0&&observations.every(obs=>obs.ownership==="discovered"&&!['bounded','unreadable','malformed','broken','empty'].includes(obs.state)),
  // 部署到哪些别的引擎：可写、且这个 Skill 在那儿还没有部署
  otherEngines=(observations.length?engines.filter(e=>!observations.some(obs=>obs.engine===e)&&engineRoots(e).length&&Settings.skills?.adapters?.find(a=>a.engine===e)?.capability==="read-write"):[]),
  exposeAttr=otherEngines.length?` data-expose="${esc(otherEngines.join(","))}"`:"",busyP=Settings.busy==="planning"?"disabled":"",
  adopt=isBundle?`<div class="settings-callout"><strong>技能包</strong><span>内嵌 ${esc(String(Math.max(...observations.map(o=>o.nestedSkills||0))))} 个 Skill，由外部工具（如 gstack）维护并随其升级。Ownward 只登记、不纳管、不删除。</span></div>`
  // 同名不同内容：不能一起纳管。给差异视图，并允许「以某一版为准」——纳管它并部署到其它引擎（其它引擎的原目录会备份后换成链接）
  :(isConflict&&writable&&!record&&healthyDiscovered.length>=2)?`<div class="conflict-actions"><button class="button secondary sm" data-conflict-diff="${esc(item.observationIds.join(","))}" ${busyP}>查看两侧差异…</button>${healthyDiscovered.map(obs=>{const others=engines.filter(e=>e!==obs.engine&&engineRoots(e).length&&Settings.skills?.adapters?.find(a=>a.engine===e)?.capability==="read-write");return`<button class="button secondary sm" data-adopt-one="${esc(obs.id)}" data-expose="${esc(others.join(","))}" ${busyP}>以 ${esc(obs.engine)} 这一版为准${others.length?`，部署到 ${esc(others.join("/"))}`:""}…</button>`}).join("")}</div>`
  :canAdopt?`<div class="conflict-actions"><button class="button secondary sm" data-adopt-catalog="${esc(item.logicalId)}"${exposeAttr} ${busyP}>${Settings.busy==="planning"?"正在生成纳管方案…":observations.length>1?`将 ${observations.length} 个相同版本位置一起纳管…`:otherEngines.length?`纳管并部署到 ${esc(otherEngines.join("/"))}…`:"纳管这个 Skill…"}</button>${otherEngines.length&&observations.length===1?`<button class="button ghost sm" data-adopt-catalog="${esc(item.logicalId)}" ${busyP}>仅纳管，不部署到其它引擎…</button>`:""}</div>`:"";const managed=record?`<section class="managed-controls"><h4>Ownward 纳管</h4><code>${esc(record.id)}</code><div>${engines.map(engine=>{const deployment=record.deployments.find(item=>item.engine===engine&&item.scope==="user"),healthy=observations.some(obs=>obs.engine===engine&&obs.ownership==="managed"&&obs.state==="healthy"),adapter=Settings.skills?.adapters?.find(item=>item.engine===engine),rootId=targetRootId(engine,deployment?.path);if(!writable||adapter?.capability!=="read-write")return`<span class="tag">${engine} 只读</span>`;if(deployment&&!healthy)return`<button class="button secondary sm" data-repair-skill="${esc(record.id)}" data-engine="${engine}" data-root-id="${esc(rootId)}">重新创建 ${engine} 受管链接…</button>`;if(!deployment&&engineRoots(engine).length)return`<button class="button secondary sm" data-expose-skill="${esc(record.id)}" data-engine="${engine}" data-root-id="${esc(rootId)}">部署到 ${engine}…</button>`;return`<span class="tag">${engine} ${healthy?"✓":deployment?"待修复":"不可用"}</span>`}).join("")}</div></section>`:"";return`<div class="eyebrow">UNIFIED SKILL</div><h3>${esc(item.name)}</h3><p>${esc(item.description||"没有公开描述")}</p>${adopt}${managed}<div class="skill-locations">${observations.map(obs=>`<article><strong>${esc(obs.engine)} · ${esc(obs.scope)}</strong><code>${esc(obs.displayPath||obs.entryPath)}</code><span>${esc(obs.ownership)} · ${esc(obs.state==="empty"?"空目录":obs.state)}</span>${writable&&obs.ownership==="discovered"&&!['bounded','unreadable','malformed','broken'].includes(obs.state)?`<button class="button danger sm" data-delete-observation="${esc(obs.id)}">删除此部署…</button>`:""}${migrateButtons(record,obs,writable)}${(obs.findings||[]).includes("conflict")?`<button class="button ghost sm" data-content-conflict="${esc(obs.id)}">允许 Agent 查看此冲突文本…</button>`:""}</article>`).join("")}</div>`}
/** 建议正文原先直接渲染裸 JSON：107 个重复、15 个冲突摆在一起时根本没法人工判断。
 *  这里解析成「动作 + Skill + 位置」；解析不出来就退回原始 ID，绝不猜路径。
 *  原始动作收进 <details> 备排障（summary 是交互元素，点它不会连带勾中复选框）。 */
function proposalObs(id){return(Settings.skills?.observations||[]).find(item=>item.id===id)}
function proposalObsLabel(id){const obs=proposalObs(id);return obs?`${obs.name} · ${obs.engine}${obs.scope?` · ${obs.scope}`:""} · ${obs.displayPath||obs.entryPath}`:id||"（未知位置）"}
function proposalSkillName(id){return Settings.registry?.skills?.find(skill=>skill.id===id)?.name||id||"（未知 Skill）"}
function proposalView(action){
  const kind=action?.kind;
  if(kind==="adopt"){const ids=action.observationIds||[];const digests=new Set(ids.map(id=>{const o=proposalObs(id);return o?(o.targetTreeDigest||o.treeDigest||""):""}));const same=digests.size===1&&!digests.has("");return{title:`纳管 ${proposalObs(ids[0])?.name||"Skill"}`,detail:ids.length>1?`${ids.length} 个${same?"相同版本位置":"位置，但内容并不相同——无法一起采纳，请逐个采纳或只勾一个"}：${ids.map(proposalObsLabel).join("；")}`:proposalObsLabel(ids[0])}}
  if(kind==="delete")return{title:"删除部署",detail:proposalObsLabel(action.observationId)};
  if(kind==="migrate")return{title:`迁移到 ${action.engine||"?"}${action.removeSource?"（并移除原部署）":""}`,detail:`${proposalSkillName(action.skillId)}${action.fromObservationId?` · 原部署 ${proposalObsLabel(action.fromObservationId)}`:""}`};
  if(kind==="repair")return{title:`重建 ${action.engine||"?"} 受管链接`,detail:proposalSkillName(action.skillId)};
  return{title:String(kind||"未知动作"),detail:""};
}
/** 0 条建议不等于「整理没跑」：得告诉用户为什么没有、下一步在哪。重复项纳管完就是 0，
 *  冲突项规则和 Agent 都不能替人选规范版本，只能指路到目录页。 */
/** 分析期间每秒问一次后端「到哪一步了」。没有这条，用户只能盯着灰掉的「Agent 分析中…」猜是不是卡死；
 *  「已收到 N KB」是模型真的在产出的硬证据，「已用 / 上限」告诉你最多还要等多久。 */
function fmtKB(bytes){return bytes<1024?`${bytes} B`:`${(bytes/1024).toFixed(1)} KB`}
const PHASE_LABEL={preparing:"准备 prompt",'waiting-model':"等待模型首字",receiving:"接收中",validating:"校验结果"};
function analysisProgressHtml(){const p=Settings.analysisProgress;if(!p)return`<div class="analysis-progress" id="analysis-progress"><span class="spin"></span>Agent 分析中…（正在连接）</div>`;const elapsed=Math.max(0,Math.round((Date.now()-Date.parse(p.startedAt))/1000)),limit=Math.round(p.timeoutMs/1000),pct=Math.min(100,Math.round(elapsed/limit*100));
  return`<div class="analysis-progress" id="analysis-progress"><span class="spin"></span><strong>${esc(PHASE_LABEL[p.phase]||p.phase)}</strong> · ${esc(p.model)} · 已送 ${p.observationsSent} 个观测（${fmtKB(p.promptBytes)}）${p.receivedBytes?` · 已收到 ${fmtKB(p.receivedBytes)}`:""} · <span class="mono">${elapsed}s / ${limit}s</span><i class="bar" style="width:${pct}%"></i></div>`}
function analysisDiagHtml(){const d=Settings.analysis?.diagnostics;if(!d)return"";const outcome={agent:"Agent 完成","agent-empty-scope":"没有可动的观测，未调用 Agent",timeout:`超时（${Math.round(d.timeoutMs/1000)}s）`,exit:"Agent 进程异常退出",malformed:"Agent 输出不是合法 JSON","invalid-shape":"Agent 返回结构不对",error:"调用异常"}[d.outcome]||d.outcome;
  return`<div class="analysis-diag">上次分析：${esc(outcome)} · ${esc(d.model)} · 送 ${d.observationsSent}/${d.observationsActionable} 个可动观测（${fmtKB(d.promptBytes)}）· 用时 ${(d.elapsedMs/1000).toFixed(0)}s${d.receivedBytes?` · 收到 ${fmtKB(d.receivedBytes)}`:""}${d.dropped?` · 丢弃 ${d.dropped} 条不合规`:""}</div>`}
async function pollAnalysisProgress(){try{Settings.analysisProgress=(await requestJSON("/api/skills/analysis/status")).body.progress||null}catch{}const el=$("#analysis-progress");if(el&&Settings.busy==="analysis")el.outerHTML=analysisProgressHtml()}
function proposalEmptyText(){const summary=Settings.skills?.summary||{},dup=summary.duplicates||0,conflicts=summary.conflicts||0;
  if(conflicts)return`没有可自动执行的建议。${dup?`还有 ${dup} 个重复；`:"重复项已全部纳管；"}${conflicts} 个冲突（同名但内容不同）需要你选一版为准——下面每条冲突都可以直接「查看两侧差异」再「以某一版为准」，另一侧会先备份再换成链接。`;
  if(dup)return`没有可自动执行的建议，但还有 ${dup} 个重复——试试「改用 Agent 整理」，或到「目录」里手动纳管。`;
  return"没有需要整理的 skill：重复项已全部纳管，也没有冲突。"}
function analysisStale(){const a=Settings.analysis,cur=Settings.skills?.mutableRevision;return !!(a&&a.inventoryMutableRevision&&cur&&a.inventoryMutableRevision!==cur)}
function skillAgentHtml(){if(Settings.analysis&&analysisStale())return`<div class="settings-callout"><strong>建议已过期</strong><span>生成这批建议之后 Skill 目录又变了（inventory ${esc(String(Settings.analysis.inventoryMutableRevision).slice(0,12))} → ${esc(String(Settings.skills?.mutableRevision).slice(0,12))}），里面引用的观测可能已经不存在。请重新分析。</span><button class="button secondary sm" id="skills-analyze" ${Settings.busy==="analysis"?"disabled":""}>${Settings.busy==="analysis"?"Agent 分析中…":"重新分析"}</button>${Settings.busy==="analysis"?analysisProgressHtml():""}</div>`;if(!Settings.analysis){const blocked=!Settings.skills||Settings.skills?.completeness==="partial"||controlPlaneFrozen()||Settings.busy==="analysis";
  // 规则是默认路径：同名同内容 → 纳管；空壳 → 删；冲突 / 技能包 / 失效 → 只提示。全部确定性、瞬时完成。
  // Agent 是可选项——它是唯一会提出错误建议的来源，只在用户明确要语义整理时才用。
  return`<div class="agent-analysis-empty"><div class="eyebrow">DEDUPE</div><h3>整理 Skill</h3><p>按规则找出跨引擎内容一致的重复项并合并为一份受管 Skill；空壳目录建议清理；同名不同内容、技能包只提示不动。</p><button class="button primary" id="skills-analyze-rules" ${blocked?"disabled":""}>${Settings.busy==="analysis"?"生成中…":"按规则生成建议"}</button><button class="button ghost sm" id="skills-analyze" ${blocked?"disabled":""}>用 Agent 分析（可选，只发元数据）</button>${Settings.busy==="analysis"?analysisProgressHtml():""}</div>`}const actions=Settings.analysis.actions||[],byAgent=String(Settings.analysis.source).startsWith("agent"),picked=[...Settings.selectedActions].filter(i=>i<actions.length).length;
  // 原先这里把 source=deterministic-fallback 直译成实现术语摆给用户看，没人知道那是什么、该怎么办：
  // 说清楚「没走 Agent、是规则按元数据生成的、要逐条审」，并给一个真的能改用 Agent 的入口。
  const analyzeBlocked=!Settings.skills||Settings.skills?.completeness==="partial"||controlPlaneFrozen();
  return`<div class="settings-callout"><strong>${byAgent?"Agent 建议":"规则生成的建议"}</strong><span>${byAgent?"":"按名称与内容指纹确定性生成：跨引擎内容一致的重复项建议纳管为一份，空壳目录建议清理；同名不同内容、技能包只提示不动。"}inventory ${esc(Settings.analysis.inventoryRevision?.slice(0,12))}</span>${byAgent?"":`<button class="button secondary sm" id="skills-analyze" ${analyzeBlocked||Settings.busy==="analysis"?"disabled":""}>${Settings.busy==="analysis"?"Agent 分析中…":"用 Agent 分析（可选）"}</button>`}${Settings.busy==="analysis"?analysisProgressHtml():analysisDiagHtml()}</div><div class="proposal-bar"><span class="count">已选 ${picked} / 共 ${actions.length}</span><button class="button ghost sm" id="skills-select-all" ${actions.length?"":"disabled"}>全选</button><button class="button ghost sm" id="skills-select-none" ${picked?"":"disabled"}>清空</button><span style="flex:1"></span><button class="button primary sm" id="skills-build-plan" ${!picked||controlPlaneFrozen()?"disabled":""}>审阅所选建议</button></div><div class="proposal-list">${actions.length?actions.map((action,index)=>{const view=proposalView(action);return`<label><input type="checkbox" data-proposal-index="${index}" ${Settings.selectedActions.has(index)?"checked":""}><span><strong>${esc(view.title)}</strong>${view.detail?`<small>${esc(view.detail)}</small>`:""}<details><summary>原始动作</summary><code>${esc(JSON.stringify(action))}</code></details></span></label>`}).join(""):stateBox(proposalEmptyText())}</div>${(Settings.analysis.notes||[]).map(note=>`<div class="settings-callout ${note.severity==="warning"?"warning":""}"><strong>${esc(note.code)}</strong><span>${esc(note.message)}</span>${conflictNoteActions(note)}</div>`).join("")}`}
// 冲突提示就地可处理：不用回目录。能选边的一侧才给按钮；技能包那一侧只提示。
function conflictNoteActions(note){if(note.code!=="CONTENT_CONFLICT"||controlPlaneFrozen()||Settings.skills?.completeness!=="complete")return"";const sides=conflictSides(note.observationIds||[]);if(sides.length<2)return"";const engines=["claude","codex","codebuddy"],busy=Settings.busy==="planning"?"disabled":"";return`<div class="conflict-actions">${sides.length===2?`<button class="button secondary sm" data-conflict-diff="${esc(sides.map(o=>o.id).join(","))}" ${busy}>查看两侧差异…</button>`:""}${sides.map(o=>{const others=engines.filter(e=>e!==o.engine&&sides.some(s=>s.engine===e)&&engineRoots(e).length&&Settings.skills?.adapters?.find(a=>a.engine===e)?.capability==="read-write");return`<button class="button secondary sm" data-adopt-one="${esc(o.id)}" data-expose="${esc(others.join(","))}" ${busy}>以 ${esc(o.engine)} 这一版为准${others.length?`，部署到 ${esc(others.join("/"))}`:""}…</button>`}).join("")}</div>`}
function skillHistoryHtml(){return`<div class="transaction-list">${Settings.transactions.length?Settings.transactions.map(tx=>`<article><div><strong>${esc(tx.phase)}</strong><code>${esc(tx.id)}</code><span>${esc(tx.updatedAt||tx.createdAt||"")}</span>${tx.errorCode?`<span class="tag warning">${esc(tx.errorCode)}</span>`:""}</div>${tx.phase==="committed"&&!controlPlaneFrozen()?`<button class="button secondary sm" data-rollback-tx="${esc(tx.id)}">审阅恢复方案</button>`:""}</article>`).join(""):stateBox("尚无 Skill 写操作记录")}</div>`}
function bindSkillControls(content){$("#skills-search",content)?.addEventListener("change",e=>{Settings.query=e.target.value;renderSettings()});if($("#skills-filter",content))$("#skills-filter",content).value=Settings.filter;$("#skills-filter",content)?.addEventListener("change",e=>{Settings.filter=e.target.value;renderSettings()});$("#skills-scan",content)?.addEventListener("click",()=>loadSkills(true));$$('[data-skill-id]',content).forEach(b=>b.addEventListener("click",()=>{Settings.selected=b.dataset.skillId;renderSettings()}));const enginesOf=b=>(b.dataset.expose||"").split(",").filter(Boolean);
  $$('[data-adopt-catalog]',content).forEach(b=>b.addEventListener("click",async()=>{const item=skillCatalog().find(item=>item.logicalId===b.dataset.adoptCatalog);if(!item){Settings.skillsError="所选 Skill 已变化，请重新扫描";renderSettings();return}const engines=enginesOf(b);const expose=engines.length?await resolveExpose(engines,{},b):[];if(expose===null)return;buildSkillPlan([{kind:"adopt",observationIds:item.observationIds,...(expose.length?{expose}:{})}],b)}));
  // 冲突选边：只纳管选中的那一版，并部署到其它引擎——目标根取另一侧现在所在的根，planner 对已存在路径走 replace-with-link（先备份）
  $$('[data-adopt-one]',content).forEach(b=>b.addEventListener("click",async()=>{const engines=enginesOf(b),hints={};for(const o of Settings.skills?.observations||[])if(engines.includes(o.engine)&&o.name===proposalObs(b.dataset.adoptOne)?.name&&o.id!==b.dataset.adoptOne)hints[o.engine]=o.displayPath||o.entryPath;const expose=engines.length?await resolveExpose(engines,hints,b):[];if(expose===null)return;buildSkillPlan([{kind:"adopt",observationIds:[b.dataset.adoptOne],...(expose.length?{expose}:{})}],b)}));
  $$('[data-conflict-diff]',content).forEach(b=>b.addEventListener("click",()=>showConflictDiff(b.dataset.conflictDiff.split(","),b)));$$('[data-delete-observation]',content).forEach(b=>b.addEventListener("click",()=>buildSkillPlan([{kind:"delete",observationId:b.dataset.deleteObservation}],b)));$$('[data-expose-skill]',content).forEach(b=>b.addEventListener("click",()=>chooseSkillRoot({kind:"migrate",skillId:b.dataset.exposeSkill,engine:b.dataset.engine,scope:"user",removeSource:false},b.dataset.rootId,b)));$$('[data-repair-skill]',content).forEach(b=>b.addEventListener("click",()=>chooseSkillRoot({kind:"repair",skillId:b.dataset.repairSkill,engine:b.dataset.engine,scope:"user"},b.dataset.rootId,b)));$$('[data-migrate-source]',content).forEach(b=>b.addEventListener("click",()=>chooseSkillRoot({kind:"migrate",skillId:b.dataset.skillId,fromObservationId:b.dataset.migrateSource,engine:b.dataset.engine,scope:"user",removeSource:true},b.dataset.rootId,b)));$$('[data-content-conflict]',content).forEach(b=>b.addEventListener("click",()=>reviewConflictContent(b.dataset.contentConflict,b)));$("#skills-analyze-rules",content)?.addEventListener("click",()=>runSkillAnalysis([],undefined,"rules"));$("#skills-analyze",content)?.addEventListener("click",()=>runSkillAnalysis([],undefined,"agent"));$("#skills-select-all",content)?.addEventListener("click",()=>{(Settings.analysis?.actions||[]).forEach((_,i)=>Settings.selectedActions.add(i));renderSettings()});
  $("#skills-select-none",content)?.addEventListener("click",()=>{Settings.selectedActions.clear();renderSettings()});
  $$('[data-proposal-index]',content).forEach(x=>x.addEventListener("change",()=>{const i=+x.dataset.proposalIndex;x.checked?Settings.selectedActions.add(i):Settings.selectedActions.delete(i);renderSettings()}));$("#skills-build-plan",content)?.addEventListener("click",()=>buildSkillPlan([...Settings.selectedActions].map(i=>Settings.analysis.actions[i]),$("#skills-build-plan",content)));$$('[data-rollback-tx]',content).forEach(b=>b.addEventListener("click",()=>reviewRollback(b.dataset.rollbackTx,b)))}
function chooseSkillRoot(action,rootId,returnEl){if(rootId){buildSkillPlan([{...action,targetRootId:rootId}],returnEl);return}const roots=engineRoots(action.engine),body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">EXPLICIT ROOT</div><h2 id="control-dialog-title">选择 ${esc(action.engine)} Skill 目录</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="proposal-list">${roots.map(root=>`<button class="skill-root-choice" data-root-choice="${esc(root.id)}"><strong>${esc(root.path)}</strong><span>${esc(root.capabilityReason||"已声明兼容")}</span></button>`).join("")}</div>`,returnEl);$$('[data-root-choice]',body).forEach(button=>button.addEventListener("click",()=>{$("#settings-dialog").close();buildSkillPlan([{...action,targetRootId:button.dataset.rootChoice}],returnEl)}))}
async function reviewConflictContent(id,returnEl){try{const group=(Settings.skills.observations||[]).filter(obs=>obs.name===(Settings.skills.observations||[]).find(item=>item.id===id)?.name&&(obs.findings||[]).includes("conflict")).map(obs=>obs.id),result=(await postJSON("/api/skills/analysis/preview",{expectedRevision:Settings.skills.mutableRevision,contentObservationIds:group})).body,body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">CONTENT OPT-IN</div><h2 id="control-dialog-title">允许比较 ${result.previews.length} 个冲突版本</h2></div><button class="button ghost" data-dialog-close>关闭</button></div>${result.previews.map(preview=>`<div class="settings-callout warning"><strong>版本 ${esc(preview.observationId.slice(0,8))}</strong><span>${preview.files.length} 个文本文件、${preview.bytes} 字节；排除 ${preview.excluded} 个脚本、附件、隐藏或二进制条目。</span></div><ul>${preview.files.map(file=>`<li><code>${esc(file.pathAlias)}</code> · ${file.bytes} bytes</li>`).join("")}</ul>`).join("")}<p>授权仅本次有效；HOME 与疑似密钥会脱敏。</p><div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="skills-content-confirm">允许并分析这些版本</button></div>`,returnEl);$("#skills-content-confirm",body).addEventListener("click",()=>{$("#settings-dialog").close();runSkillAnalysis(group,result.consentId,"agent")})}catch(error){toast(`${error.code||"预览失败"}：${error.message}`)}}
async function runSkillAnalysis(contentObservationIds=[],consentId,mode="rules"){Settings.busy="analysis";Settings.analysisProgress=null;renderSettings();clearInterval(Settings.progressTimer);if(mode==="agent")Settings.progressTimer=setInterval(pollAnalysisProgress,1000);try{Settings.analysis=(await postJSON("/api/skills/analysis",{expectedRevision:Settings.skills.mutableRevision,contentObservationIds,mode,...(consentId?{consentId}:{})})).body;Settings.selectedActions=new Set((Settings.analysis.actions||[]).map((_,i)=>i))}catch(error){toast(`${error.code||"分析失败"}：${error.message}`)}clearInterval(Settings.progressTimer);Settings.progressTimer=null;Settings.analysisProgress=null;Settings.busy="";renderSettings()}
async function buildSkillPlan(actions,returnEl){Settings.skillsError="";Settings.busy="planning";renderSettings();let nextPlan=null;try{nextPlan=(await postJSON("/api/skills/plan",{expectedRevision:Settings.skills.mutableRevision,actions})).body;Settings.plan=nextPlan}catch(error){Settings.skillsError=`${error.code||"计划失败"}：${error.message}`;toast(Settings.skillsError)}Settings.busy="";renderSettings();if(nextPlan)reviewSkillPlan(returnEl)}
function reviewSkillPlan(returnEl){const plan=Settings.plan,body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">FILESYSTEM PLAN</div><h2 id="control-dialog-title">审阅 ${plan.effects.length} 项 Skill 操作</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="approval-effects">${plan.effects.map(effect=>`<article data-danger="${effect.destructive}"><strong>${esc(effect.summary)}</strong><code>${esc(effect.path)}</code><small>${esc(effect.kind)}${effect.destructive?" · 将替换、移动或删除现有条目":" · 仅创建新条目"}</small></article>`).join("")}</div><div class="settings-callout warning"><strong>备份与回滚</strong><span>现有条目先进入 ~/.ownward/skills/backups；失败按相反顺序恢复。</span></div><div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="skills-approve-apply">批准并执行 ${plan.effects.length} 项操作</button></div>`,returnEl);$("#skills-approve-apply",body).addEventListener("click",()=>applySkillPlan(body))}
async function applySkillPlan(body){const button=$("#skills-approve-apply",body);button.disabled=true;button.textContent="正在执行…";Settings.skillsError="";try{const approval=(await postJSON(`/api/skills/plans/${encodeURIComponent(Settings.plan.id)}/approval`,{expectedPlanDigest:Settings.plan.digest})).body;Settings.transaction=(await postJSON("/api/skills/apply",{planId:Settings.plan.id,expectedPlanDigest:Settings.plan.digest,expectedRevision:Settings.skills.mutableRevision,idempotencyKey:randomKey(),approval:{id:approval.id,nonce:approval.nonce}})).body;$("#settings-dialog").close();await loadSkills(true);Settings.analysis=null;Settings.selectedActions.clear();Settings.plan=null;Settings.skillMode="history"}catch(error){if(error.code==="SKILL_TRANSACTION_CONFLICT"){Settings.plan=null;$("#settings-dialog").close();Settings.skillsError="这个方案上一次执行失败并已自动回滚（错误码见「操作记录」），同一方案不能重复提交。请重新点「审阅」生成新方案。";toast(Settings.skillsError);renderSettings();return}button.disabled=false;button.textContent=`批准并执行 ${Settings.plan.effects.length} 项操作`;Settings.skillsError=`${error.code||"执行失败"}：${error.message}`;toast(Settings.skillsError)}renderSettings()}
// 恢复前必须拿**服务端当前**的清单，不能信页面缓存：daemon 重启后 GET /api/skills 是 404
// （SKILL_SCAN_REQUIRED），页面的 Settings.skills 就是 null——而操作记录现在不依赖扫描也能打开，
// 于是 Settings.skills.mutableRevision 直接空指针（2026-09-03 实测）。审批把 revision 烧进摘要，
// 门比的是服务端此刻的快照，所以本来就该现取。
async function currentInventory(){try{return(await requestJSON("/api/skills")).body}catch(error){if(error.status===404||error.code==="SKILL_SCAN_REQUIRED")return(await postJSON("/api/skills/scan",{})).body;throw error}}
// 冲突两侧逐文件差异：给用户看清「只是路径不同」还是真的两个版本，再决定以哪一版为准。
// 部署到别的引擎时定目标根：给了现有部署路径就用它所在的根（原地换成链接）；否则根唯一就直用；
// 多个根（codex 有 ~/.agents/skills 和 ~/.codex/skills）就逐个弹选择。planner 对多根要求显式 targetRootId。
async function resolveExpose(engines,hintPathByEngine={},returnEl){const out=[];for(const engine of engines){let rootId=targetRootId(engine,hintPathByEngine[engine]);if(!rootId){const roots=engineRoots(engine);if(roots.length===1)rootId=roots[0].id;else rootId=await new Promise(resolve=>{const body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">EXPLICIT ROOT</div><h2 id="control-dialog-title">部署到 ${esc(engine)}：选择目录</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="proposal-list">${roots.map(root=>`<button class="skill-root-choice" data-root-choice="${esc(root.id)}"><strong>${esc(root.path)}</strong><span>${esc(root.capabilityReason||"已声明兼容")}</span></button>`).join("")}</div>`,returnEl);$$('[data-root-choice]',body).forEach(b=>b.addEventListener("click",()=>{$("#settings-dialog").close();resolve(b.dataset.rootChoice)}));$("#settings-dialog").addEventListener("close",()=>resolve(""),{once:true})})}if(!rootId)return null;out.push({engine,scope:"user",targetRootId:rootId})}return out}
// 冲突组里能「选为准」的一侧：discovered、健康、不是技能包（整包纳管会被 planner 拒）
function conflictSides(ids){return(Settings.skills?.observations||[]).filter(o=>ids.includes(o.id)&&(o.findings||[]).includes("conflict")&&o.ownership==="discovered"&&!(o.nestedSkills>0)&&!['bounded','unreadable','malformed','broken','empty'].includes(o.state))}
async function showConflictDiff(ids,returnEl){const sides=conflictSides(ids).slice(0,2);const item={name:sides[0]?.name||"?"};if(sides.length!==2){toast("差异比较需要恰好两个冲突项");return}
  try{const d=(await postJSON("/api/skills/conflict-diff",{expectedRevision:Settings.skills.mutableRevision,observationIds:sides.map(o=>o.id)})).body;
    const label=o=>`${o.engine} · ${o.displayPath||o.entryPath}`,changed=d.files.filter(f=>f.status!=="same"),same=d.files.length-changed.length;
    const rows=changed.map(f=>f.status==="different"?`<details open><summary><code>${esc(f.path)}</code> · ${f.lines.length}${f.truncated?"+":""} 行不同</summary><table class="diff-table"><tbody>${f.lines.map(l=>`<tr><td>${l.n}</td><td>${esc(l.left??"（无）")}</td><td>${esc(l.right??"（无）")}</td></tr>`).join("")}</tbody></table></details>`:`<div><code>${esc(f.path)}</code> · ${f.status==="only-left"?"只在左侧":"只在右侧"}</div>`).join("");
    openDialog(`<div class="dialog-head"><div><div class="eyebrow">CONFLICT</div><h2 id="control-dialog-title">${esc(item.name)} 两侧差异</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><p class="diff-legend"><span>左：${esc(label(sides[0]))}</span><span>右：${esc(label(sides[1]))}</span></p><p>${same} 个文件相同，${changed.length} 个不同。选一版为准后，另一侧的目录会先备份、再换成指向受管副本的链接。</p><div class="diff-files">${rows||"<div>可比较的文本文件没有差异（差异可能在脚本、附件或被裁剪的部分）</div>"}</div><div class="dialog-actions">${sides.map((o,i)=>`<button class="button ${i?"secondary":"primary"}" data-diff-pick="${esc(o.id)}" data-expose="${esc(sides.filter(x=>x!==o).map(x=>x.engine).join(","))}">以${i?"右":"左"}侧（${esc(o.engine)}）为准…</button>`).join("")}</div>`,returnEl);
    $$('[data-diff-pick]',$("#settings-dialog-body")).forEach(b=>b.addEventListener("click",async()=>{const engines=(b.dataset.expose||"").split(",").filter(Boolean),hints={};for(const o of sides)if(o.id!==b.dataset.diffPick)hints[o.engine]=o.displayPath||o.entryPath;$("#settings-dialog").close();const expose=engines.length?await resolveExpose(engines,hints,returnEl):[];if(expose===null)return;buildSkillPlan([{kind:"adopt",observationIds:[b.dataset.diffPick],...(expose.length?{expose}:{})}],returnEl)}));
  }catch(error){toast(`${error.code||"差异比较失败"}：${error.message}`)}}
async function reviewRollback(id,returnEl){try{const preview=(await requestJSON(`/api/skills/transactions/${encodeURIComponent(id)}/rollback-plan`)).body,body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">CONDITIONAL ROLLBACK</div><h2 id="control-dialog-title">恢复 Skill 事务</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="approval-effects">${preview.effects.map(effect=>`<article data-danger="true"><strong>${esc(effect.summary)}</strong><code>${esc(effect.path)}</code><small>${esc(effect.action)}</small></article>`).join("")}</div><div class="settings-callout warning"><strong>仅在上述后置条件仍匹配时恢复</strong><span>如果路径已被后来事务或人工修改，Ownward 会拒绝覆盖，并要求根据当前状态生成新的逆向方案。</span></div><div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="skills-confirm-rollback">批准执行 ${preview.effects.length} 项恢复操作</button></div>`,returnEl);$("#skills-confirm-rollback",body).addEventListener("click",async()=>{try{const inventory=await currentInventory();Settings.skills=inventory;const approval=(await postJSON(`/api/skills/transactions/${encodeURIComponent(id)}/rollback/approval`,{expectedRevision:inventory.mutableRevision})).body;Settings.transaction=(await postJSON(`/api/skills/transactions/${encodeURIComponent(id)}/rollback`,{expectedRevision:inventory.mutableRevision,approval:{id:approval.id,nonce:approval.nonce}})).body;$("#settings-dialog").close();await loadSkills(true)}catch(error){toast(`${error.code||"恢复失败"}：${error.message}`)}renderSettings()})}catch(error){toast(`${error.code||"恢复方案不可用"}：${error.message}`)}}

/** 日报/周报规则编辑器（追加到「自动化」分类）：结构化编辑 routine 的启用/时间/取材窗口/星期，写回 routines.json。 */
window.renderRoutinesEditor = async function (content) {
  if (!content) return;
  const wrap = document.createElement("section");
  wrap.className = "settings-group";
  wrap.innerHTML = `<div class="settings-group-title">日报 / 周报 / 月度复盘</div><div id="routines-rules">${stateBox("加载中…", "loading")}</div>`;
  content.appendChild(wrap);
  const rules = await getJSON("/api/routines/rules").catch(() => null);
  const el = wrap.querySelector("#routines-rules");
  if (!rules) { el.innerHTML = stateBox("无法载入 routine 规则", "error"); return; }
  if (!Array.isArray(rules) || !rules.length) { el.innerHTML = `<div class="settings-callout"><span>暂无周期职责。样例见 examples/routines.json。</span></div>`; return; }
  const WD = ["日", "一", "二", "三", "四", "五", "六"];
  el.innerHTML = rules.map((r) => `<article class="settings-field editable" data-routine="${esc(r.id)}">
    <div><label><h4>${esc(r.name || r.id)}</h4></label>${r.docUrl ? `<a class="settings-path mono" href="${esc(r.docUrl)}" target="_blank" rel="noopener">飞书文档 ↗</a>` : `<span class="settings-path mono">${esc(r.id)}</span>`}</div>
    <div class="settings-editor routine-editor">
      <label class="setting-switch"><input type="checkbox" data-rk="enabled" ${r.enabled ? "checked" : ""}><span>${r.enabled ? "已启用" : "已停用"}</span></label>
      <div class="routine-row"><label class="routine-inline">时间 <input type="time" data-rk="time" value="${esc(r.time || "")}"></label>
      <label class="routine-inline">取材 <select data-rk="window"><option value="yesterday" ${r.window === "yesterday" ? "selected" : ""}>上一个工作日</option><option value="week" ${r.window === "week" ? "selected" : ""}>本周</option><option value="month" ${r.window === "month" ? "selected" : ""}>上个自然月</option></select></label></div>
      <label class="routine-inline">周期 <select data-rk="cadence"><option value="weekly" ${r.cadence !== "monthly" ? "selected" : ""}>按星期</option><option value="monthly" ${r.cadence === "monthly" ? "selected" : ""}>每月首个周一前的周日</option></select></label>
      <div class="routine-days"><span>星期（按星期时生效）</span>${WD.map((w, i) => `<label class="routine-day"><input type="checkbox" data-rk="day" value="${i}" ${(r.days || []).includes(i) ? "checked" : ""}>${w}</label>`).join("")}</div>
      <label>覆盖人员（逗号分隔，留空使用本人姓名）<input type="text" data-rk="people" value="${esc((r.people || []).join("，"))}"></label>
      <label>会议材料来源（选择已有职责的文档）<select multiple data-rk="refRoutines" aria-label="会议材料来源">${rules.filter((ref) => ref.id !== r.id).map((ref) => `<option value="${esc(ref.id)}" ${(r.refRoutines || []).includes(ref.id) ? "selected" : ""}>${esc(ref.name || ref.id)}</option>`).join("")}</select></label>
      <div><button class="button primary sm" data-routine-save="${esc(r.id)}">保存规则</button>${r.refRoutines?.length ? ` <button class="button secondary sm" data-routine-archive="${esc(r.id)}">刷新会议归档</button> <button class="button ghost sm" data-routine-archive-status="${esc(r.id)}">查看归档状态</button>` : ""}</div>
      <p data-archive-result role="status"></p>
    </div></article>`).join("");
  el.querySelectorAll("[data-routine-save]").forEach((b) => b.addEventListener("click", async () => {
    const art = b.closest("[data-routine]"), id = b.dataset.routineSave;
    const patch = {
      enabled: art.querySelector('[data-rk="enabled"]').checked,
      time: art.querySelector('[data-rk="time"]').value,
      window: art.querySelector('[data-rk="window"]').value,
      cadence: art.querySelector('[data-rk="cadence"]').value,
      people: art.querySelector('[data-rk="people"]').value.split(/[,，\n]/).map((x) => x.trim()).filter(Boolean),
      refRoutines: [...art.querySelector('[data-rk="refRoutines"]').selectedOptions].map((x) => x.value),
      days: [...art.querySelectorAll('[data-rk="day"]:checked')].map((x) => +x.value),
    };
    b.disabled = true;
    try {
      const res = await post("/api/routines/rules", { id, patch });
      toast(res.msg || (res.ok ? "已保存" : "失败"));
    } catch { toast("保存失败，请重试"); }
    finally { b.disabled = false; }
  }));
  el.querySelectorAll("[data-routine-archive]").forEach((b) => b.addEventListener("click", async () => {
    b.disabled = true;
    try { const res = await post("/api/routines/archive", { id: b.dataset.routineArchive }); b.closest("[data-routine]").querySelector("[data-archive-result]").textContent = res.ok ? `已归档 ${res.sources.length} 个来源。可在今日页单独生成月报。` : (res.msg || "归档失败，已保存的旧版本保留"); toast(res.msg || (res.ok ? "会议材料已归档" : "归档失败")); }
    catch { toast("归档失败，请重试"); }
    finally { b.disabled = false; }
  }));
  el.querySelectorAll("[data-routine-archive-status]").forEach((b) => b.addEventListener("click", async () => {
    b.disabled = true;
    const result = b.closest("[data-routine]").querySelector("[data-archive-result]");
    try {
      const res = await getJSON(`/api/routines/archive?id=${encodeURIComponent(b.dataset.routineArchiveStatus)}`);
      result.textContent = res?.ok ? (res.sources.map((s) => `${s.name}：${s.status === "ready" ? `已归档 ${s.fetchedAt} · ${s.hash.slice(0, 12)}` : "尚无可用归档，请刷新"}`).join("；") || "没有配置会议来源") : (res?.msg || "读取状态失败");
    } catch { result.textContent = "读取状态失败，请重试"; }
    finally { b.disabled = false; }
  }));
};

/** 从任意 tab 跳到对应设置分类（tab↔设置联动）。 */
window.openSettings = function (category) {
  if (category) Settings.category = category;
  switchTab("settings");
  if (category) setTimeout(() => { if (typeof renderSettings === "function") renderSettings(); }, 0);
};
