"use strict";
/* Settings + Skill Control Plane：写操作始终先生成确定性 diff/plan，再由浏览器会话批准。 */
const Settings={category:"general",schema:null,effective:null,settingsError:"",draft:new Map(),validation:null,validateTimer:null,operation:null,operationTimer:null,pollFailures:0,pollStarted:0,skills:null,registry:null,skillsError:"",skillMode:"catalog",query:"",filter:"all",selected:"",analysis:null,selectedActions:new Set(),plan:null,transaction:null,transactions:[],busy:"",dialogReturn:null};
const SETTING_CATEGORIES=[["general","通用","称呼、时区与 Vault"],["system","系统与运行","运行健康、组件与计划"],["engines","AI 引擎","Provider、模型与权限"],["skills","Skills","跨引擎发现、整理与纳管"],["sources","事件源","飞书、GitHub、Gmail 与股票"],["automation","自动化","心跳、日报与分流"],["notifications","通知","macOS 与飞书提醒"],["advanced","高级","网络、命令与诊断"]];
const CATEGORY_ROOTS={general:["owner","timezone","quietHours","vault"],engines:["chat","llm","providers","dispatch","engine","architecture"],sources:["connectors"],automation:["heartbeat","digest","triage"],notifications:["notify"],advanced:["dashboard","strategy"]};
const LABELS={owner:"Owner",timezone:"时区",quietHours:"静默时段",vault:"知识库",chat:"对话",llm:"后台 AI",providers:"Provider",dispatch:"任务派发",engine:"会话引擎",architecture:"架构权限",connectors:"事件源",heartbeat:"心跳",digest:"日报",triage:"事件分流",notify:"通知",dashboard:"Dashboard",strategy:"策略",enabled:"启用",port:"端口",listen:"监听范围",root:"目录",name:"称呼",intervalMin:"间隔（分钟）",model:"模型",allowFullAccess:"允许完整访问",allowedRoots:"授权目录"};
const TERMINAL_SETTINGS=new Set(["committed","restored","manual-repair"]),TERMINAL_SKILLS=new Set(["committed","rolled-back","manual-repair"]);
const controlPlaneFrozen=()=>Settings.operation?.phase==="manual-repair"||Settings.transaction?.phase==="manual-repair"||Settings.transactions.some(tx=>tx.phase==="manual-repair");
async function requestJSON(url,options={}){const response=await fetch(url,options),text=await response.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={message:text}}if(!response.ok){const error=new Error(body?.error?.message||body?.message||`${url} → ${response.status}`);error.status=response.status;error.code=body?.error?.code||body?.error;error.body=body;throw error}return{status:response.status,body}}
const postJSON=(url,body)=>requestJSON(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body||{})});
const pointerParts=p=>p.slice(1).split("/").map(x=>x.replaceAll("~1","/").replaceAll("~0","~"));
const valueAt=(root,p)=>pointerParts(p).reduce((value,key)=>value?.[key],root);const labelFor=p=>pointerParts(p).map(k=>LABELS[k]||k).join(" · ");
const jsonValue=v=>typeof v==="string"?v:JSON.stringify(v),randomKey=()=>`${Date.now()}-${crypto.randomUUID()}`;

TABS.settings={init(root){root.innerHTML=`<aside class="settings-sidebar"><div class="page-head compact"><div><div class="eyebrow">CONTROL PLANE</div><h1>设置</h1><p>配置与多引擎 Skill 的统一控制面</p></div></div><nav class="settings-categories" aria-label="设置分类">${SETTING_CATEGORIES.map(([id,label,desc])=>`<button type="button" data-settings-category="${id}" aria-current="false"><strong>${label}</strong><span>${desc}</span><i id="settings-count-${id}"></i></button>`).join("")}</nav></aside><div class="settings-main"><div class="settings-toolbar"><div><h2 id="settings-title">通用</h2><p id="settings-subtitle"></p></div><button class="button ghost sm" id="settings-refresh" type="button">刷新</button></div><div class="settings-scroll" id="settings-content" aria-live="polite"></div><footer class="settings-apply" id="settings-footer"><span id="settings-footer-state"></span><div><button class="button ghost sm" id="settings-discard" type="button" hidden>全部放弃</button> <button class="button primary" id="settings-review" type="button" disabled>审阅并应用</button></div></footer></div><dialog class="control-dialog" id="settings-dialog" aria-labelledby="control-dialog-title"><div id="settings-dialog-body"></div></dialog>`;$$('[data-settings-category]',root).forEach(b=>b.addEventListener("click",async()=>{Settings.category=b.dataset.settingsCategory;if(Settings.category==="skills"&&!Settings.skills)await loadSkills(false);renderSettings()}));$("#settings-refresh",root).addEventListener("click",()=>Settings.category==="skills"?loadSkills(true):loadSettings(false));$("#settings-discard",root).addEventListener("click",()=>{Settings.draft.clear();Settings.validation=null;renderSettings()});$("#settings-review",root).addEventListener("click",reviewSettings);$("#settings-dialog",root).addEventListener("close",()=>Settings.dialogReturn?.focus?.());window.addEventListener("beforeunload",e=>{if(Settings.draft.size){e.preventDefault();e.returnValue=""}});loadSettings(true)},show(){renderSettings()}};

async function loadSettings(initial){const content=$("#settings-content");if(!content)return;if(initial)content.innerHTML=stateBox("正在读取设置…","loading");Settings.settingsError="";const operationId=new URLSearchParams(location.search).get("settingsOperation"),operationUrl=operationId?`/api/settings/operations/${encodeURIComponent(operationId)}`:"/api/settings/operations/current";const[schema,effective,current]=await Promise.allSettled([requestJSON("/api/settings/schema"),requestJSON("/api/settings/effective"),requestJSON(operationUrl)]);if(schema.status==="fulfilled")Settings.schema=schema.value.body;if(effective.status==="fulfilled")Settings.effective=effective.value.body;if(current.status==="fulfilled"&&current.value.body.operation){Settings.operation=current.value.body.operation;if(!TERMINAL_SETTINGS.has(Settings.operation.phase))pollSettingsOperation()}if(!Settings.schema||!Settings.effective)Settings.settingsError="设置服务暂时不可用；运行状态仍可在「系统」查看。";if(Settings.draft.size)scheduleValidation();renderSettings()}
function renderSettings(){const root=$("#settings-root");if(!root||!$("#settings-content"))return;const meta=SETTING_CATEGORIES.find(([id])=>id===Settings.category)||SETTING_CATEGORIES[0];$("#settings-title").textContent=meta[1];$("#settings-subtitle").textContent=meta[2];$$('[data-settings-category]',root).forEach(b=>{const on=b.dataset.settingsCategory===Settings.category;b.dataset.on=on;b.setAttribute("aria-current",on?"page":"false")});if(Settings.category==="system")window.renderSystemInSettings?.($("#settings-content"));else if(Settings.category==="skills")renderSkills($("#settings-content"));else if(Settings.settingsError)$("#settings-content").innerHTML=stateBox(Settings.settingsError,"error");else{renderConfig($("#settings-content"),Settings.category);if(Settings.category==="automation")window.renderRoutinesEditor?.($("#settings-content"))}renderFooter()}
function schemaFields(){const out=[];const walk=(nodes,pointer="")=>Object.entries(nodes||{}).forEach(([key,node])=>{const path=`${pointer}/${key.replaceAll("~","~0").replaceAll("/","~1")}`;node.type==="object"?walk(node.children,path):out.push({pointer:path,...node})});walk(Settings.schema?.nodes);return out}
const categoryFields=category=>schemaFields().filter(field=>field.metadata?.editable&&(CATEGORY_ROOTS[category]||[]).includes(pointerParts(field.pointer)[0]));
function shownValue(field){const patch=Settings.draft.get(field.pointer);if(patch?.op==="set")return patch.value;if(patch?.op==="remove")return field.default;return valueAt(Settings.effective?.effective||{},field.pointer)}
function fieldId(pointer){return`setting-${btoa(unescape(encodeURIComponent(pointer))).replaceAll("=","")}`}
// 已知可枚举字段 → 下拉选项（schema 未带 enum，按 pointer 末段/正则硬编码）。免手写框、减少输错。
const SELECT_OPTIONS={listen:[["local","仅本机 (127.0.0.1)"],["all","局域网可访问 (0.0.0.0)"]],engine:[["claude","Claude Code"],["codex","Codex"],["codebuddy","CodeBuddy"],["codechat","CodeChat"]],provider:[["","跟随系统默认"],["claude","Claude Code"],["codex","Codex"],["codebuddy","CodeBuddy"]],permission:[["","跟随引擎默认"],["safe","safe（需要审批）"],["bypass","bypass（完整权限）"]],identity:[["user","用户身份"],["bot","机器人身份"]]};
const TZ_LIST=["Asia/Shanghai","Asia/Hong_Kong","Asia/Tokyo","Asia/Singapore","America/New_York","America/Los_Angeles","Europe/London","UTC"];
function selectOptionsFor(pointer){const seg=pointer.split("/").pop();return SELECT_OPTIONS[seg]||null;}
function fieldControl(field){const value=shownValue(field),pointer=esc(field.pointer),id=fieldId(field.pointer);if(field.type==="boolean")return`<label class="setting-switch"><input id="${id}" data-setting-pointer="${pointer}" type="checkbox" ${value?"checked":""}><span>${value?"已开启":"已关闭"}</span></label>`;if(field.type==="array")return`<textarea id="${id}" data-setting-pointer="${pointer}" data-setting-type="array" rows="2" spellcheck="false">${esc(JSON.stringify(value??[]))}</textarea>`;const opts=selectOptionsFor(field.pointer);if(opts&&field.type!=="number"){const cur=String(value??"");const known=opts.some(([v])=>String(v)===cur);return`<select id="${id}" data-setting-pointer="${pointer}" data-setting-type="${field.type}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===cur?"selected":""}>${esc(l)}</option>`).join("")}${known?"":`<option value="${esc(cur)}" selected>${esc(cur||"（未设置）")}</option>`}</select>`;}if(/\/timezone$/.test(field.pointer)){return`<input id="${id}" list="tz-datalist" data-setting-pointer="${pointer}" data-setting-type="${field.type}" type="text" value="${esc(value??"")}"><datalist id="tz-datalist">${TZ_LIST.map(z=>`<option value="${z}">`).join("")}</datalist>`;}const inputType=field.type==="number"?"number":/\/(?:time|start|end)$/.test(field.pointer)?"time":"text";return`<input id="${id}" data-setting-pointer="${pointer}" data-setting-type="${field.type}" type="${inputType}" value="${esc(value??"")}" ${field.metadata?.sensitive?'autocomplete="off"':""}>`}
// 分组：按配置子对象聚合，做成层级（飞书/GitHub… 各自成组）。>2 段用前两段当组，否则用第一段。
const GROUP_NAMES={lark:"飞书",github:"GitHub",gmail:"邮件（Gmail）",stock:"股票",owner:"身份",vault:"知识库",quietHours:"静默时段",providers:"Provider",dispatch:"任务派发",defaults:"派发默认值",architecture:"架构权限",heartbeat:"心跳",digest:"日报",triage:"事件分流",timezone:"时区",notify:"通知",dashboard:"Dashboard",strategy:"策略",chat:"对话",llm:"后台 AI",engine:"会话引擎"};
// 叶子字段的短标签：分组后不再重复「事件源·lark·」前缀，只显示末段人话名。
const LEAF_LABELS={enabled:"启用",pollMin:"轮询间隔（分钟）",intervalMin:"间隔（分钟）",groupPolicy:"群消息策略",maxBatch:"单次上限",time:"时间",port:"端口",listen:"监听范围",root:"目录",dir:"默认项目目录",provider:"默认引擎",permission:"默认权限",name:"称呼",model:"默认模型",identity:"身份",start:"开始",end:"结束",allowFullAccess:"允许完整访问",allowedRoots:"授权目录",timezone:"时区",engine:"引擎",aheadMin:"提前量（分钟）",window:"取材窗口",checkTimes:"检查时点",watchlist:"自选标的"};
function groupKeyOf(pointer){const parts=pointerParts(pointer);return parts.length>2?parts.slice(0,2).join("/"):parts[0];}
function groupLabelOf(key){const seg=key.split("/").pop();return GROUP_NAMES[seg]||LABELS[seg]||seg;}
function leafLabelOf(pointer){const seg=pointerParts(pointer).pop();return LEAF_LABELS[seg]||LABELS[seg]||seg;}
function settingFieldHtml(field,issues,short){const dirty=Settings.draft.has(field.pointer),overridden=Settings.effective?.provenance?.[field.pointer]==="override",issue=issues.get(field.pointer);return`<article class="settings-field editable" data-dirty="${dirty}" data-risk="${field.metadata?.risk||"low"}"><div><label for="${fieldId(field.pointer)}"><h4>${esc(short?leafLabelOf(field.pointer):labelFor(field.pointer))}</h4></label><span class="settings-path mono">${esc(field.pointer)}</span><div class="setting-badges">${overridden?"<span>本机覆盖</span>":"<span>沿用默认</span>"}${dirty?"<strong>待应用</strong>":""}${field.metadata?.risk!=="low"?"<em>高风险</em>":""}</div></div><div class="settings-editor">${fieldControl(field)}<div class="setting-actions">${overridden?`<button type="button" class="button ghost sm" data-setting-remove="${esc(field.pointer)}">沿用默认值</button>`:""}${dirty?`<button type="button" class="button ghost sm" data-setting-undo="${esc(field.pointer)}">撤销</button>`:""}</div>${issue?`<p class="setting-error" role="alert">${esc(issue)}</p>`:""}</div></article>`}
// 真层级：一个配置子对象 = 一个父分组。它的「启用」字段升为分组头上的总开关，其余字段作为子项缩进嵌在下面。
function settingGroupHtml(key,fields,issues){const enableField=fields.find(f=>pointerParts(f.pointer).pop()==="enabled");const rest=fields.filter(f=>f!==enableField);if(!enableField&&fields.length===1)return settingFieldHtml(fields[0],issues,false);const on=enableField?!!shownValue(enableField):true;return`<section class="settings-group" data-enabled="${on}"><header class="settings-group-head"><div class="settings-group-title">${esc(groupLabelOf(key))}</div>${enableField?`<div class="settings-group-switch">${fieldControl(enableField)}</div>`:""}</header>${rest.length?`<div class="settings-group-body">${rest.map(f=>settingFieldHtml(f,issues,true)).join("")}</div>`:""}</section>`}
function renderConfig(content,category){if(!Settings.schema||!Settings.effective){content.innerHTML=stateBox("正在读取设置…","loading");return}const fields=categoryFields(category),issues=new Map((Settings.validation?.issues||[]).map(x=>[x.path,x.message]));const groups=new Map();for(const f of fields){const k=groupKeyOf(f.pointer);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(f)}const body=fields.length?[...groups.entries()].map(([k,fs])=>settingGroupHtml(k,fs,issues)).join(""):`<div class="settings-callout"><strong>本分类暂无可编辑字段</strong><span>内部配置只在系统诊断中展示。</span></div>`;content.innerHTML=(Settings.operation?operationBanner(Settings.operation,"settings"):"")+body;$$('[data-setting-pointer]',content).forEach(input=>input.addEventListener("change",settingChanged));$$('[data-setting-remove]',content).forEach(b=>b.addEventListener("click",()=>{Settings.draft.set(b.dataset.settingRemove,{op:"remove",path:b.dataset.settingRemove});scheduleValidation();renderSettings()}));$$('[data-setting-undo]',content).forEach(b=>b.addEventListener("click",()=>{Settings.draft.delete(b.dataset.settingUndo);scheduleValidation();renderSettings()}))}
function settingChanged(e){const input=e.currentTarget,path=input.dataset.settingPointer,type=input.dataset.settingType||(input.type==="checkbox"?"boolean":"string");let value;try{value=type==="boolean"?input.checked:type==="number"?Number(input.value):type==="array"?JSON.parse(input.value):input.value}catch{Settings.validation={valid:false,issues:[{path,message:"请输入合法 JSON 数组"}]};renderSettings();return}Settings.draft.set(path,{op:"set",path,value});scheduleValidation();renderSettings()}
function scheduleValidation(){clearTimeout(Settings.validateTimer);Settings.validation=Settings.draft.size?{state:"validating",issues:[]}:null;if(Settings.draft.size)Settings.validateTimer=setTimeout(validateDraft,300)}
async function validateDraft(){try{Settings.validation=(await postJSON("/api/settings/validate",{sourceDigest:Settings.effective.sourceDigest,patches:[...Settings.draft.values()]})).body}catch(error){Settings.validation={valid:false,stale:error.status===409,issues:error.body?.issues||[{path:"",message:error.message}]}}renderSettings()}
function renderFooter(){const footer=$("#settings-footer"),state=$("#settings-footer-state"),review=$("#settings-review"),discard=$("#settings-discard");if(!footer)return;footer.hidden=Settings.category==="skills"||Settings.category==="system";if(footer.hidden)return;const draftCount=Settings.draft.size,v=Settings.validation,n=v?.valid?v.normalizedPatches?.length??draftCount:draftCount,frozen=controlPlaneFrozen();discard.hidden=!draftCount;review.disabled=!n||v?.state==="validating"||v?.valid!==true||frozen||Settings.operation&&!TERMINAL_SETTINGS.has(Settings.operation.phase);state.innerHTML=frozen?"<strong>控制面已冻结</strong> · 需要先完成人工恢复":!draftCount||v?.valid&&!n?"<strong>配置已同步</strong> · 没有有效修改":v?.state==="validating"?`<strong>正在校验 ${draftCount} 项修改…</strong>`:v?.stale?"<strong>配置已被外部修改</strong> · 草稿仍保留，请刷新后重新检查":v?.valid?`<strong>${n} 项待应用</strong> · 将事务化重启 Ownward`:`<strong>${v?.issues?.length||1} 项需要处理</strong>`}
function openDialog(html,returnEl){Settings.dialogReturn=returnEl||document.activeElement;const dialog=$("#settings-dialog"),body=$("#settings-dialog-body");body.innerHTML=html;dialog.showModal();$$('[data-dialog-close]',body).forEach(b=>b.addEventListener("click",()=>dialog.close()));return body}
function reviewSettings(e){if(!Settings.validation?.valid)return;const diff=Settings.validation.redactedDiff||[],confirmations=Settings.validation.risk?.confirmations||[];const body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">HUMAN APPROVAL</div><h2 id="control-dialog-title">审阅 ${diff.length} 项配置变更</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="approval-effects">${diff.map(item=>`<article><strong>${esc(labelFor(item.path))}</strong><code>${esc(jsonValue(item.before))}</code><span>→</span><code>${esc(jsonValue(item.after))}</code><small>${esc(item.path)} · ${item.risk}</small></article>`).join("")}</div>${confirmations.length?`<div class="approval-confirmations">${confirmations.map(item=>`<label><input type="checkbox" data-confirmation="${esc(item)}"> 我理解并确认：${esc(item)}</label>`).join("")}</div>`:""}<div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="settings-approve-apply">批准并重启 Ownward</button></div>`,e?.currentTarget);$("#settings-approve-apply",body).addEventListener("click",()=>applySettings(confirmations,body))}
async function applySettings(confirmations,body){const button=$("#settings-approve-apply",body),checked=$$('[data-confirmation]:checked',body).map(x=>x.dataset.confirmation);if(confirmations.some(item=>!checked.includes(item))){toast("请逐项确认高风险影响");return}button.disabled=true;button.textContent="正在创建审批…";const payload={sourceDigest:Settings.effective.sourceDigest,patches:[...Settings.draft.values()],confirmations:checked};try{const approval=(await postJSON("/api/settings/approve",payload)).body;button.textContent="正在启动事务…";const result=(await postJSON("/api/settings/apply",{...payload,approvalId:approval.approvalId,idempotencyKey:randomKey()})).body;Settings.operation=result.operation;$("#settings-dialog").close();history.replaceState(null,"",`${location.pathname}?tab=settings&settingsOperation=${encodeURIComponent(Settings.operation.id)}`);pollSettingsOperation();renderSettings()}catch(error){button.disabled=false;button.textContent="批准并重启 Ownward";toast(`${error.code||"应用失败"}：${error.message}`)}}
function operationBanner(operation,domain){const terminal=domain==="settings"?TERMINAL_SETTINGS:TERMINAL_SKILLS,bad=["manual-repair","restored","rolled-back"].includes(operation.phase);return`<div class="operation-banner" data-state="${bad?"error":terminal.has(operation.phase)?"done":"running"}" role="${bad?"alert":"status"}"><strong>${domain==="settings"?"设置事务":"Skill 事务"} · ${esc(operation.phase)}</strong><span>${operation.error?.message?esc(operation.error.message):operation.errorCode?esc(operation.errorCode):terminal.has(operation.phase)?"事务已结束":"正在执行或恢复，请稍候"}</span><code>${esc(operation.id)}</code></div>`}
function pollSettingsOperation(){clearTimeout(Settings.operationTimer);if(!Settings.operation||TERMINAL_SETTINGS.has(Settings.operation.phase))return;if(!Settings.pollStarted)Settings.pollStarted=Date.now();Settings.operationTimer=setTimeout(async()=>{const path=`/api/settings/operations/${Settings.operation.id}`;try{Settings.operation=(await requestJSON(path)).body.operation;Settings.pollFailures=0}catch{Settings.pollFailures++;const candidate=Settings.operation.origins?.candidate;if(Settings.pollFailures>=5&&candidate&&candidate!==location.origin){location.assign(`${candidate}/?tab=settings&settingsOperation=${encodeURIComponent(Settings.operation.id)}`);return}if(Date.now()-Settings.pollStarted>180000){Settings.operation={...Settings.operation,error:{message:"无法连接旧或候选地址。请检查端口、代理与 TLS 后重新打开 Settings。"}};renderSettings();return}}if(Settings.operation?.phase==="committed"){Settings.draft.clear();Settings.validation=null;Settings.pollStarted=0;await loadSettings(false)}renderSettings();pollSettingsOperation()},1200)}

async function loadSkills(scan){Settings.skillsError="";Settings.busy=scan?"scanning":Settings.busy;if(scan)renderSettings();try{Settings.skills=(await(scan?postJSON("/api/skills/scan",{}):requestJSON("/api/skills"))).body;const[tx,registry]=await Promise.all([requestJSON("/api/skills/transactions").catch(()=>({body:[]})),requestJSON("/api/skills/registry").catch(()=>({body:{skills:[]}}))]);Settings.transactions=Array.isArray(tx.body)?tx.body:tx.body.transactions||[];Settings.registry=registry.body}catch(error){Settings.skillsError=error.code==="SKILL_SCAN_REQUIRED"||error.status===404?"尚未扫描 Skill":`Skill inventory 暂时不可用：${error.message}`}Settings.busy="";renderSettings()}
function skillCatalog(){let catalog;if(Array.isArray(Settings.skills?.catalog))catalog=Settings.skills.catalog.map(item=>({...item}));else{const groups=new Map();for(const item of Settings.skills?.observations||[]){const group=groups.get(item.name)||{logicalId:item.name,name:item.name,description:item.description,observationIds:[],engines:[],scopes:[],findings:[]};group.observationIds.push(item.id);if(!group.engines.includes(item.engine))group.engines.push(item.engine);if(!group.scopes.includes(item.scope))group.scopes.push(item.scope);for(const finding of item.findings||[])if(!group.findings.includes(finding))group.findings.push(finding);groups.set(item.name,group)}catalog=[...groups.values()]}for(const managed of Settings.registry?.skills||[]){const existing=catalog.find(item=>item.name===managed.name&&item.digest===managed.digest);if(existing){existing.managedSkillId=managed.id;continue}catalog.push({logicalId:`managed:${managed.id}`,managedSkillId:managed.id,name:managed.name,description:managed.description,digest:managed.digest,ownership:"managed",observationIds:[],engines:[...new Set(managed.deployments.map(item=>item.engine))],scopes:[...new Set(managed.deployments.map(item=>item.scope))],findings:["broken"]})}return catalog.sort((a,b)=>a.name.localeCompare(b.name))}
function renderSkills(content){const items=skillCatalog(),summary=Settings.skills?.summary||{},partial=Settings.skills?.completeness==="partial",adapters=Settings.skills?.adapters||[],frozen=controlPlaneFrozen();$("#settings-count-skills").textContent=(summary.duplicates||0)+(summary.conflicts||0)||"";content.innerHTML=`${Settings.transaction?operationBanner(Settings.transaction,"skills"):""}<div class="skill-control-tabs" role="tablist"><button role="tab" aria-selected="${Settings.skillMode==="catalog"}" data-skill-mode="catalog" data-on="${Settings.skillMode==="catalog"}">目录</button><button role="tab" aria-selected="${Settings.skillMode==="agent"}" data-skill-mode="agent" data-on="${Settings.skillMode==="agent"}">Agent 建议</button><button role="tab" aria-selected="${Settings.skillMode==="history"}" data-skill-mode="history" data-on="${Settings.skillMode==="history"}">操作记录</button></div>${frozen?`<div class="settings-callout warning" role="alert"><strong>控制面已冻结</strong><span>manual-repair 未完成前禁止设置与 Skill 写操作。</span></div>`:""}${partial?`<div class="settings-callout warning"><strong>扫描结果不完整，所有写操作已禁用</strong><span>${esc((Settings.skills.warnings||[]).join("；"))}</span></div>`:""}${adapters.some(a=>a.capability!=="read-write")?`<div class="settings-callout warning"><strong>部分引擎已降级为只读</strong><span>${adapters.map(a=>`${a.engine}: ${a.capability}${a.reason?`（${a.reason}）`:""}`).join(" · ")}</span></div>`:""}${Settings.skillMode==="catalog"?skillCatalogHtml(items):Settings.skillMode==="agent"?skillAgentHtml():skillHistoryHtml()}`;$$('[data-skill-mode]',content).forEach(b=>b.addEventListener("click",()=>{Settings.skillMode=b.dataset.skillMode;renderSettings()}));bindSkillControls(content)}
function skillCatalogHtml(items){if(Settings.skillsError&&!Settings.skills)return`<div class="settings-callout"><strong>${esc(Settings.skillsError)}</strong><button class="button secondary" id="skills-scan">开始只读扫描</button></div>`;const shown=items.filter(item=>!Settings.query||`${item.name} ${item.description||""} ${(item.engines||[]).join(" ")}`.toLowerCase().includes(Settings.query.toLowerCase())).filter(item=>Settings.filter==="all"||(item.findings||[]).includes(Settings.filter));const selected=shown.find(x=>x.logicalId===Settings.selected)||shown[0];if(selected)Settings.selected=selected.logicalId;return`<div class="skills-summary"><div><strong>${items.length}</strong><span>统一 Skills</span></div><div><strong>${Settings.skills?.summary?.duplicates||0}</strong><span>重复</span></div><div><strong>${Settings.skills?.summary?.conflicts||0}</strong><span>冲突</span></div><div><strong>${Settings.skills?.summary?.protected||0}</strong><span>受保护</span></div></div><div class="skills-tools"><input type="search" id="skills-search" placeholder="搜索名称或引擎" value="${esc(Settings.query)}"><select id="skills-filter"><option value="all">全部状态</option><option value="duplicate">重复</option><option value="conflict">冲突</option><option value="protected">受保护</option><option value="broken">失效</option></select><button class="button secondary sm" id="skills-scan">${Settings.busy==="scanning"?"扫描中…":"重新扫描"}</button></div><div class="skills-browser"><div class="skills-list">${shown.length?shown.map(item=>`<button class="skill-row" data-skill-id="${esc(item.logicalId)}" aria-pressed="${item.logicalId===Settings.selected}"><span class="skill-row-main"><strong>${esc(item.name)}</strong><small>${esc((item.engines||[]).join(" · ")||"未部署")}</small></span><span class="skill-state" data-state="${esc((item.findings||["ok"])[0]||"ok")}">${esc((item.findings||[]).join(" / ")||"正常")}</span></button>`).join(""):stateBox("没有符合筛选条件的 Skill")}</div><aside class="skill-detail">${selected?skillDetailHtml(selected):stateBox("选择一个 Skill 查看详情")}</aside></div>`}
function engineRoots(engine){return(Settings.skills?.roots||[]).filter(root=>root.engine===engine&&root.scope==="user"&&!root.protected&&["read-write","explicit-only"].includes(root.mutationCapability))}
function targetRootId(engine,deploymentPath){const roots=engineRoots(engine);if(deploymentPath){const matched=roots.find(root=>deploymentPath===`${root.path}/${deploymentPath.split("/").pop()}`);if(matched)return matched.id}return roots.length===1&&roots[0].mutationCapability==="read-write"?roots[0].id:""}
function migrateButtons(record,obs,writable){if(!record||!writable||!record.sources.some(source=>source.path===(obs.displayPath||obs.entryPath)))return"";return["claude","codex","codebuddy"].filter(engine=>engine!==obs.engine&&engineRoots(engine).length).map(engine=>`<button class="button danger sm" data-migrate-source="${esc(obs.id)}" data-skill-id="${esc(record.id)}" data-engine="${engine}" data-root-id="${esc(targetRootId(engine))}">迁移到 ${engine} 并移除此部署…</button>`).join("")}
function skillDetailHtml(item){const observations=(Settings.skills?.observations||[]).filter(x=>item.observationIds.includes(x.id)),writable=!controlPlaneFrozen()&&Settings.skills?.completeness==="complete",record=Settings.registry?.skills?.find(skill=>skill.name===item.name&&(!item.digest||skill.digest===item.digest)),engines=["claude","codex","codebuddy"];const managed=record?`<section class="managed-controls"><h4>Ownward 纳管</h4><code>${esc(record.id)}</code><div>${engines.map(engine=>{const deployment=record.deployments.find(item=>item.engine===engine&&item.scope==="user"),healthy=observations.some(obs=>obs.engine===engine&&obs.ownership==="managed"&&obs.state==="healthy"),adapter=Settings.skills.adapters?.find(item=>item.engine===engine),rootId=targetRootId(engine,deployment?.path);if(!writable||adapter?.capability!=="read-write")return`<span class="tag">${engine} 只读</span>`;if(deployment&&!healthy)return`<button class="button secondary sm" data-repair-skill="${esc(record.id)}" data-engine="${engine}" data-root-id="${esc(rootId)}">重新创建 ${engine} 受管链接…</button>`;if(!deployment&&engineRoots(engine).length)return`<button class="button secondary sm" data-expose-skill="${esc(record.id)}" data-engine="${engine}" data-root-id="${esc(rootId)}">部署到 ${engine}…</button>`;return`<span class="tag">${engine} ${healthy?"✓":deployment?"待修复":"不可用"}</span>`}).join("")}</div></section>`:"";return`<div class="eyebrow">UNIFIED SKILL</div><h3>${esc(item.name)}</h3><p>${esc(item.description||"没有公开描述")}</p>${managed}<div class="skill-locations">${observations.map(obs=>`<article><strong>${esc(obs.engine)} · ${esc(obs.scope)}</strong><code>${esc(obs.displayPath||obs.entryPath)}</code><span>${esc(obs.ownership)} · ${esc(obs.state)}</span>${writable&&obs.ownership==="discovered"&&!['bounded','unreadable','malformed','broken'].includes(obs.state)?`<button class="button secondary sm" data-adopt-observation="${esc(obs.id)}">以此版本纳管</button><button class="button danger sm" data-delete-observation="${esc(obs.id)}">删除此部署…</button>`:""}${migrateButtons(record,obs,writable)}${(obs.findings||[]).includes("conflict")?`<button class="button ghost sm" data-content-conflict="${esc(obs.id)}">允许 Agent 查看此冲突文本…</button>`:""}</article>`).join("")}</div>`}
function skillAgentHtml(){if(!Settings.analysis)return`<div class="agent-analysis-empty"><div class="eyebrow">METADATA ONLY</div><h3>让本机 Agent 梳理 Skill</h3><p>只发送名称、脱敏描述、摘要、引擎、作用域、大小与路径别名；不会发送 Skill 正文、脚本、附件或凭据。</p><button class="button primary" id="skills-analyze" ${!Settings.skills||Settings.skills.completeness==="partial"||controlPlaneFrozen()?"disabled":""}>${Settings.busy==="analysis"?"Agent 分析中…":"让 Agent 整理"}</button></div>`;const actions=Settings.analysis.actions||[];return`<div class="settings-callout"><strong>${String(Settings.analysis.source).startsWith("agent")?"Agent 建议":"确定性降级建议"}</strong><span>inventory ${esc(Settings.analysis.inventoryRevision?.slice(0,12))}</span></div><div class="proposal-list">${actions.length?actions.map((action,index)=>`<label><input type="checkbox" data-proposal-index="${index}" ${Settings.selectedActions.has(index)?"checked":""}><span><strong>${esc(action.kind)}</strong><code>${esc(JSON.stringify(action))}</code></span></label>`).join(""):stateBox("没有可自动执行的建议；冲突项需要人工选择规范版本。")}</div>${(Settings.analysis.notes||[]).map(note=>`<div class="settings-callout ${note.severity==="warning"?"warning":""}"><strong>${esc(note.code)}</strong><span>${esc(note.message)}</span></div>`).join("")}<button class="button primary" id="skills-build-plan" ${!Settings.selectedActions.size||controlPlaneFrozen()?"disabled":""}>审阅所选建议</button>`}
function skillHistoryHtml(){return`<div class="transaction-list">${Settings.transactions.length?Settings.transactions.map(tx=>`<article><div><strong>${esc(tx.phase)}</strong><code>${esc(tx.id)}</code><span>${esc(tx.updatedAt||tx.createdAt||"")}</span></div>${tx.phase==="committed"&&!controlPlaneFrozen()?`<button class="button secondary sm" data-rollback-tx="${esc(tx.id)}">审阅恢复方案</button>`:""}</article>`).join(""):stateBox("尚无 Skill 写操作记录")}</div>`}
function bindSkillControls(content){$("#skills-search",content)?.addEventListener("change",e=>{Settings.query=e.target.value;renderSettings()});if($("#skills-filter",content))$("#skills-filter",content).value=Settings.filter;$("#skills-filter",content)?.addEventListener("change",e=>{Settings.filter=e.target.value;renderSettings()});$("#skills-scan",content)?.addEventListener("click",()=>loadSkills(true));$$('[data-skill-id]',content).forEach(b=>b.addEventListener("click",()=>{Settings.selected=b.dataset.skillId;renderSettings()}));$$('[data-adopt-observation]',content).forEach(b=>b.addEventListener("click",()=>buildSkillPlan([{kind:"adopt",observationIds:[b.dataset.adoptObservation]}],b)));$$('[data-delete-observation]',content).forEach(b=>b.addEventListener("click",()=>buildSkillPlan([{kind:"delete",observationId:b.dataset.deleteObservation}],b)));$$('[data-expose-skill]',content).forEach(b=>b.addEventListener("click",()=>chooseSkillRoot({kind:"migrate",skillId:b.dataset.exposeSkill,engine:b.dataset.engine,scope:"user",removeSource:false},b.dataset.rootId,b)));$$('[data-repair-skill]',content).forEach(b=>b.addEventListener("click",()=>chooseSkillRoot({kind:"repair",skillId:b.dataset.repairSkill,engine:b.dataset.engine,scope:"user"},b.dataset.rootId,b)));$$('[data-migrate-source]',content).forEach(b=>b.addEventListener("click",()=>chooseSkillRoot({kind:"migrate",skillId:b.dataset.skillId,fromObservationId:b.dataset.migrateSource,engine:b.dataset.engine,scope:"user",removeSource:true},b.dataset.rootId,b)));$$('[data-content-conflict]',content).forEach(b=>b.addEventListener("click",()=>reviewConflictContent(b.dataset.contentConflict,b)));$("#skills-analyze",content)?.addEventListener("click",()=>runSkillAnalysis([]));$$('[data-proposal-index]',content).forEach(x=>x.addEventListener("change",()=>{const i=+x.dataset.proposalIndex;x.checked?Settings.selectedActions.add(i):Settings.selectedActions.delete(i);renderSettings()}));$("#skills-build-plan",content)?.addEventListener("click",()=>buildSkillPlan([...Settings.selectedActions].map(i=>Settings.analysis.actions[i]),$("#skills-build-plan",content)));$$('[data-rollback-tx]',content).forEach(b=>b.addEventListener("click",()=>reviewRollback(b.dataset.rollbackTx,b)))}
function chooseSkillRoot(action,rootId,returnEl){if(rootId){buildSkillPlan([{...action,targetRootId:rootId}],returnEl);return}const roots=engineRoots(action.engine),body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">EXPLICIT ROOT</div><h2 id="control-dialog-title">选择 ${esc(action.engine)} Skill 目录</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="proposal-list">${roots.map(root=>`<button class="skill-root-choice" data-root-choice="${esc(root.id)}"><strong>${esc(root.path)}</strong><span>${esc(root.capabilityReason||"已声明兼容")}</span></button>`).join("")}</div>`,returnEl);$$('[data-root-choice]',body).forEach(button=>button.addEventListener("click",()=>{$("#settings-dialog").close();buildSkillPlan([{...action,targetRootId:button.dataset.rootChoice}],returnEl)}))}
async function reviewConflictContent(id,returnEl){try{const group=(Settings.skills.observations||[]).filter(obs=>obs.name===(Settings.skills.observations||[]).find(item=>item.id===id)?.name&&(obs.findings||[]).includes("conflict")).map(obs=>obs.id),result=(await postJSON("/api/skills/analysis/preview",{expectedRevision:Settings.skills.revision,contentObservationIds:group})).body,body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">CONTENT OPT-IN</div><h2 id="control-dialog-title">允许比较 ${result.previews.length} 个冲突版本</h2></div><button class="button ghost" data-dialog-close>关闭</button></div>${result.previews.map(preview=>`<div class="settings-callout warning"><strong>版本 ${esc(preview.observationId.slice(0,8))}</strong><span>${preview.files.length} 个文本文件、${preview.bytes} 字节；排除 ${preview.excluded} 个脚本、附件、隐藏或二进制条目。</span></div><ul>${preview.files.map(file=>`<li><code>${esc(file.pathAlias)}</code> · ${file.bytes} bytes</li>`).join("")}</ul>`).join("")}<p>授权仅本次有效；HOME 与疑似密钥会脱敏。</p><div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="skills-content-confirm">允许并分析这些版本</button></div>`,returnEl);$("#skills-content-confirm",body).addEventListener("click",()=>{$("#settings-dialog").close();runSkillAnalysis(group,result.consentId)})}catch(error){toast(`${error.code||"预览失败"}：${error.message}`)}}
async function runSkillAnalysis(contentObservationIds=[],consentId){Settings.busy="analysis";renderSettings();try{Settings.analysis=(await postJSON("/api/skills/analysis",{expectedRevision:Settings.skills.revision,contentObservationIds,...(consentId?{consentId}:{})})).body;Settings.selectedActions=new Set((Settings.analysis.actions||[]).map((_,i)=>i))}catch(error){toast(`${error.code||"分析失败"}：${error.message}`)}Settings.busy="";renderSettings()}
async function buildSkillPlan(actions,returnEl){try{Settings.plan=(await postJSON("/api/skills/plan",{expectedRevision:Settings.skills.revision,actions})).body;reviewSkillPlan(returnEl)}catch(error){toast(`${error.code||"计划失败"}：${error.message}`)}}
function reviewSkillPlan(returnEl){const plan=Settings.plan,body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">FILESYSTEM PLAN</div><h2 id="control-dialog-title">审阅 ${plan.effects.length} 项 Skill 操作</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="approval-effects">${plan.effects.map(effect=>`<article data-danger="${effect.destructive}"><strong>${esc(effect.summary)}</strong><code>${esc(effect.path)}</code><small>${esc(effect.kind)}${effect.destructive?" · 将替换、移动或删除现有条目":" · 仅创建新条目"}</small></article>`).join("")}</div><div class="settings-callout warning"><strong>备份与回滚</strong><span>现有条目先进入 ~/.ownward/skills/backups；失败按相反顺序恢复。</span></div><div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="skills-approve-apply">批准并执行 ${plan.effects.length} 项操作</button></div>`,returnEl);$("#skills-approve-apply",body).addEventListener("click",()=>applySkillPlan(body))}
async function applySkillPlan(body){const button=$("#skills-approve-apply",body);button.disabled=true;button.textContent="正在执行…";try{const approval=(await postJSON(`/api/skills/plans/${encodeURIComponent(Settings.plan.id)}/approval`,{expectedPlanDigest:Settings.plan.digest})).body;Settings.transaction=(await postJSON("/api/skills/apply",{planId:Settings.plan.id,expectedPlanDigest:Settings.plan.digest,expectedRevision:Settings.skills.revision,idempotencyKey:randomKey(),approval:{id:approval.id,nonce:approval.nonce}})).body;$("#settings-dialog").close();await loadSkills(true);Settings.skillMode="history"}catch(error){button.disabled=false;button.textContent=`批准并执行 ${Settings.plan.effects.length} 项操作`;toast(`${error.code||"执行失败"}：${error.message}`)}renderSettings()}
async function reviewRollback(id,returnEl){try{const preview=(await requestJSON(`/api/skills/transactions/${encodeURIComponent(id)}/rollback-plan`)).body,body=openDialog(`<div class="dialog-head"><div><div class="eyebrow">CONDITIONAL ROLLBACK</div><h2 id="control-dialog-title">恢复 Skill 事务</h2></div><button class="button ghost" data-dialog-close>关闭</button></div><div class="approval-effects">${preview.effects.map(effect=>`<article data-danger="true"><strong>${esc(effect.summary)}</strong><code>${esc(effect.path)}</code><small>${esc(effect.action)}</small></article>`).join("")}</div><div class="settings-callout warning"><strong>仅在上述后置条件仍匹配时恢复</strong><span>如果路径已被后来事务或人工修改，Ownward 会拒绝覆盖，并要求根据当前状态生成新的逆向方案。</span></div><div class="dialog-actions"><button class="button ghost" data-dialog-close>取消</button><button class="button primary" id="skills-confirm-rollback">批准执行 ${preview.effects.length} 项恢复操作</button></div>`,returnEl);$("#skills-confirm-rollback",body).addEventListener("click",async()=>{try{const approval=(await postJSON(`/api/skills/transactions/${encodeURIComponent(id)}/rollback/approval`,{expectedRevision:Settings.skills.revision})).body;Settings.transaction=(await postJSON(`/api/skills/transactions/${encodeURIComponent(id)}/rollback`,{expectedRevision:Settings.skills.revision,approval:{id:approval.id,nonce:approval.nonce}})).body;$("#settings-dialog").close();await loadSkills(true)}catch(error){toast(`${error.code||"恢复失败"}：${error.message}`)}renderSettings()})}catch(error){toast(`${error.code||"恢复方案不可用"}：${error.message}`)}}

/** 日报/周报规则编辑器（追加到「自动化」分类）：结构化编辑 routine 的启用/时间/取材窗口/星期，写回 routines.json。 */
window.renderRoutinesEditor = async function (content) {
  if (!content) return;
  const wrap = document.createElement("section");
  wrap.className = "settings-group";
  wrap.innerHTML = `<div class="settings-group-title">日报 / 周报规则</div><div id="routines-rules">${stateBox("加载中…", "loading")}</div>`;
  content.appendChild(wrap);
  const rules = await getJSON("/api/routines/rules").catch(() => null);
  const el = wrap.querySelector("#routines-rules");
  if (!rules) { el.innerHTML = stateBox("无法载入 routine 规则", "error"); return; }
  if (!Array.isArray(rules) || !rules.length) { el.innerHTML = `<div class="settings-callout"><span>暂无周期职责。样例见 examples/routines.json。</span></div>`; return; }
  const WD = ["日", "一", "二", "三", "四", "五", "六"];
  el.innerHTML = rules.map((r) => `<article class="settings-field editable" data-routine="${esc(r.id)}">
    <div><label><h4>${esc(r.name || r.id)}</h4></label>${r.docUrl ? `<a class="settings-path mono" href="${esc(r.docUrl)}" target="_blank" rel="noopener">飞书文档 ↗</a>` : `<span class="settings-path mono">${esc(r.id)}</span>`}</div>
    <div class="settings-editor routine-editor">
      <label class="setting-switch"><input type="checkbox" data-rk="enabled" ${r.enabled ? "checked" : ""}><span>${r.enabled ? "已启用" : "已停用"}</span></label>
      <div class="routine-row"><label class="routine-inline">时间 <input type="time" data-rk="time" value="${esc(r.time || "")}"></label>
      <label class="routine-inline">取材 <select data-rk="window"><option value="yesterday" ${r.window === "yesterday" ? "selected" : ""}>昨天</option><option value="week" ${r.window === "week" ? "selected" : ""}>本周</option></select></label></div>
      <div class="routine-days"><span>星期</span>${WD.map((w, i) => `<label class="routine-day"><input type="checkbox" data-rk="day" value="${i}" ${(r.days || []).includes(i) ? "checked" : ""}>${w}</label>`).join("")}</div>
      <button class="button primary sm" data-routine-save="${esc(r.id)}">保存规则</button>
    </div></article>`).join("");
  el.querySelectorAll("[data-routine-save]").forEach((b) => b.addEventListener("click", async () => {
    const art = b.closest("[data-routine]"), id = b.dataset.routineSave;
    const patch = {
      enabled: art.querySelector('[data-rk="enabled"]').checked,
      time: art.querySelector('[data-rk="time"]').value,
      window: art.querySelector('[data-rk="window"]').value,
      days: [...art.querySelectorAll('[data-rk="day"]:checked')].map((x) => +x.value),
    };
    b.disabled = true;
    const res = await post("/api/routines/rules", { id, patch });
    toast(res.msg || (res.ok ? "已保存" : "失败"));
    b.disabled = false;
  }));
};

/** 从任意 tab 跳到对应设置分类（tab↔设置联动）。 */
window.openSettings = function (category) {
  if (category) Settings.category = category;
  switchTab("settings");
  if (category) setTimeout(() => { if (typeof renderSettings === "function") renderSettings(); }, 0);
};
